json_file_rename_name_ascii – JSON-Fortran
json_file_rename_name_ascii Subroutine
Jacob Williams
8 statements
Source File
private subroutine json_file_rename_name_ascii(me, path, name, found)
Wrapper for json_file_rename where “name” is kind=CDK).
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CK, len=*), intent(in) :: path
the path to the variable
character(kind=CDK, len=*), intent(in) :: name
the new name
logical(kind=LK), intent(out), optional :: found
if the variable was found
Calls
Source Code
    subroutine json_file_rename_name_ascii(me,path,name,found)
    implicit none
    class(json_file),intent(inout)       :: me
    character(kind=CK,len=*),intent(in)  :: path   !! the path to the variable
    character(kind=CDK,len=*),intent(in) :: name   !! the new name
    logical(LK),intent(out),optional     :: found  !! if the variable was found
    call me%json_file_rename(path,to_unicode(name),found)
    end subroutine json_file_rename_name_ascii
Call graph
json_file_rename_name_ascii calls to_unicode, json_file_rename
to_unicode calls to_uni, to_uni_vec