json_file_destroy – JSON-Fortran
json_file_destroy Subroutine
Jacob Williams
9 statements
Source File
private subroutine json_file_destroy(me, destroy_core)
Destroy the json_value data in a json_file. This may be done when the variable is no longer needed, or will be reused to open a different file. Otherwise a memory leak will occur.
Optionally, also destroy the json_core instance (this is not necessary to prevent memory leaks, since a json_core does not use pointers).
See also
json_file_nullify
History
12/9/2013 : Created
4/26/2016 : Added optional destroy_core argument
Note
This routine will be called automatically when the variable goes out of scope.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
logical, intent(in), optional :: destroy_core
to also destroy the json_core. default is to leave it as is.
Calls
Called by
Source Code
    subroutine json_file_destroy(me,destroy_core)
    implicit none
    class(json_file),intent(inout) :: me
    logical,intent(in),optional :: destroy_core  !! to also destroy the [[json_core(type)]].
                                                 !! default is to leave it as is.
    if (associated(me%p)) call me%core%destroy(me%p)
    if (present(destroy_core)) then
        if (destroy_core) call me%core%destroy()
    end if
    end subroutine json_file_destroy
Call graph
json_file_destroy calls destroy
json_value_destroy calls destroy, destroy_json_data
assign_string_to_json_file calls json_file_destroy, deserialize
finalize_json_file calls json_file_destroy
json_file_add calls json_file_destroy
json_file_load calls json_file_destroy
json_file_load_from_string calls json_file_destroy
wrap_assign_string_to_json_file calls assign_string_to_json_file
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2