json_value_destroy – JSON-Fortran
json_value_destroy Subroutine
Jacob Williams
1/22/2014
43 statements
Source File
private pure recursive subroutine json_value_destroy(json, p, destroy_next)
Destroy a json_value linked-list structure.
Note
The original FSON version of this routine was not properly freeing the memory. It was rewritten.
Note
This routine destroys this variable, it’s children, and (if destroy_next is true) the subsequent elements in an object or array. It does not destroy the parent or previous elements.
Note
There is some protection here to enable destruction of improperly-created linked lists. However, likely there are cases not handled. Use the json_value_validate method to validate a JSON structure that was manually created using json_value pointers.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
variable to destroy
logical(kind=LK), intent(in), optional :: destroy_next
if true, then p%next is also destroyed (default is true)
Calls
Called by
Source Code
    pure recursive subroutine json_value_destroy(json,p,destroy_next)
    implicit none
    class(json_core),intent(inout)  :: json
    type(json_value),pointer        :: p            !! variable to destroy
    logical(LK),intent(in),optional :: destroy_next !! if true, then `p%next`
                                                    !! is also destroyed (default is true)
    logical(LK)              :: des_next  !! local copy of `destroy_next`
                                          !! optional argument
    type(json_value),pointer :: child     !! for getting child elements
    logical                  :: circular  !! to check to malformed linked lists
    if (associated(p)) then
        if (present(destroy_next)) then
            des_next = destroy_next
        else
            des_next = .true.
        end if
        if (allocated(p%name)) deallocate(p%name)
        call destroy_json_data(p)
        if (associated(p%next)) then
            ! check for circular references:
            if (associated(p, p%next)) nullify(p%next)
        end if
        if (associated(p%children)) then
            do while (p%n_children > 0)
                child => p%children
                if (associated(child)) then
                    p%children => p%children%next
                    p%n_children = p%n_children - 1
                    ! check children for circular references:
                    circular = (associated(p%children) .and. &
                                associated(p%children,child))
                    call json%destroy(child,destroy_next=.false.)
                    if (circular) exit
                else
                    ! it is a malformed JSON object. But, we will
                    ! press ahead with the destroy process, since
                    ! otherwise, there would be no way to destroy it.
                    exit
                end if
            end do
            nullify(p%children)
            nullify(child)
        end if
        if (associated(p%next) .and. des_next) call json%destroy(p%next)
        nullify(p%previous)
        nullify(p%parent)
        nullify(p%tail)
        if (associated(p)) deallocate(p)
        nullify(p)
    end if
    end subroutine json_value_destroy
Call graph
json_value_destroy calls destroy, destroy_json_data
json_file_destroy calls destroy
json_file_valid_path_op calls destroy, valid_path
json_value_remove calls destroy
parse_array calls destroy, parse_value, add
parse_object calls destroy, parse_object, parse_value, add
assign_string_to_json_file calls json_file_destroy, deserialize
finalize_json_file calls json_file_destroy
json_file_add calls json_file_destroy
json_file_load calls json_file_destroy, load
json_file_load_from_string calls json_file_destroy, deserialize
json_value_remove_if_present calls json_value_remove, get
json_value_replace calls json_value_remove
parse_value calls parse_array, parse_object
convert calls json_value_replace, info
json_add_integer_by_path calls json_value_replace, create, info
json_add_integer_vec_by_path calls json_value_replace, create, info, add
json_add_logical_by_path calls json_value_replace, create, info
json_add_logical_vec_by_path calls json_value_replace, create, info, add
json_add_member_by_path calls json_value_replace, create, info
json_add_real_by_path calls json_value_replace, create, info
json_add_real_vec_by_path calls json_value_replace, create, info, add
json_add_string_by_path calls json_value_replace, create, info
json_add_string_vec_by_path calls json_value_replace, create, info, add
json_parse_file calls parse_value
json_parse_string calls parse_value
wrap_assign_string_to_json_file calls assign_string_to_json_file
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_file_remove calls remove_if_present
json_get_by_path_jsonpath_bracket calls convert, add
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
wrap_json_file_load_from_string calls deserialize
wrap_json_value_remove_if_present calls remove_if_present
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_create_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_get_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_update_integer calls add_by_path, get, info
json_update_logical calls add_by_path, get, info
json_update_real calls add_by_path, get, info
json_update_string calls add_by_path, get, info
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_parse_string calls deserialize
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
wrap_json_file_remove calls remove
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_string_info calls get, info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_valid_path calls get
wrap_json_create_by_path calls create
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_value_get_child_by_name calls get
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_file_valid_path calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_value_add_member calls info
json_value_reverse calls info
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_valid_path calls valid_path
json_value_print calls json_is_vector, json_value_print
json_check_children_for_duplicate_keys calls get_path
json_get_by_path_default calls add
json_print_to_unit calls json_value_print
json_value_add_integer calls add
json_value_add_integer_vec calls add
json_value_add_logical calls add
json_value_add_logical_vec calls add
json_value_add_null calls add
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add
json_value_add_string calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
json_value_to_string calls json_value_print
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string