json_file_print_error_message – JSON-Fortran
json_file_print_error_message Subroutine
6 statements
Source File
private subroutine json_file_print_error_message(me, io_unit)
This is a wrapper for json_print_error_message.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
integer, intent(in), optional :: io_unit
Calls
Source Code
    subroutine json_file_print_error_message(me,io_unit)
    implicit none
    class(json_file),intent(inout) :: me
    integer, intent(in), optional  :: io_unit
    call me%core%print_error_message(io_unit)
    end subroutine json_file_print_error_message
Call graph
json_file_print_error_message calls json_print_error_message
json_print_error_message calls integer_to_string, json_check_for_errors, json_clear_exceptions