json_get_string – JSON-Fortran
json_get_string Subroutine
65 statements
Source File
private subroutine json_get_string(json, me, value)
Get a character string from a json_value.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: me
character(kind=CK, len=:), intent(out), allocatable :: value
Calls
Called by
Source Code
    subroutine json_get_string(json, me, value)
    implicit none
    class(json_core),intent(inout)                   :: json
    type(json_value),pointer,intent(in)              :: me
    character(kind=CK,len=:),allocatable,intent(out) :: value
    value = CK_''
    if (.not. json%exception_thrown) then
        if (me%var_type == json_string) then
            if (allocated(me%str_value)) then
                if (json%unescaped_strings) then
                    ! default: it is stored already unescaped:
                    value = me%str_value
                else
                    ! return the escaped version:
                    call escape_string(me%str_value, value, json%escape_solidus)
                end if
            else
               call json%throw_exception('Error in json_get_string: '//&
                                         'me%str_value not allocated')
            end if
        else
            if (json%strict_type_checking) then
                if (allocated(me%name)) then
                    call json%throw_exception('Error in json_get_string:'//&
                                              ' Unable to resolve value to string: '//me%name)
                else
                    call json%throw_exception('Error in json_get_string:'//&
                                              ' Unable to resolve value to string')
                end if
            else
                select case (me%var_type)
                case (json_integer)
                    if (allocated(me%int_value)) then
                        value = repeat(space, max_integer_str_len)
                        call integer_to_string(me%int_value,int_fmt,value)
                        value = trim(value)
                    else
                        call json%throw_exception('Error in json_get_string: '//&
                                                  'me%int_value not allocated')
                    end if
                case (json_real)
                    if (allocated(me%dbl_value)) then
                        value = repeat(space, max_numeric_str_len)
                        call real_to_string(me%dbl_value,json%real_fmt,&
                                            json%non_normals_to_null,&
                                            json%compact_real,value)
                        value = trim(value)
                    else
                        call json%throw_exception('Error in json_get_string: '//&
                                                  'me%int_value not allocated')
                    end if
                case (json_logical)
                    if (allocated(me%log_value)) then
                        if (me%log_value) then
                            value = true_str
                        else
                            value = false_str
                        end if
                    else
                        call json%throw_exception('Error in json_get_string: '//&
                                                  'me%log_value not allocated')
                    end if
                case (json_null)
                    value = null_str
                case default
                    if (allocated(me%name)) then
                        call json%throw_exception('Error in json_get_string: '//&
                                                  'Unable to resolve value to characters: '//&
                                                  me%name)
                    else
                        call json%throw_exception('Error in json_get_string: '//&
                                                  'Unable to resolve value to characters')
                    end if
                end select
            end if
        end if
    end if
    end subroutine json_get_string
Call graph
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
escape_string calls valid_json_hex
real_to_string calls compact_real_string
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_string_info calls get, info
json_update_integer calls get, info, add_by_path
json_update_logical calls get, info, add_by_path
json_update_real calls get, info, add_by_path
json_update_string calls get, info, add_by_path
json_valid_path calls get
json_value_remove_if_present calls get
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
convert calls info
json_add_integer_by_path calls info, create
json_add_integer_vec_by_path calls info, add, create
json_add_logical_by_path calls info, create
json_add_logical_vec_by_path calls info, add, create
json_add_member_by_path calls info, create
json_add_real_by_path calls info, create
json_add_real_vec_by_path calls info, add, create
json_add_string_by_path calls info, create
json_add_string_vec_by_path calls info, add, create
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_add_member calls info
json_value_reverse calls info
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_get_by_path_jsonpath_bracket calls convert, add
json_value_print calls json_is_vector, json_value_print
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_check_children_for_duplicate_keys calls get_path
json_create_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_get_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_get_by_path_default calls add
json_print_to_unit calls json_value_print
json_value_add_integer calls add
json_value_add_integer_vec calls add
json_value_add_logical calls add
json_value_add_logical_vec calls add
json_value_add_null calls add
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add
json_value_add_string calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
json_value_to_string calls json_value_print
parse_array calls add, parse_value
parse_object calls add, parse_object, parse_value
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
assign_json_file_to_string calls json_value_to_string
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_file_print_to_string calls json_value_to_string
parse_value calls parse_array, parse_object
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_parse_file calls parse_value
json_parse_string calls parse_value
wrap_json_create_by_path calls create
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2