json_failed – JSON-Fortran
json_failed Function
Jacob Williams
12/5/2013
6 statements
Source File
private pure function json_failed(json) result(failed)
Logical function to indicate if an exception has been thrown in a json_core.
Example
    type(json_core) :: json
    type(json_value),pointer :: p
    logical :: status_ok
    character(len=:),allocatable :: error_msg
    call json%load(filename='myfile.json',p)
    if (json%failed()) then
        call json%check_for_errors(status_ok, error_msg)
        write(*,*) 'Error: '//error_msg
        call json%clear_exceptions()
        call json%destroy(p)
    end if
Note that json_file contains a wrapper for this routine, which is used like:
    type(json_file) :: f
    logical :: status_ok
    character(len=:),allocatable :: error_msg
    call f%load(filename='myfile.json')
    if (f%failed()) then
        call f%check_for_errors(status_ok, error_msg)
        write(*,*) 'Error: '//error_msg
        call f%clear_exceptions()
        call f%destroy()
    end if
See also
json_check_for_errors
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(in) :: json
Return Value logical(kind=LK)
will be true if an exception has been thrown.
Called by
Source Code
    pure function json_failed(json) result(failed)
    implicit none
    class(json_core),intent(in) :: json
    logical(LK)                 :: failed  !! will be true if an exception
                                           !! has been thrown.
    failed = json%exception_thrown
    end function json_failed
Call graph
assign_json_file_to_string calls json_failed, json_value_to_string
assign_string_to_json_file calls json_failed
json_file_failed calls json_failed
json_file_update_integer calls json_failed
json_file_update_logical calls json_failed
json_file_update_real calls json_failed
json_file_update_string calls json_failed
json_value_print calls json_failed, json_value_print
json_value_validate calls json_failed
json_file_move_pointer calls json_file_failed
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
wrap_assign_string_to_json_file calls assign_string_to_json_file
json_file_print_to_string calls json_value_to_string
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update