json_clear_exceptions – JSON-Fortran
json_clear_exceptions Subroutine
Jacob Williams
12/4/2013
6 statements
Source File
private pure subroutine json_clear_exceptions(json)
Clear exceptions in the json_core.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
Called by
Source Code
    pure subroutine json_clear_exceptions(json)
    implicit none
    class(json_core),intent(inout)  :: json
    !clear the flag and message:
    json%exception_thrown = .false.
    if (allocated(json%err_message)) deallocate(json%err_message)
    end subroutine json_clear_exceptions
Call graph
assign_string_to_json_file calls json_clear_exceptions, deserialize
json_add_integer_by_path calls json_clear_exceptions, create, info, json_value_replace
json_add_logical_by_path calls json_clear_exceptions, create, info, json_value_replace
json_add_member_by_path calls json_clear_exceptions, create, info, json_value_replace
json_add_real_by_path calls json_clear_exceptions, create, info, json_value_replace
json_add_string_by_path calls json_clear_exceptions, create, info, json_value_replace
json_add_string_vec_by_path calls json_clear_exceptions, create, info, json_value_replace, add
json_create_by_path calls json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_file_clear_exceptions calls json_clear_exceptions
json_get_alloc_string_vec_by_path calls json_clear_exceptions, get
json_get_array_by_path calls json_clear_exceptions, get
json_get_by_path calls json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_by_path_default calls json_clear_exceptions, get_child, add
json_get_by_path_jsonpath_bracket calls json_clear_exceptions, get_child, convert, add
json_get_by_path_rfc6901 calls json_clear_exceptions, get_child
json_get_integer_by_path calls json_clear_exceptions, get
json_get_integer_vec_by_path calls json_clear_exceptions, get
json_get_logical_by_path calls json_clear_exceptions, get
json_get_logical_vec_by_path calls json_clear_exceptions, get
json_get_path calls json_clear_exceptions, info
json_get_real_by_path calls json_clear_exceptions, get
json_get_real_vec_by_path calls json_clear_exceptions, get
json_get_string_by_path calls json_clear_exceptions, get
json_get_string_vec_by_path calls json_clear_exceptions, get
json_initialize calls json_clear_exceptions
json_matrix_info_by_path calls json_clear_exceptions, get, matrix_info
json_print_error_message calls json_clear_exceptions
json_rename_by_path calls json_clear_exceptions, get
json_string_info calls json_clear_exceptions, get, info
json_value_get_child_by_index calls json_clear_exceptions
json_value_get_child_by_name calls json_clear_exceptions
json_value_validate calls json_clear_exceptions
parse_number calls json_clear_exceptions
initialize_json_core calls json_initialize
initialize_json_core_in_file calls json_initialize
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_file_print_error_message calls json_print_error_message
json_parse_file calls json_initialize, parse_value
json_parse_string calls json_initialize, parse_value
parse_value calls parse_number, parse_array, parse_object
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_core calls initialize_json_core
json_add_integer_vec_by_path calls create, info, json_value_replace, add
json_add_logical_vec_by_path calls create, info, json_value_replace, add
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_real_vec_by_path calls create, info, json_value_replace, add
json_check_children_for_duplicate_keys calls get_child, get_path
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_file_variable_matrix_info calls matrix_info
json_get_alloc_string_vec calls get, string_info
json_get_integer_vec calls get
json_get_logical_vec calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_vec calls get
json_get_string_vec calls get
json_info_by_path calls get, info
json_matrix_info calls get_child, info
json_update_integer calls add_by_path, get, info
json_update_logical calls add_by_path, get, info
json_update_real calls add_by_path, get, info
json_update_string calls add_by_path, get, info
json_valid_path calls get
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_remove_if_present calls get
parse_array calls parse_value, add
parse_object calls parse_value, parse_object, add
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_create_by_path calls create
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_path calls get_path
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_value_get_child_by_name calls get
initialize_json_file calls initialize
initialize_json_file_from_string calls initialize, deserialize
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_file_load calls load
json_file_load_from_string calls deserialize
json_file_move_pointer calls initialize
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
wrap_json_parse_string calls deserialize
json_file calls initialize_json_file, initialize_json_file_from_string, initialize_json_file_from_string_v2
convert calls info, json_value_replace
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_is_vector calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_add_member calls info
json_value_replace calls insert_after
json_value_reverse calls info
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_info_by_path calls info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
initialize_json_file_from_string_v2 calls deserialize
json_value_print calls json_is_vector, json_value_print
wrap_json_file_load_from_string calls deserialize
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_print_to_unit calls json_value_print
json_value_add_integer calls add
json_value_add_integer_vec calls add
json_value_add_logical calls add
json_value_add_logical_vec calls add
json_value_add_null calls add
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add
json_value_add_string calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
json_value_to_string calls json_value_print
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string