json_update_string – JSON-Fortran
json_update_string Subroutine
Jacob Williams
12/6/2014
25 statements
Source File
private subroutine json_update_string(json, p, path, val, found, trim_str, adjustl_str)
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
Note
If the variable is not a scalar, an exception will be thrown.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
character(kind=CK, len=*), intent(in) :: path
path to the variable in the structure
character(kind=CK, len=*), intent(in) :: val
the new value
logical(kind=LK), intent(out) :: found
if the variable was found and was a scalar.
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for the val (only used if val is present)
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for the val (only used if val is present) (note that ADJUSTL is done before TRIM)
Calls
Called by
Source Code
    subroutine json_update_string(json,p,path,val,found,trim_str,adjustl_str)
    implicit none
    class(json_core),intent(inout)      :: json
    type(json_value),pointer            :: p
    character(kind=CK,len=*),intent(in) :: path  !! path to the variable in the structure
    character(kind=CK,len=*),intent(in) :: val   !! the new value
    logical(LK),intent(out)             :: found !! if the variable was found and was a scalar.
    logical(LK),intent(in),optional     :: trim_str    !! if TRIM() should be called for the `val`
                                                       !! (only used if `val` is present)
    logical(LK),intent(in),optional     :: adjustl_str !! if ADJUSTL() should be called for the `val`
                                                       !! (only used if `val` is present)
                                                       !! (note that ADJUSTL is done before TRIM)
    type(json_value),pointer :: p_var
    integer(IK) :: var_type
    call json%get(p,path,p_var,found)
    if (found) then
        call json%info(p_var,var_type)
        select case (var_type)
        case (json_null,json_logical,json_integer,json_real,json_string)
            call json%to_string(p_var,val,trim_str=trim_str,adjustl_str=adjustl_str) ! update the value
        case default
            found = .false.
            call json%throw_exception('Error in json_update_string: '//&
                                      'the variable is not a scalar value',found)
        end select
    else
        call json%add_by_path(p,path,val)   !add the new element
    end if
    end subroutine json_update_string
Call graph
json_update_string calls add_by_path, get, info, throw_exception, to_string
to_string calls destroy_json_data
json_add_integer_by_path calls info, throw_exception, create, create_integer, json_clear_exceptions, json_value_replace
json_add_integer_vec_by_path calls info, add, create, create_array, json_value_replace
json_add_logical_by_path calls info, throw_exception, create, create_logical, json_clear_exceptions, json_value_replace
json_add_logical_vec_by_path calls info, add, create, create_array, json_value_replace
json_add_member_by_path calls info, throw_exception, create, json_clear_exceptions, json_value_replace
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_real_by_path calls info, throw_exception, create, create_real, json_clear_exceptions, json_value_replace
json_add_real_vec_by_path calls info, add, create, create_array, json_value_replace
json_add_string_by_path calls info, throw_exception, create, create_string, json_clear_exceptions, json_value_replace
json_add_string_vec_by_path calls info, throw_exception, add, create, create_array, json_clear_exceptions, json_value_replace
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls get, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_info calls throw_exception
json_info_by_path calls get, info
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, add, json_clear_exceptions, string_to_integer, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, add, json_clear_exceptions, string_to_integer, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
json_value_replace calls insert_after, json_value_remove
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, json_value_replace, create_null, create_object
decode_rfc6901 calls replace_string
json_create_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_string_info calls get, info, throw_exception, json_clear_exceptions
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls info, throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_real32 calls create_real
json_value_create_string calls to_string, json_value_create
json_value_remove calls destroy
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_insert_after_child_by_index calls get_child, insert_after
to_integer calls destroy_json_data
to_logical calls destroy_json_data
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_destroy calls destroy_json_data, destroy
name_equal calls name_strings_equal
name_strings_equal calls lowercase_string
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update