wrap_initialize_json_file_from_string – JSON-Fortran
wrap_initialize_json_file_from_string Function
28 statements
Source File
private function wrap_initialize_json_file_from_string(str, verbose, compact_reals, print_signs, real_format, spaces_per_tab, strict_type_checking, trailing_spaces_significant, case_sensitive_keys, no_whitespace, unescape_strings, comment_char, path_mode, path_separator, compress_vectors, allow_duplicate_keys, escape_solidus, stop_on_error, null_to_real_mode, non_normal_mode, use_quiet_nan, strict_integer_type_checking, allow_trailing_comma) result(file_object)
Alternate version of initialize_json_file_from_string, where “str” is kind=CDK.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: str
string to load JSON data from
logical(kind=LK), intent(in), optional :: verbose
mainly useful for debugging (default is false)
logical(kind=LK), intent(in), optional :: compact_reals
to compact the real number strings for output (default is true)
logical(kind=LK), intent(in), optional :: print_signs
always print numeric sign (default is false)
character(kind=CDK, len=*), intent(in), optional :: real_format
Real number format: ‘E’ [default], ‘*’, ‘G’, ‘EN’, or ‘ES’
integer(kind=IK), intent(in), optional :: spaces_per_tab
number of spaces per tab for indenting (default is 2)
logical(kind=LK), intent(in), optional :: strict_type_checking
if true, no integer, double, or logical type conversions are done for the get routines (default is false).
logical(kind=LK), intent(in), optional :: trailing_spaces_significant
for name and path comparisons, is trailing space to be considered significant. (default is false)
logical(kind=LK), intent(in), optional :: case_sensitive_keys
for name and path comparisons, are they case sensitive. (default is true)
logical(kind=LK), intent(in), optional :: no_whitespace
if true, printing the JSON structure is done without adding any non-significant spaces or linebreaks (default is false)
logical(kind=LK), intent(in), optional :: unescape_strings
If false, then the raw escaped string is returned from json_get_string and similar routines. If true [default], then the string is returned unescaped.
character(kind=CK, len=*), intent(in), optional :: comment_char
If present, these characters are used to denote comments in the JSON file, which will be ignored if present. Example: !, #, or /!#. Setting this to a blank string disables the ignoring of comments. (Default is /!#).
integer(kind=IK), intent(in), optional :: path_mode
How the path strings are interpreted in the get_by_path routines:
1 : Default mode (see json_get_by_path_default)
2 : as RFC 6901 “JSON Pointer” paths (see json_get_by_path_rfc6901)
3 : JSONPath “bracket-notation” see json_get_by_path_jsonpath_bracket)
character(kind=CK, len=1), intent(in), optional :: path_separator
The path separator to use in the “default” mode for the paths in the various get_by_path routines. Example: . [default] or %. Note: if path_mode/=1 then this is ignored.
logical(kind=LK), intent(in), optional :: compress_vectors
If true, then arrays of integers, nulls, doubles, and logicals are printed all on one line. [Note: no_whitespace will override this option if necessary]. (Default is False).
logical(kind=LK), intent(in), optional :: allow_duplicate_keys
If True [default] then no special checks are done to check for duplicate keys.
If False, then after parsing, if any duplicate keys are found, an error is thrown. A call to json_value_validate will also check for duplicates.
logical(kind=LK), intent(in), optional :: escape_solidus
If True then the solidus “/” is always escaped “\/” when serializing JSON
If False [default], then it is not escaped.
Note that this option does not affect parsing (both escaped and unescaped are still valid in all cases).
logical(kind=LK), intent(in), optional :: stop_on_error
If an exception is raised, then immediately quit. (Default is False).
integer(kind=IK), intent(in), optional :: null_to_real_mode
if strict_type_checking=false:
1 : an exception will be raised if try to retrieve a null as a real.
2 : a null retrieved as a real will return a NaN. [default]
3 : a null retrieved as a real will return 0.0.
integer(kind=IK), intent(in), optional :: non_normal_mode
How to serialize NaN, Infinity, and -Infinity real values:
1 : as strings (e.g., “NaN”, “Infinity”, “-Infinity”) [default]
2 : as JSON null values
logical(kind=LK), intent(in), optional :: use_quiet_nan
If true [default], null_to_real_mode=2 and string_to_real will use ieee_quiet_nan for NaN values.
If false, ieee_signaling_nan will be used.
logical(kind=LK), intent(in), optional :: strict_integer_type_checking
If false, when parsing JSON, if an integer numeric value cannot be converted to an integer (integer(IK)), then an attempt is then make to convert it to a real (real(RK)).
If true, an exception will be raised if the integer value cannot be read.
(default is true)
logical(kind=LK), intent(in), optional :: allow_trailing_comma
Allow a single trailing comma in arrays and objects. (default is true)
Return Value type(json_file)
Calls
Source Code
    function wrap_initialize_json_file_from_string(str,&
#include "json_initialize_dummy_arguments.inc"
                                                  ) result(file_object)
    implicit none
    type(json_file) :: file_object
    character(kind=CDK,len=*),intent(in) :: str  !! string to load JSON data from
#include "json_initialize_arguments.inc"
    file_object = initialize_json_file_from_string(&
                                  to_unicode(str),&
#include "json_initialize_dummy_arguments.inc"
                                                )
    end function wrap_initialize_json_file_from_string
Call graph
wrap_initialize_json_file_from_string calls to_unicode, initialize_json_file_from_string
to_unicode calls to_uni, to_uni_vec
initialize_json_file_from_string calls deserialize, initialize
initialize_json_core_in_file calls json_initialize
json_file_load_from_string calls deserialize, json_file_destroy
json_file_destroy calls destroy
json_initialize calls throw_exception, integer_to_string, json_clear_exceptions
json_parse_string calls json_initialize, throw_exception, annotate_invalid_json, json_check_all_for_duplicate_keys, json_parse_end, json_prepare_parser, json_value_create, parse_value
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
json_check_all_for_duplicate_keys calls json_traverse
json_parse_end calls throw_exception, pop_char
json_value_destroy calls destroy, destroy_json_data
parse_value calls throw_exception, parse_array, parse_for_chars, parse_number, parse_object, parse_string, pop_char, push_char, to_array, to_logical, to_null, to_object, to_string
json_traverse calls throw_exception
parse_array calls destroy, throw_exception, json_value_create, parse_value, pop_char, add
parse_for_chars calls throw_exception, pop_char
parse_number calls json_clear_exceptions, pop_char, push_char, string_to_dble, string_to_int, to_integer, to_real
parse_object calls destroy, throw_exception, json_value_create, parse_value, parse_object, parse_string, pop_char, add
parse_string calls throw_exception, pop_char, unescape_string
push_char calls throw_exception, integer_to_string
to_array calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_string calls destroy_json_data
string_to_dble calls throw_exception, string_to_real
string_to_int calls throw_exception, string_to_integer
to_integer calls destroy_json_data
to_real calls destroy_json_data
unescape_string calls valid_json_hex
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception, info
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_info calls throw_exception
json_info_by_path calls info, get
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_clear_exceptions, json_value_create, to_array, to_null, to_object, add, string_to_integer, get_child
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, json_value_create, to_null, add, string_to_integer, get_child, convert
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, create_array, create_null, info, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, json_clear_exceptions, info, get
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string