jf_test_9 – JSON-Fortran
jf_test_9 Program
Source File
Uses:
jf_test_9_mod
Ninth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_9
    !! Ninth unit test.
    use jf_test_9_mod , only: test_9
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_9(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_9
Call graph
jf_test_9 calls test_9
test_9 calls json_initialize, read_file, json_failed, json_print_error_message
json_initialize calls json_clear_exceptions, throw_exception
json_print_error_message calls json_clear_exceptions, json_check_for_errors
throw_exception calls json_throw_exception