jf_test_1 – JSON-Fortran
jf_test_1 Program
Source File
Uses:
jf_test_1_mod
First unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_1
    !! First unit test.
    use jf_test_1_mod , only: test_1
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_1(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_1
Call graph
jf_test_1 calls test_1
test_1 calls json_remove, json_initialize, json_update, json_failed, json_print_error_message
json_remove calls json_value_remove
json_initialize calls json_clear_exceptions, throw_exception
json_update calls json_update_logical, json_update_string, json_update_integer, json_update_double
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_value_remove calls json_value_destroy
json_value_destroy calls json_value_destroy, destroy_json_data
throw_exception calls json_throw_exception
json_update_logical calls throw_exception, json_get, json_add, to_logical, json_info
json_update_string calls throw_exception, json_get, json_add, json_info, to_string
json_update_integer calls throw_exception, json_get, json_add, json_info, to_integer
json_update_double calls throw_exception, json_get, json_add, json_info, to_double
json_get calls json_get_string, json_get_double_vec_with_path, json_get_logical, json_get_integer_vec_with_path, json_get_logical_vec_with_path, json_get_array, json_get_double, json_get_string_vec_with_path, json_get_by_path, json_get_integer, json_get_double_with_path, json_get_logical_with_path, json_get_integer_with_path, json_get_logical_vec, json_get_string_with_path, json_get_string_vec, json_get_integer_vec, json_get_array_with_path, json_get_double_vec
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
to_logical calls destroy_json_data
json_info calls json_count
json_get_string calls throw_exception, unescape_string
json_get_double_vec_with_path calls json_get
json_get_logical calls throw_exception
json_get_integer_vec_with_path calls json_get
json_get_logical_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
json_get_double calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
json_get_integer calls throw_exception
json_get_double_with_path calls json_clear_exceptions, throw_exception, json_get_double, json_get_by_path
json_get_logical_with_path calls json_clear_exceptions, throw_exception, json_get_logical, json_get_by_path
json_get_integer_with_path calls json_clear_exceptions, throw_exception, json_get_by_path, json_get_integer
json_get_logical_vec calls json_get
json_get_string_with_path calls json_clear_exceptions, throw_exception, json_get_string, json_get_by_path
json_get_string_vec calls json_get
json_get_integer_vec calls json_get
json_get_array_with_path calls json_clear_exceptions, throw_exception, json_get_array, json_get_by_path
json_get_double_vec calls json_get
unescape_string calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
json_value_add_logical calls json_add, to_logical, json_value_create
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_double calls destroy_json_data
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data