jf_test_2 – JSON-Fortran
jf_test_2 Program
Source File
Uses:
jf_test_2_mod
Second unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_2
    !! Second unit test.
    use jf_test_2_mod , only: test_2
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_2(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_2
Call graph
jf_test_2 calls test_2
test_2 calls json_print, json_failed, json_create_array, json_get_next, json_get_parent, json_destroy, add_variables_to_input, json_print_error_message, json_update, json_initialize, json_get_tail, json_clone, json_add, json_info, json_create_object, json_get, json_get_previous
json_print calls json_print_1, json_print_2
json_create_array calls json_value_create_array
json_destroy calls json_value_destroy
add_variables_to_input calls json_failed, json_print_error_message, json_add, json_create_object
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_update calls json_update_logical, json_update_string, json_update_integer, json_update_double
json_initialize calls throw_exception, json_clear_exceptions
json_clone calls json_value_clone_func
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
json_info calls json_count
json_create_object calls json_value_create_object
json_get calls json_get_string, json_get_double_vec_with_path, json_get_logical, json_get_integer_vec_with_path, json_get_logical_vec_with_path, json_get_array, json_get_double, json_get_string_vec_with_path, json_get_by_path, json_get_integer, json_get_double_with_path, json_get_logical_with_path, json_get_integer_with_path, json_get_logical_vec, json_get_string_with_path, json_get_string_vec, json_get_integer_vec, json_get_array_with_path, json_get_double_vec
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
json_value_create_array calls json_value_create, to_array
to_array calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
json_update_logical calls json_add, json_info, json_get, throw_exception, to_logical
json_update_string calls json_add, json_info, json_get, throw_exception, to_string
json_update_integer calls json_add, json_info, json_get, throw_exception, to_integer
json_update_double calls json_add, json_info, json_get, throw_exception, to_double
to_logical calls destroy_json_data
to_string calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
json_value_clone_func calls json_value_clone_func
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_get_string calls throw_exception, unescape_string
json_get_double_vec_with_path calls json_get
json_get_logical calls throw_exception
json_get_integer_vec_with_path calls json_get
json_get_logical_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
json_get_double calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_by_path calls throw_exception, json_clear_exceptions, json_get_child, string_to_integer
json_get_integer calls throw_exception
json_get_double_with_path calls throw_exception, json_clear_exceptions, json_get_double, json_get_by_path
json_get_logical_with_path calls throw_exception, json_clear_exceptions, json_get_logical, json_get_by_path
json_get_integer_with_path calls throw_exception, json_clear_exceptions, json_get_by_path, json_get_integer
json_get_logical_vec calls json_get
json_get_string_with_path calls throw_exception, json_clear_exceptions, json_get_string, json_get_by_path
json_get_string_vec calls json_get
json_get_integer_vec calls json_get
json_get_array_with_path calls throw_exception, json_clear_exceptions, json_get_array, json_get_by_path
json_get_double_vec calls json_get
unescape_string calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count