jf_test_3 – JSON-Fortran
jf_test_3 Program
Source File
Uses:
jf_test_3_mod
Third unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_3
    !! Third unit test.
    use jf_test_3_mod , only: test_3
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_3(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_3
Call graph
jf_test_3 calls test_3
test_3 calls json_initialize, json_failed, json_print_error_message
json_initialize calls json_clear_exceptions, throw_exception
json_print_error_message calls json_clear_exceptions, json_check_for_errors
throw_exception calls json_throw_exception