jf_test_4 – JSON-Fortran
jf_test_4 Program
Source File
Uses:
jf_test_4_mod
Fourth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_4
    !! Fourth unit test.
    use jf_test_4_mod , only: test_4
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_4(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_4
Call graph
jf_test_4 calls test_4
test_4 calls json_print, json_failed, json_print_error_message, json_print_to_string, json_initialize, json_add, json_create_object, json_destroy
json_print calls json_print_1, json_print_2
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_print_to_string calls json_value_to_string
json_initialize calls throw_exception, json_clear_exceptions
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
json_create_object calls json_value_create_object
json_destroy calls json_value_destroy
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
json_value_to_string calls json_value_print
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_double calls json_add, json_value_create, to_double
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_logical calls destroy_json_data
to_double calls destroy_json_data
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy