json_value_create_real – JSON-Fortran
json_value_create_real Subroutine
Jacob Williams
9 statements
Source File
private subroutine json_value_create_real(json, p, val, name)
Allocate a json_value pointer and make it a real(RK) variable. The pointer should not already be allocated.
Example
     type(json_value),pointer :: p
     type(json_core) :: json
     call json%create_real(p,'value',1.0_RK)
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
real(kind=RK), intent(in) :: val
character(kind=CK, len=*), intent(in) :: name
Calls
Source Code
    subroutine json_value_create_real(json,p,val,name)
    implicit none
    class(json_core),intent(inout)      :: json
    type(json_value),pointer            :: p
    real(RK),intent(in)                 :: val
    character(kind=CK,len=*),intent(in) :: name
    call json_value_create(p)
    call json%to_real(p,val,name)
    end subroutine json_value_create_real
Call graph
json_value_create_real calls json_value_create, to_real
to_real calls destroy_json_data