real_to_string – JSON-Fortran
real_to_string Subroutine
Jacob Williams
12/4/2013
32 statements
Source File
public subroutine real_to_string(rval, real_fmt, compact_real, non_normals_to_null, str)
Convert a real value to a string.
Modified
Izaak Beekman : 02/24/2015 : added the compact option.
Jacob Williams : 10/27/2015 : added the star option.
Jacob Williams : 07/07/2019 : added null and ieee options.
Arguments
Type Intent Optional Attributes Name
real(kind=RK), intent(in) :: rval
real value.
character(kind=CDK, len=*), intent(in) :: real_fmt
format for real numbers
logical(kind=LK), intent(in) :: compact_real
compact the string so that it is displayed with fewer characters
logical(kind=LK), intent(in) :: non_normals_to_null
If True, NaN, Infinity, or -Infinity are returned as null. If False, the string value will be returned in quotes (e.g., “NaN”, “Infinity”, or “-Infinity”)
character(kind=CK, len=*), intent(out) :: str
rval converted to a string.
Calls
Called by
Source Code
    subroutine real_to_string(rval,real_fmt,compact_real,non_normals_to_null,str)
    implicit none
    real(RK),intent(in)                  :: rval         !! real value.
    character(kind=CDK,len=*),intent(in) :: real_fmt     !! format for real numbers
    logical(LK),intent(in)               :: compact_real !! compact the string so that it is
                                                         !! displayed with fewer characters
    logical(LK),intent(in)               :: non_normals_to_null !! If True, NaN, Infinity, or -Infinity are returned as `null`.
                                                                !! If False, the string value will be returned in quotes
                                                                !! (e.g., "NaN", "Infinity", or "-Infinity" )
    character(kind=CK,len=*),intent(out) :: str          !! `rval` converted to a string.
    integer(IK) :: istat !! write `iostat` flag
    if (ieee_is_finite(rval) .and. .not. ieee_is_nan(rval)) then
        ! normal real numbers
        if (real_fmt==star) then
            write(str,fmt=*,iostat=istat) rval
        else
            write(str,fmt=real_fmt,iostat=istat) rval
        end if
        if (istat==0) then
            !in this case, the default string will be compacted,
            ! so that the same value is displayed with fewer characters.
            if (compact_real) call compact_real_string(str)
        else
            str = repeat(star,len(str)) ! error
        end if
    else
        ! special cases for NaN, Infinity, and -Infinity
        if (non_normals_to_null) then
            ! return it as a JSON null value
            str = null_str
        else
            ! Let the compiler do the real to string conversion
            ! like before, but put the result in quotes so it
            ! gets printed as a string
            write(str,fmt=*,iostat=istat) rval
            if (istat==0) then
                str = quotation_mark//trim(adjustl(str))//quotation_mark
            else
                str = repeat(star,len(str)) ! error
            end if
        end if
    end if
    end subroutine real_to_string
Call graph
real_to_string calls compact_real_string
json_get_string calls real_to_string
json_value_print calls real_to_string, json_value_print, json_is_vector
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
assign_json_file_to_string calls json_value_to_string
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_file_print_to_string calls json_value_to_string
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_string_info calls get, info
json_update_integer calls get, info, add_by_path
json_update_logical calls get, info, add_by_path
json_update_real calls get, info, add_by_path
json_update_string calls get, info, add_by_path
json_valid_path calls get
json_value_remove_if_present calls get
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
convert calls info
json_add_integer_by_path calls info, create
json_add_integer_vec_by_path calls info, add, create
json_add_logical_by_path calls info, create
json_add_logical_vec_by_path calls info, add, create
json_add_member_by_path calls info, create
json_add_real_by_path calls info, create
json_add_real_vec_by_path calls info, add, create
json_add_string_by_path calls info, create
json_add_string_vec_by_path calls info, add, create
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_add_member calls info
json_value_reverse calls info
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_get_by_path_jsonpath_bracket calls convert, add
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_check_children_for_duplicate_keys calls get_path
json_create_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_get_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_get_by_path_default calls add
json_value_add_integer calls add
json_value_add_integer_vec calls add
json_value_add_logical calls add
json_value_add_logical_vec calls add
json_value_add_null calls add
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add
json_value_add_string calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
parse_array calls add, parse_value
parse_object calls add, parse_object, parse_value
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
parse_value calls parse_array, parse_object
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_parse_file calls parse_value
json_parse_string calls parse_value
wrap_json_create_by_path calls create
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2