ucs4_neq_default – JSON-Fortran
ucs4_neq_default Function
Jacob Williams
7 statements
Source File
private pure elemental function ucs4_neq_default(ucs4_str, def_str) result(res)
CK/=CDK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: ucs4_str
character(kind=CDK, len=*), intent(in) :: def_str
Return Value logical(kind=LK)
Calls
Source Code
    pure elemental function ucs4_neq_default(ucs4_str,def_str) result(res)
    implicit none
    character(kind=CK, len=*), intent(in) :: ucs4_str
    character(kind=CDK,len=*), intent(in) :: def_str
    logical(LK) :: res
    res = ( ucs4_str /= to_unicode(def_str) )
    end function ucs4_neq_default
Call graph
ucs4_neq_default calls to_unicode
to_unicode calls to_uni, to_uni_vec