wrap_json_file_valid_path_op – JSON-Fortran
wrap_json_file_valid_path_op Function
Jacob Williams
7 statements
Source File
private function wrap_json_file_valid_path_op(path, me) result(found)
Alternate version of json_file_valid_path_op, where “path” is kind=CDK.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: path
the path to the variable
class(json_file), intent(in) :: me
the JSON file
Return Value logical(kind=LK)
if the variable was found
Calls
Source Code
    function wrap_json_file_valid_path_op(path,me) result(found)
    implicit none
    character(kind=CDK,len=*),intent(in) :: path   !! the path to the variable
    class(json_file),intent(in)          :: me     !! the JSON file
    logical(LK)                          :: found  !! if the variable was found
    found = to_unicode(path) .in. me
    end function wrap_json_file_valid_path_op
Call graph
wrap_json_file_valid_path_op calls to_unicode
to_unicode calls to_uni, to_uni_vec