comment:
  layout: header, changes, diff, sunburst
coverage:
  fixes:
  - doc/src::src
  ignore:
  - src/tests
  - doc
  status:
    patch:
      default:
        target: 20%
    project:
      default:
        target: 80%
