json_create_object – JSON-Fortran
json_create_object Interface
Source File
public interface json_create_object
Allocate a json_value pointer and make it an object variable. The pointer should not already be allocated.
Example
     type(json_value),pointer :: p
     call json_create(p,'objectname')
Note
The name is not significant for the root structure or an array element. In those cases, an empty string can be used.
Calls
Called By
Module Procedures
private subroutine json_value_create_object(me, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
Description
Author
Jacob Williams
Allocate a json_value pointer and make it an object variable. The pointer should not already be allocated.
Call graph
json_create_object calls json_value_create_object
json_value_create_object calls json_value_create, to_object
to_object calls destroy_json_data
test_7 calls json_create_object
test_2 calls json_create_object, add_variables_to_input
test_12 calls json_create_object
add_variables_to_input calls json_create_object
test_4 calls json_create_object
test_10 calls json_create_object
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_4 calls test_4
jf_test_10 calls test_10