json_print_to_string – JSON-Fortran
json_print_to_string Interface
Source File
public interface json_print_to_string
Print the json_value structure to an allocatable string.
Calls
Called By
Module Procedures
private subroutine json_value_to_string(me, str)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=:), intent(out), allocatable :: str
prints structure to this string
Description
Author
Jacob Williams
Date
2/12/2014
Print the json_value structure to an allocatable string.
Call graph
json_print_to_string calls json_value_to_string
json_value_to_string calls json_value_print
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
test_4 calls json_print_to_string
jf_test_4 calls test_4