json_print – JSON-Fortran
json_print Interface
Source File
public interface json_print
Print the json_value to a file.
Example
    type(json_value) :: p
    !...
    call json_print(p,'test.json')  !this is json_print_2
Calls
Called By
Module Procedures
private subroutine json_print_1(me, iunit)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
integer(kind=IK), intent(in) :: iunit
the file unit (the file must already have been opened, can't be -1).
Description
Author
Jacob Williams
Date
6/20/2014
Print the json_value structure to a file.
private subroutine json_print_2(me, filename)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: filename
the filename to print to (should not already be open)
Description
Author
Jacob Williams
Date
12/23/2014
Print the json_value structure to a file.
Call graph
json_print calls json_print_1, json_print_2
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
test_7 calls json_print
test_2 calls json_print
test_12 calls json_print
test_8 calls json_print
test_4 calls json_print
test_14 calls json_print
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_8 calls test_8
jf_test_4 calls test_4
jf_test_14 calls test_14