json_destroy – JSON-Fortran
json_destroy Interface
Source File
public interface json_destroy
Destructor routine for a json_value pointer. This must be called explicitly if it is no longer needed, before it goes out of scope. Otherwise, a memory leak will result.
Example
Destroy the json_value pointer before the variable goes out of scope:
     subroutine example1()
     type(json_value),pointer :: p
     call json_create_object(p,'')
     call json_add(p,'year',2015)
     call json_print(p)
     call json_destroy(p)
     end subroutine example1
Note: it should NOT be called for a json_value pointer than has already been added to another json_value structure, since doing so may render the other structure invalid. Consider the following example:
     subroutine example2(p)
     type(json_value),pointer,intent(out) :: p
     type(json_value),pointer :: q
     call json_create_object(p,'')
     call json_add(p,'year',2015)
     call json_create_object(q,'q')
     call json_add(q,'val',1)
     call json_add(p, q)  !add q to p structure
     ! do NOT call json_destroy(q) here, because q is
     ! now part of the output structure p.  p should be destroyed
     ! somewhere upstream by the caller of this routine.
     nullify(q) !OK, but not strictly necessary
     end subroutine example2
Calls
Called By
Module Procedures
private recursivesubroutine json_value_destroy(me, destroy_next)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
logical(kind=LK), intent(in), optional :: destroy_next
if true, then me%next is also destroyed (default is true)
Description
Author
Jacob Williams
Date
1/22/2014
Destroy a json_value linked-list structure.
Call graph
json_destroy calls json_value_destroy
json_value_destroy calls json_value_destroy, destroy_json_data
test_7 calls json_destroy
test_2 calls json_destroy
parse_array calls json_destroy, parse_value
test_8 calls json_destroy, json_parse
test_10 calls json_destroy
test_14 calls json_destroy, json_parse
parse_object calls json_destroy, parse_object, parse_value
test_4 calls json_destroy
jf_test_7 calls test_7
jf_test_2 calls test_2
parse_value calls parse_array, parse_object
json_parse_string calls parse_value
json_parse_file calls parse_value
wrap_json_parse_string calls json_parse_string
json_parse calls json_parse_string, json_parse_file
json_file_load calls json_parse
json_file_load_from_string calls json_parse
wrap_json_file_load_from_string calls json_file_load_from_string
jf_test_8 calls test_8
jf_test_10 calls test_10
jf_test_14 calls test_14
jf_test_4 calls test_4