json_add_string_vec_by_path – JSON-Fortran
json_add_string_vec_by_path Subroutine
58 statements
Source File
private subroutine json_add_string_vec_by_path(json, me, path, value, found, was_created, ilen, trim_str, adjustl_str)
Wrapper to json_add_string_by_path for adding a string vector by path.
Note
The ilen input can be used to specify the actual lengths of the the strings in the array. They must all be <= len(value).
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: me
the JSON structure
character(kind=CK, len=*), intent(in) :: path
the path to the variable
character(kind=CK, len=*), intent(in), dimension(:) :: value
the vector to add
logical(kind=LK), intent(out), optional :: found
if the variable was found
logical(kind=LK), intent(out), optional :: was_created
if the variable had to be created
integer(kind=IK), intent(in), optional, dimension(:) :: ilen
the string lengths of each element in value. If not present, the full len(value) string is added for each element.
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for each element
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for each element
Calls
Called by
Source Code
    subroutine json_add_string_vec_by_path(json,me,path,value,found,was_created,ilen,trim_str,adjustl_str)
    implicit none
    class(json_core),intent(inout)      :: json
    type(json_value),pointer            :: me           !! the JSON structure
    character(kind=CK,len=*),intent(in) :: path         !! the path to the variable
    character(kind=CK,len=*),dimension(:),intent(in) :: value !! the vector to add
    logical(LK),intent(out),optional    :: found        !! if the variable was found
    logical(LK),intent(out),optional    :: was_created  !! if the variable had to be created
    integer(IK),dimension(:),intent(in),optional :: ilen !! the string lengths of each
                                                         !! element in `value`. If not present,
                                                         !! the full `len(value)` string is added
                                                         !! for each element.
    logical(LK),intent(in),optional     :: trim_str      !! if TRIM() should be called for each element
    logical(LK),intent(in),optional     :: adjustl_str   !! if ADJUSTL() should be called for each element
    type(json_value),pointer :: p   !! pointer to path (which may exist)
    type(json_value),pointer :: var !! new variable that is created
    integer(IK) :: i    !! counter
    character(kind=CK,len=:),allocatable :: name !! the variable name
    logical(LK) :: p_found  !! if the path was successfully found (or created)
    if ( .not. json%exception_thrown ) then
        ! validate ilen array if present:
        if (present(ilen)) then
            if (size(ilen)/=size(value)) then
                call json%throw_exception('Error in json_add_string_vec_by_path: '//&
                                          'Invalid size of ilen input vector.',found)
                if (present(found)) then
                    found = .false.
                    call json%clear_exceptions()
                end if
                if (present(was_created)) was_created = .false.
                return
            else
                ! also have to validate the specified lengths.
                ! (must not be greater than input string length)
                do i = 1, size(value)
                    if (ilen(i)>len(value)) then
                        call json%throw_exception('Error in json_add_string_vec_by_path: '//&
                                                  'Invalid ilen element.',found)
                        if (present(found)) then
                            found = .false.
                            call json%clear_exceptions()
                        end if
                        if (present(was_created)) was_created = .false.
                        return
                    end if
                end do
            end if
        end if
        !get a pointer to the variable
        !(creating it if necessary)
        call json%create(me,path,p,found=p_found)
        if (p_found) then
            call json%info(p,name=name)             ! want to keep the existing name
            call json%create_array(var,name)        ! create a new array variable
            call json%replace(p,var,destroy=.true.) ! replace p with this array (destroy p)
            !populate each element of the array:
            do i=1,size(value)
                if (present(ilen)) then
                    call json%add(var, CK_'', value(i)(1:ilen(i)), &
                                  trim_str=trim_str, adjustl_str=adjustl_str)
                else
                    call json%add(var, CK_'', value(i), &
                                  trim_str=trim_str, adjustl_str=adjustl_str)
                end if
            end do
        end if
    else
        if ( present(found) )       found = .false.
        if ( present(was_created) ) was_created = .false.
    end if
    end subroutine json_add_string_vec_by_path
Call graph
json_add_string_vec_by_path calls add, create, create_array, info, throw_exception, json_clear_exceptions, json_value_replace
json_value_replace calls insert_after, json_value_remove
json_create_by_path calls throw_exception, json_clear_exceptions, integer_to_string, json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_info calls throw_exception
json_info_by_path calls info, get
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls info, throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_create_array calls json_value_create, to_array
json_value_remove calls destroy
json_get_by_path_default calls add, throw_exception, json_clear_exceptions, json_value_create, to_array, get_child, string_to_integer, to_null, to_object
json_get_by_path_jsonpath_bracket calls add, throw_exception, json_clear_exceptions, json_value_create, get_child, convert, string_to_integer, to_null
json_value_insert_after_child_by_index calls insert_after, get_child
to_array calls destroy_json_data
convert calls create_array, info, throw_exception, json_value_replace, create_null, create_object
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, json_clear_exceptions, integer_to_string, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_value_destroy calls destroy, destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
escape_string calls valid_json_hex
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, get_child, string_to_integer, decode_rfc6901
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
real_to_string calls compact_real_string
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
decode_rfc6901 calls replace_string
json_string_info calls info, throw_exception, json_clear_exceptions, get
json_value_create_object calls json_value_create, to_object
name_equal calls name_strings_equal
name_strings_equal calls lowercase_string
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_update_integer calls add_by_path
json_update_logical calls add_by_path
json_update_real calls add_by_path
json_update_string calls add_by_path
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update