assign_json_file_to_string – JSON-Fortran
assign_json_file_to_string Subroutine
Jacob Williams
13 statements
Source File
private subroutine assign_json_file_to_string(str, me)
Assignment operator for character = json_core. This is just a wrapper for the json_value_to_string routine.
Note
If an exception is raised or the file contains no data, this will return an empty string.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=:), intent(out), allocatable :: str
class(json_file), intent(in) :: me
Calls
Source Code
    subroutine assign_json_file_to_string(str,me)
    implicit none
    character(kind=CK,len=:),allocatable,intent(out) :: str
    class(json_file),intent(in) :: me
    type(json_core) :: core_copy !! a copy of `core` from `me`
    if (me%core%failed() .or. .not. associated(me%p)) then
        str = CK_''
    else
        ! This is sort of a hack. Since `me` has to have `intent(in)`
        ! for the assignment to work, we need to make a copy of `me%core`
        ! so we can call the low level routine (since it needs it to
        ! be `intent(inout)`) because it's possible for this
        ! function to raise an exception.
        core_copy = me%core ! copy the parser settings
        call core_copy%serialize(me%p,str)
        if (me%core%failed()) str = CK_''
    end if
    end subroutine assign_json_file_to_string
Call graph
assign_json_file_to_string calls json_failed, json_value_to_string
json_value_to_string calls json_value_print
json_value_print calls json_failed, json_value_print, throw_exception, escape_string, integer_to_string, json_is_vector, real_to_string
escape_string calls valid_json_hex
json_is_vector calls throw_exception, info
real_to_string calls compact_real_string
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_info calls throw_exception
json_info_by_path calls info, get
wrap_json_info_by_path calls info, to_unicode
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
convert calls throw_exception, info, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, info, get, json_clear_exceptions
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
wrap_json_value_get_child_by_name calls to_unicode, get
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy