default_comp_ucs4 – JSON-Fortran
default_comp_ucs4 Function
Izaak Beekman
7 statements
Source File
private pure elemental function default_comp_ucs4(def_str, ucs4_str) result(res)
CDK==CK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: def_str
character(kind=CK, len=*), intent(in) :: ucs4_str
Return Value logical(kind=LK)
Calls
Called by
Source Code
    pure elemental function default_comp_ucs4(def_str,ucs4_str) result(res)
    implicit none
    character(kind=CDK,len=*), intent(in) :: def_str
    character(kind=CK, len=*), intent(in) :: ucs4_str
    logical(LK) :: res
    res = (to_unicode(def_str) == ucs4_str)
    end function default_comp_ucs4
Call graph
default_comp_ucs4 calls to_unicode
to_unicode calls to_uni, to_uni_vec
operator(==) calls default_comp_ucs4