encode_rfc6901 – JSON-Fortran
encode_rfc6901 Function
8 statements
Source File
public pure function encode_rfc6901(str) result(str_out)
Encode a string into the “JSON Pointer” RFC 6901 format.
It replaces ~ with ~0 and / with ~1.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: str
Return Value character(kind=CK, len=:), allocatable
Calls
Called by
Source Code
    pure function encode_rfc6901(str) result(str_out)
    implicit none
    character(kind=CK,len=*),intent(in) :: str
    character(kind=CK,len=:),allocatable :: str_out
    str_out = str
    call replace_string(str_out,tilde,tilde//CK_'0')
    call replace_string(str_out,slash,tilde//CK_'1')
    end function encode_rfc6901
Call graph
encode_rfc6901 calls replace_string
json_get_path calls encode_rfc6901
json_check_children_for_duplicate_keys calls get_path
wrap_json_get_path calls get_path