finalize_json_file – JSON-Fortran
finalize_json_file Subroutine
5 statements
Source File
private subroutine finalize_json_file(me)
Finalizer for json_file class.
Just a wrapper for json_file_destroy.
Arguments
Type Intent Optional Attributes Name
type(json_file), intent(inout) :: me
Calls
Source Code
    subroutine finalize_json_file(me)
    implicit none
    type(json_file),intent(inout) :: me
    call me%destroy(destroy_core=.true.)
    end subroutine finalize_json_file
Call graph
finalize_json_file calls json_file_destroy
json_file_destroy calls destroy
json_value_destroy calls destroy, destroy_json_data