get_current_line_from_file_sequential – JSON-Fortran
get_current_line_from_file_sequential Subroutine
Jacob Williams
22 statements
Source File
private subroutine get_current_line_from_file_sequential(iunit, line)
Rewind the file to the beginning of the current line, and return this line. The file is assumed to be opened. This is the SEQUENTIAL version (see also get_current_line_from_file_stream).
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: iunit
file unit number
character(kind=CK, len=:), intent(out), allocatable :: line
current line
Called by
Source Code
    subroutine get_current_line_from_file_sequential(iunit,line)
    implicit none
    integer(IK),intent(in)                           :: iunit  !! file unit number
    character(kind=CK,len=:),allocatable,intent(out) :: line   !! current line
    character(kind=CK,len=seq_chunk_size) :: chunk !! for reading line in chunks
    integer(IK) :: istat  !! iostat flag
    integer(IK) :: isize  !! number of characters read in read statement
    !initialize:
    line = CK_''
    !rewind to beginning of the current record:
    backspace(iunit, iostat=istat)
    !loop to read in all the characters in the current record.
    ![the line is read in chunks until the end of the line is reached]
    if (istat==0) then
        do
            isize = 0
            read(iunit,fmt='(A)',advance='NO',size=isize,iostat=istat) chunk
            if (istat==0) then
                line = line//chunk
            else
                if (isize>0 .and. isize<=seq_chunk_size) line = line//chunk(1:isize)
                exit
            end if
        end do
    end if
    end subroutine get_current_line_from_file_sequential
Call graph
annotate_invalid_json calls get_current_line_from_file_sequential
json_parse_file calls annotate_invalid_json
json_parse_string calls annotate_invalid_json
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2