json_get_next – JSON-Fortran
json_get_next Subroutine
Jacob Williams
10/31/2015
12 statements
Source File
private subroutine json_get_next(json, p, next)
Returns a pointer to the next of a json_value. If there is no next, then a null() pointer is returned.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
JSON object
type(json_value), intent(out), pointer :: next
pointer to next
Calls
Source Code
    subroutine json_get_next(json,p,next)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer,intent(in)  :: p       !! JSON object
    type(json_value),pointer,intent(out) :: next    !! pointer to `next`
    if (associated(p)) then
        next => p%next
    else
        nullify(next)
        call json%throw_exception('Error in json_get_next: '//&
                                  'pointer is not associated.')
    end if
    end subroutine json_get_next
Call graph
json_get_next calls throw_exception
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec