json_value_to_string – JSON-Fortran
json_value_to_string Subroutine
Jacob Williams
2/12/2014
16 statements
Source File
private subroutine json_value_to_string(json, p, str)
Print the json_value structure to an allocatable string.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
character(kind=CK, len=:), intent(out), allocatable :: str
prints structure to this string
Calls
Called by
Source Code
    subroutine json_value_to_string(json,p,str)
    implicit none
    class(json_core),intent(inout)                   :: json
    type(json_value),pointer,intent(in)              :: p
    character(kind=CK,len=:),intent(out),allocatable :: str  !! prints structure to this string
    integer(IK) :: iloc  !! used to keep track of size of str
                         !! since it is being allocated in chunks.
    character(kind=CK,len=:),allocatable :: tmp  !! temporary buffer for trimming `str`
    str = repeat(space, print_str_initial_buffer_size)
    iloc = 0_IK
    call json%json_value_print(p, iunit=unit2str, str=str, iloc=iloc, indent=1_IK, colon=.true.)
    ! trim the string if necessary:
    if (len(str)>iloc) then
        allocate(character(kind=CK,len=iloc)::tmp)
        tmp(1:iloc) = str
        call move_alloc(tmp, str)
    endif
    end subroutine json_value_to_string
Call graph
json_value_to_string calls json_value_print
json_value_print calls json_value_print, throw_exception, escape_string, integer_to_string, json_failed, json_is_vector, real_to_string
escape_string calls valid_json_hex
json_is_vector calls throw_exception, info
real_to_string calls compact_real_string
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_info calls throw_exception
json_info_by_path calls info, get
wrap_json_info_by_path calls info, to_unicode
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
convert calls throw_exception, info, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, info, get, json_clear_exceptions
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
wrap_json_value_get_child_by_name calls to_unicode, get
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string