json_matrix_info – JSON-Fortran
json_matrix_info Subroutine
Jacob Williams
10/16/2015
78 statements
Source File
private subroutine json_matrix_info(json, p, is_matrix, var_type, n_sets, set_size, name)
Alternate version of json_info that returns matrix information about a json_value.
A json_value is a valid rank 2 matrix if all of the following are true:
The var_type is json_array
Each child is also a json_array, each of which has the same number of elements
Each individual element has the same variable type (integer, logical, etc.)
The idea here is that if it is a valid matrix, it can be interoperable with a Fortran rank 2 array of the same type.
Example
The following example is an array with var_type=json_integer, n_sets=3, and set_size=4
    {
        "matrix": [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ]
    }
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
a JSON linked list
logical(kind=LK), intent(out) :: is_matrix
true if it is a valid matrix
integer(kind=IK), intent(out), optional :: var_type
variable type of data in the matrix (if all elements have the same type)
integer(kind=IK), intent(out), optional :: n_sets
number of data sets (i.e., matrix rows if using row-major order)
integer(kind=IK), intent(out), optional :: set_size
size of each data set (i.e., matrix cols if using row-major order)
character(kind=CK, len=:), intent(out), optional, allocatable :: name
variable name
Calls
Called by
Source Code
    subroutine json_matrix_info(json,p,is_matrix,var_type,n_sets,set_size,name)
    implicit none
    class(json_core),intent(inout)   :: json
    type(json_value),pointer         :: p          !! a JSON linked list
    logical(LK),intent(out)          :: is_matrix  !! true if it is a valid matrix
    integer(IK),intent(out),optional :: var_type   !! variable type of data in the matrix
                                                   !! (if all elements have the same type)
    integer(IK),intent(out),optional :: n_sets     !! number of data sets (i.e., matrix
                                                   !! rows if using row-major order)
    integer(IK),intent(out),optional :: set_size   !! size of each data set (i.e., matrix
                                                   !! cols if using row-major order)
    character(kind=CK,len=:),allocatable,intent(out),optional :: name !! variable name
    type(json_value),pointer :: p_row       !! for getting a set
    type(json_value),pointer :: p_element   !! for getting an element in a set
    integer(IK) :: vartype         !! json variable type of `p`
    integer(IK) :: row_vartype     !! json variable type of a row
    integer(IK) :: element_vartype !! json variable type of an element in a row
    integer(IK) :: nr              !! number of children of `p`
    integer(IK) :: nc              !! number of elements in first child of `p`
    integer(IK) :: icount          !! number of elements in a set
    integer(IK) :: i               !! counter
    integer(IK) :: j               !! counter
#if defined __GFORTRAN__
    character(kind=CK,len=:),allocatable :: p_name  !! temporary variable for getting name
#endif
    !get info about the variable:
#if defined __GFORTRAN__
    call json%info(p,vartype,nr)
    if (present(name)) then !workaround for gfortran bug
        if (allocated(p%name)) then
            p_name = p%name
            name = p_name
        else
            name = CK_''
        end if
    end if
#else
    call json%info(p,vartype,nr,name)
#endif
    is_matrix = (vartype==json_array)
    if (is_matrix) then
        main : do i=1,nr
            nullify(p_row)
            call json%get_child(p,i,p_row)
            if (.not. associated(p_row)) then
                is_matrix = .false.
                call json%throw_exception('Error in json_matrix_info: '//&
                                          'Malformed JSON linked list')
                exit main
            end if
            call json%info(p_row,var_type=row_vartype,n_children=icount)
            if (row_vartype==json_array) then
                if (i==1) nc = icount  !number of columns in first row
                if (icount==nc) then   !make sure each row has the same number of columns
                    !see if all the variables in this row are the same type:
                    do j=1,icount
                        nullify(p_element)
                        call json%get_child(p_row,j,p_element)
                        if (.not. associated(p_element)) then
                            is_matrix = .false.
                            call json%throw_exception('Error in json_matrix_info: '//&
                                                      'Malformed JSON linked list')
                            exit main
                        end if
                        call json%info(p_element,var_type=element_vartype)
                        if (i==1 .and. j==1) vartype = element_vartype  !type of first element
                                                                        !in the row
                        if (vartype/=element_vartype) then
                            !not all variables are the same time
                            is_matrix = .false.
                            exit main
                        end if
                    end do
                else
                    is_matrix = .false.
                    exit main
                end if
            else
                is_matrix = .false.
                exit main
            end if
        end do main
    end if
    if (is_matrix) then
        if (present(var_type)) var_type = vartype
        if (present(n_sets))   n_sets   = nr
        if (present(set_size)) set_size = nc
    else
        if (present(var_type)) var_type = json_unknown
        if (present(n_sets))   n_sets   = 0
        if (present(set_size)) set_size = 0
    end if
    end subroutine json_matrix_info
Call graph
json_matrix_info calls get_child, info, throw_exception
json_info calls throw_exception
json_info_by_path calls info, get
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
wrap_json_info_by_path calls info, to_unicode
wrap_json_throw_exception calls throw_exception, to_unicode
wrap_json_value_get_child_by_name calls to_unicode, get
to_unicode calls to_uni, to_uni_vec
name_equal calls name_strings_equal
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, integer_to_string, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
name_strings_equal calls lowercase_string
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
escape_string calls valid_json_hex
json_get_by_path_default calls get_child, throw_exception, json_clear_exceptions, string_to_integer, add, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls get_child, throw_exception, json_clear_exceptions, string_to_integer, add, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls get_child, throw_exception, json_clear_exceptions, string_to_integer, decode_rfc6901
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls info, throw_exception, get, json_clear_exceptions
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_replace calls insert_after, json_value_remove
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_destroy calls destroy_json_data, destroy
json_file_variable_matrix_info calls matrix_info
json_matrix_info_by_path calls matrix_info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_file_variable_matrix_info calls matrix_info