json_is_vector – JSON-Fortran
json_is_vector Function
35 statements
Source File
private function json_is_vector(json, p) result(is_vector)
Returns true if all the children are the same type (and a scalar). Note that integers and reals are considered the same type for this purpose. This routine is used for the compress_vectors option.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
Return Value logical(kind=LK)
if all elements of a vector are scalars of the same type
Calls
Called by
Source Code
    function json_is_vector(json, p) result(is_vector)
    implicit none
    class(json_core),intent(inout) :: json
    type(json_value),pointer       :: p
    logical(LK)                    :: is_vector  !! if all elements of a vector
                                                 !! are scalars of the same type
    integer(IK) :: var_type_prev !! for getting the variable type of children
    integer(IK) :: var_type !! for getting the variable type of children
    type(json_value),pointer :: element !! for getting children
    integer(IK) :: i !! counter
    integer(IK) :: count !! number of children
    integer(IK),parameter :: json_invalid = -1_IK  !! to initialize the flag. an invalid value
    integer(IK),parameter :: json_numeric = -2_IK  !! indicates `json_integer` or `json_real`
    if (json%compress_vectors) then
        ! check to see if every child is the same type,
        ! and a scalar:
        is_vector = .true.
        var_type_prev = json_invalid
        count = json%count(p)
        element => p%children
        do i = 1_IK, count
            if (.not. associated(element)) then
                call json%throw_exception('Error in json_is_vector: '//&
                                          'Malformed JSON linked list')
                return
            end if
            ! check variable type of all the children.
            ! They must all be the same, and a scalar.
            call json%info(element,var_type=var_type)
            ! special check for numeric values:
            if (var_type==json_integer .or. var_type==json_real) var_type = json_numeric
            if (var_type==json_object .or. &
                var_type==json_array .or. &
                (i>1_IK .and. var_type/=var_type_prev)) then
                is_vector = .false.
                exit
            end if
            var_type_prev = var_type
            ! get the next child the list:
            element => element%next
        end do
    else
        is_vector = .false.
    end if
    end function json_is_vector
Call graph
json_is_vector calls info, throw_exception
json_info calls throw_exception
json_info_by_path calls info, get
wrap_json_info_by_path calls info, to_unicode
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls info, throw_exception, get, json_clear_exceptions
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
wrap_json_value_get_child_by_name calls to_unicode, get
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy
json_value_print calls json_is_vector, json_value_print
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string