json_check_children_for_duplicate_keys – JSON-Fortran
json_check_children_for_duplicate_keys Subroutine
Jacob Williams
8/25/2017
67 statements
Source File
private subroutine json_check_children_for_duplicate_keys(json, p, has_duplicate, name, path)
Checks a JSON object for duplicate child names.
It uses the specified settings for name matching (see name_strings_equal).
Note
This will only check for one duplicate, it will return the first one that it finds.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
the object to search. If p is not a json_object, then has_duplicate will be false.
logical(kind=LK), intent(out) :: has_duplicate
true if there is at least two children have duplicate name values.
character(kind=CK, len=:), intent(out), optional, allocatable :: name
the duplicate name (unallocated if no duplicate was found)
character(kind=CK, len=:), intent(out), optional, allocatable :: path
the full path to the duplicate name (unallocated if no duplicate was found)
Calls
Source Code
    subroutine json_check_children_for_duplicate_keys(json,p,has_duplicate,name,path)
    implicit none
    class(json_core),intent(inout) :: json
    type(json_value),pointer,intent(in) :: p  !! the object to search. If `p` is
                                              !! not a `json_object`, then `has_duplicate`
                                              !! will be false.
    logical(LK),intent(out) :: has_duplicate  !! true if there is at least
                                              !! two children have duplicate
                                              !! `name` values.
    character(kind=CK,len=:),allocatable,intent(out),optional :: name !! the duplicate name
                                                                      !! (unallocated if no
                                                                      !! duplicate was found)
    character(kind=CK,len=:),allocatable,intent(out),optional :: path !! the full path to the
                                                                      !! duplicate name
                                                                      !! (unallocated if no
                                                                      !! duplicate was found)
    integer(IK)              :: i           !! counter
    integer(IK)              :: j           !! counter
    type(json_value),pointer :: child       !! pointer to a child of `p`
    integer(IK)              :: n_children  !! number of children of `p`
    logical(LK)              :: found       !! flag for `get_child`
    type :: alloc_str
        !! so we can have an array of allocatable strings
        character(kind=CK,len=:),allocatable :: str  !! name string
    end type alloc_str
    type(alloc_str),dimension(:),allocatable :: names !! array of all the
                                                      !! child name strings
    ! initialize:
    has_duplicate =.false.
    if (.not. json%exception_thrown) then
        if (associated(p)) then
            if (p%var_type==json_object) then
                ! number of items to check:
                n_children = json%count(p)
                allocate(names(n_children))
                ! first get a list of all the name keys:
                do i=1, n_children
                    call json%get_child(p,i,child,found) ! get by index
                    if (.not. found) then
                        call json%throw_exception(&
                            'Error in json_check_children_for_duplicate_keys: '//&
                            'Malformed JSON linked list')
                        exit
                    end if
                    if (allocated(child%name)) then
                        names(i)%str = child%name
                    else
                        call json%throw_exception(&
                            'Error in json_check_children_for_duplicate_keys: '//&
                            'Object child name is not allocated')
                        exit
                    end if
                end do
                if (.not. json%exception_thrown) then
                    ! now check the list for duplicates:
                    main: do i=1,n_children
                        do j=1,i-1
                            if (json%name_strings_equal(names(i)%str,names(j)%str)) then
                                has_duplicate = .true.
                                if (present(name)) then
                                    name = names(i)%str
                                end if
                                if (present(path)) then
                                    call json%get_child(p,names(i)%str,child,found) ! get by name
                                    if (found) then
                                        call json%get_path(child,path,found)
                                        if (.not. found) then
                                            ! should never happen since we know it is there
                                            call json%throw_exception(&
                                                    'Error in json_check_children_for_duplicate_keys: '//&
                                                    'Could not get path')
                                        end if
                                    else
                                        ! should never happen since we know it is there
                                        call json%throw_exception(&
                                            'Error in json_check_children_for_duplicate_keys: '//&
                                            'Could not get child: '//trim(names(i)%str))
                                    end if
                                end if
                                exit main
                            end if
                        end do
                    end do main
                end if
                ! cleanup
                do i=1,n_children
                    if (allocated(names(i)%str)) deallocate(names(i)%str)
                end do
                if (allocated(names)) deallocate(names)
            end if
        end if
    end if
    end subroutine json_check_children_for_duplicate_keys
Call graph
json_check_children_for_duplicate_keys calls get_child, get_path, throw_exception, name_strings_equal
name_strings_equal calls lowercase_string
json_get_path calls throw_exception, info, encode_rfc6901, integer_to_string, json_clear_exceptions
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
wrap_json_get_path calls get_path, to_unicode
wrap_json_throw_exception calls throw_exception, to_unicode
wrap_json_value_get_child_by_name calls to_unicode, get
to_unicode calls to_uni, to_uni_vec
encode_rfc6901 calls replace_string
name_equal calls name_strings_equal
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, json_clear_exceptions, flag_not_found
json_info calls throw_exception
json_info_by_path calls get, info
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
wrap_json_info_by_path calls to_unicode, info
escape_string calls valid_json_hex
json_get_by_path_default calls get_child, throw_exception, json_clear_exceptions, string_to_integer, add, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls get_child, throw_exception, json_clear_exceptions, string_to_integer, add, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls get_child, throw_exception, json_clear_exceptions, string_to_integer, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, info, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, get, info, json_clear_exceptions
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_replace calls insert_after, json_value_remove
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_destroy calls destroy_json_data, destroy