json_matrix_info_by_path – JSON-Fortran
json_matrix_info_by_path Subroutine
41 statements
Source File
private subroutine json_matrix_info_by_path(json, p, path, is_matrix, found, var_type, n_sets, set_size, name)
Returns matrix information about a json_value, given the path.
See also
json_matrix_info
Note
If found is present, no exceptions will be thrown if an error occurs. Otherwise, an exception will be thrown if the variable is not found.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
a JSON linked list
character(kind=CK, len=*), intent(in) :: path
path to the variable
logical(kind=LK), intent(out) :: is_matrix
true if it is a valid matrix
logical(kind=LK), intent(out), optional :: found
true if it was found
integer(kind=IK), intent(out), optional :: var_type
variable type of data in the matrix (if all elements have the same type)
integer(kind=IK), intent(out), optional :: n_sets
number of data sets (i.e., matrix rows if using row-major order)
integer(kind=IK), intent(out), optional :: set_size
size of each data set (i.e., matrix cols if using row-major order)
character(kind=CK, len=:), intent(out), optional, allocatable :: name
variable name
Calls
Called by
Source Code
    subroutine json_matrix_info_by_path(json,p,path,is_matrix,found,&
                                        var_type,n_sets,set_size,name)
    implicit none
    class(json_core),intent(inout)      :: json
    type(json_value),pointer            :: p         !! a JSON linked list
    character(kind=CK,len=*),intent(in) :: path      !! path to the variable
    logical(LK),intent(out)             :: is_matrix !! true if it is a valid matrix
    logical(LK),intent(out),optional    :: found     !! true if it was found
    integer(IK),intent(out),optional    :: var_type  !! variable type of data in
                                                     !! the matrix (if all elements have
                                                     !! the same type)
    integer(IK),intent(out),optional    :: n_sets    !! number of data sets (i.e., matrix
                                                     !! rows if using row-major order)
    integer(IK),intent(out),optional    :: set_size  !! size of each data set (i.e., matrix
                                                     !! cols if using row-major order)
    character(kind=CK,len=:),allocatable,intent(out),optional :: name !! variable name
    type(json_value),pointer :: p_var
    logical(LK) :: ok
#if defined __GFORTRAN__
    character(kind=CK,len=:),allocatable :: p_name  !! temporary variable for getting name
#endif
    call json%get(p,path,p_var,found)
    !check if it was found:
    if (present(found)) then
        ok = found
    else
        ok = .not. json%exception_thrown
    end if
    if (.not. ok) then
        if (present(var_type)) var_type = json_unknown
        if (present(n_sets))   n_sets   = 0
        if (present(set_size)) set_size = 0
        if (present(name))     name     = CK_''
    else
        !get info about the variable:
#if defined __GFORTRAN__
        call json%matrix_info(p_var,is_matrix,var_type,n_sets,set_size)
        if (present(name)) then !workaround for gfortran bug
            if (allocated(p_var%name)) then
                p_name = p_var%name
                name = p_name
            else
                name = CK_''
            end if
        end if
#else
        call json%matrix_info(p_var,is_matrix,var_type,n_sets,set_size,name)
#endif
        if (json%exception_thrown .and. present(found)) then
            found = .false.
            call json%clear_exceptions()
        end if
    end if
    end subroutine json_matrix_info_by_path
Call graph
json_matrix_info_by_path calls get, matrix_info, json_clear_exceptions
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls get, json_clear_exceptions, throw_exception
json_get_by_path calls json_clear_exceptions, throw_exception, integer_to_string, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls get, json_clear_exceptions, throw_exception, flag_not_found
json_matrix_info calls get_child, info, throw_exception
wrap_json_get_alloc_string_vec_by_path calls get, to_unicode
wrap_json_get_array_by_path calls get, to_unicode
wrap_json_get_by_path calls get, to_unicode
wrap_json_get_integer_by_path calls get, to_unicode
wrap_json_get_integer_vec_by_path calls get, to_unicode
wrap_json_get_logical_by_path calls get, to_unicode
wrap_json_get_logical_vec_by_path calls get, to_unicode
wrap_json_get_real32_by_path calls get, to_unicode
wrap_json_get_real32_vec_by_path calls get, to_unicode
wrap_json_get_real_by_path calls get, to_unicode
wrap_json_get_real_vec_by_path calls get, to_unicode
wrap_json_get_string_by_path calls get, to_unicode
wrap_json_get_string_vec_by_path calls get, to_unicode
wrap_json_matrix_info_by_path calls matrix_info, to_unicode
to_unicode calls to_uni, to_uni_vec
escape_string calls valid_json_hex
json_get_by_path_default calls json_clear_exceptions, get_child, throw_exception, string_to_integer, add, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls json_clear_exceptions, get_child, throw_exception, string_to_integer, add, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls json_clear_exceptions, get_child, throw_exception, string_to_integer, decode_rfc6901
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_info calls throw_exception
json_info_by_path calls get, info
json_string_info calls get, json_clear_exceptions, info, throw_exception
json_value_get_child calls throw_exception
json_value_get_child_by_index calls json_clear_exceptions, throw_exception
json_value_get_child_by_name calls json_clear_exceptions, throw_exception, name_equal
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
wrap_json_info_by_path calls to_unicode, info
wrap_json_throw_exception calls to_unicode, throw_exception
wrap_json_value_get_child_by_name calls get, to_unicode
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_replace calls insert_after, json_value_remove
name_equal calls name_strings_equal
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_strings_equal calls lowercase_string
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_destroy calls destroy_json_data, destroy
json_file_variable_matrix_info calls matrix_info
wrap_json_file_variable_matrix_info calls matrix_info