json_get_previous – JSON-Fortran
json_get_previous Subroutine
Jacob Williams
10/31/2015
12 statements
Source File
private subroutine json_get_previous(json, p, previous)
Returns a pointer to the previous of a json_value. If there is no previous, then a null() pointer is returned.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
JSON object
type(json_value), intent(out), pointer :: previous
pointer to previous
Calls
Source Code
    subroutine json_get_previous(json,p,previous)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer,intent(in)  :: p        !! JSON object
    type(json_value),pointer,intent(out) :: previous !! pointer to `previous`
    if (associated(p)) then
        previous => p%previous
    else
        nullify(previous)
        call json%throw_exception('Error in json_get_previous: '//&
                                  'pointer is not associated.')
    end if
    end subroutine json_get_previous
Call graph
json_get_previous calls throw_exception
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec