json_traverse – JSON-Fortran
json_traverse Subroutine
Jacob Williams
4/28/2016
35 statements
Source File
private subroutine json_traverse(json, p, traverse_callback)
Traverse a JSON structure. This routine calls the user-specified json_traverse_callback_func for each element of the structure.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
procedure(json_traverse_callback_func) :: traverse_callback
Calls
Called by
Source Code
    subroutine json_traverse(json,p,traverse_callback)
    implicit none
    class(json_core),intent(inout)         :: json
    type(json_value),pointer,intent(in)    :: p
    procedure(json_traverse_callback_func) :: traverse_callback
    logical(LK) :: finished !! can be used to stop the process
    if (.not. json%exception_thrown) call traverse(p)
    contains
        recursive subroutine traverse(p)
        !! recursive [[json_value]] traversal.
        implicit none
        type(json_value),pointer,intent(in) :: p
        type(json_value),pointer :: element  !! a child element
        integer(IK) :: i        !! counter
        integer(IK) :: icount   !! number of children
        if (json%exception_thrown) return
        call traverse_callback(json,p,finished) ! first call for this object
        if (finished) return
        !for arrays and objects, have to also call for all children:
        if (p%var_type==json_array .or. p%var_type==json_object) then
            icount = json%count(p) ! number of children
            if (icount>0) then
                element => p%children   ! first one
                do i = 1, icount        ! call for each child
                    if (.not. associated(element)) then
                        call json%throw_exception('Error in json_traverse: '//&
                                                  'Malformed JSON linked list')
                        return
                    end if
                    call traverse(element)
                    if (finished .or. json%exception_thrown) exit
                    element => element%next
                end do
            end if
            nullify(element)
        end if
        end subroutine traverse
    end subroutine json_traverse
Call graph
json_traverse calls throw_exception
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
json_check_all_for_duplicate_keys calls json_traverse
json_file_traverse calls json_traverse
json_value_is_child_of calls json_traverse
json_parse_file calls json_check_all_for_duplicate_keys
json_parse_string calls json_check_all_for_duplicate_keys
json_value_swap calls json_value_is_child_of
json_value_validate calls json_check_all_for_duplicate_keys
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2