json_file_print_to_unit – JSON-Fortran
json_file_print_to_unit Subroutine
Jacob Williams
12/9/2013
10 statements
Source File
private subroutine json_file_print_to_unit(me, iunit)
Prints the JSON file to the specified file unit number.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
integer(kind=IK), intent(in) :: iunit
file unit number (must not be -1)
Calls
Source Code
    subroutine json_file_print_to_unit(me, iunit)
    implicit none
    class(json_file),intent(inout)  :: me
    integer(IK),intent(in)          :: iunit  !! file unit number (must not be -1)
    if (iunit/=unit2str) then
        call me%core%print(me%p,iunit=iunit)
    else
        call me%core%throw_exception('Error in json_file_print_to_unit: iunit must not be -1.')
    end if
    end subroutine json_file_print_to_unit
Call graph
json_file_print_to_unit calls throw_exception
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec