parse_string – JSON-Fortran
parse_string Subroutine
47 statements
Source File
private subroutine parse_string(json, unit, str, string)
Parses a string while reading a JSON file.
History
Jacob Williams : 6/16/2014 : Added hex validation.
Jacob Williams : 12/3/2015 : Fixed some bugs.
Jacob Williams : 8/23/2015 : string is now returned unescaped.
Jacob Williams : 7/21/2018 : moved hex validate to unescape_string.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK, len=*), intent(in) :: str
JSON string (if parsing from a string)
character(kind=CK, len=:), intent(out), allocatable :: string
the string (unescaped if necessary)
Calls
Called by
Source Code
    subroutine parse_string(json, unit, str, string)
    implicit none
    class(json_core),intent(inout)                   :: json
    integer(IK),intent(in)                           :: unit   !! file unit number (if
                                                               !! parsing from a file)
    character(kind=CK,len=*),intent(in)              :: str    !! JSON string (if parsing
                                                               !! from a string)
    character(kind=CK,len=:),allocatable,intent(out) :: string !! the string (unescaped
                                                               !! if necessary)
    logical(LK)              :: eof      !! end of file flag
    logical(LK)              :: escape   !! for escape string parsing
    character(kind=CK,len=1) :: c        !! character returned by [[pop_char]]
    integer(IK)              :: ip       !! index to put next character,
                                         !! to speed up by reducing the number
                                         !! of character string reallocations.
    character(kind=CK,len=:),allocatable :: error_message !! for string unescaping
    !at least return a blank string if there is a problem:
    string = blank_chunk
    if (.not. json%exception_thrown) then
        !initialize:
        escape = .false.
        ip     = 1
        do
            !get the next character from the file:
            call json%pop_char(unit, str=str, eof=eof, skip_ws=.false., popped=c)
            if (eof) then
                call json%throw_exception('Error in parse_string: Expecting end of string')
                return
            else if (c==quotation_mark .and. .not. escape) then  !end of string
                exit
            else
                !if the string is not big enough, then add another chunk:
                if (ip>len(string)) string = string // blank_chunk
                !append to string:
                string(ip:ip) = c
                ip = ip + 1
                ! check for escape character, so we don't
                ! exit prematurely if escaping a quotation
                ! character:
                if (escape) then
                    escape = .false.
                else
                    escape = (c==backslash)
                end if
            end if
        end do
        !trim the string if necessary:
        if (ip<len(string)+1) then
            if (ip==1) then
                string = CK_''
            else
                string = string(1:ip-1)
            end if
        end if
        ! string is returned unescaped:
        ! (this will also validate any hex strings present)
        call unescape_string(string,error_message)
        if (allocated(error_message)) then
            call json%throw_exception(error_message)
            deallocate(error_message)  !cleanup
        end if
    end if
    end subroutine parse_string
Call graph
parse_string calls throw_exception, pop_char, unescape_string
unescape_string calls valid_json_hex
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
parse_object calls parse_string, parse_object, parse_value
parse_value calls parse_string, parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2