parse_for_chars – JSON-Fortran
parse_for_chars Subroutine
24 statements
Source File
private subroutine parse_for_chars(json, unit, str, chars)
Core parsing routine.
This is used to verify the strings true, false, and null during parsing.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK, len=*), intent(in) :: str
JSON string (if parsing from a string)
character(kind=CK, len=*), intent(in) :: chars
the string to check for.
Calls
Called by
Source Code
    subroutine parse_for_chars(json, unit, str, chars)
    implicit none
    class(json_core),intent(inout)      :: json
    integer(IK),intent(in)              :: unit   !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str    !! JSON string (if parsing from a string)
    character(kind=CK,len=*),intent(in) :: chars  !! the string to check for.
    integer(IK) :: i               !! counter
    integer(IK) :: length          !! trimmed length of `chars`
    logical(LK) :: eof             !! end of file flag
    character(kind=CK,len=1) :: c  !! character returned by [[pop_char]]
    if (.not. json%exception_thrown) then
        length = len_trim(chars)
        do i = 1, length
            call json%pop_char(unit, str=str, eof=eof, skip_ws=.false., popped=c)
            if (eof) then
                call json%throw_exception('Error in parse_for_chars:'//&
                                     ' Unexpected end of file while parsing.')
                return
            else if (c /= chars(i:i)) then
                call json%throw_exception('Error in parse_for_chars:'//&
                                     ' Unexpected character: "'//c//'" (expecting "'//&
                                     chars(i:i)//'")')
                return
            end if
        end do
    end if
    end subroutine parse_for_chars
Call graph
parse_for_chars calls throw_exception, pop_char
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
parse_value calls parse_for_chars, parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
parse_object calls parse_value, parse_object
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2