pop_char – JSON-Fortran
pop_char Subroutine
98 statements
Source File
private subroutine pop_char(json, unit, str, skip_ws, skip_comments, eof, c)
Get the next character from the file (or string).
See also
push_char
Note
This routine ignores non-printing ASCII characters (iachar<=31) that are in strings.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK, len=*), intent(in) :: str
JSON string (if parsing from a string) – only used if unit=0
logical(kind=LK), intent(in), optional :: skip_ws
to ignore whitespace [default False]
logical(kind=LK), intent(in), optional :: skip_comments
to ignore comment lines [default False]
logical(kind=LK), intent(out) :: eof
true if the end of the file has been reached.
character(kind=CK, len=1), intent(out) :: c
the popped character returned
Called by
Source Code
    subroutine pop_char(json,unit,str,skip_ws,skip_comments,eof,c)
    implicit none
    class(json_core),intent(inout)       :: json
    integer(IK),intent(in)               :: unit          !! file unit number (if parsing
                                                          !! from a file)
    character(kind=CK,len=*),intent(in)  :: str           !! JSON string (if parsing from a
                                                          !! string) -- only used if `unit=0`
    logical(LK),intent(in),optional      :: skip_ws       !! to ignore whitespace [default False]
    logical(LK),intent(in),optional      :: skip_comments !! to ignore comment lines [default False]
    logical(LK),intent(out)              :: eof           !! true if the end of the file has
                                                          !! been reached.
    character(kind=CK,len=1),intent(out) :: c             !! the popped character returned
    integer(IK) :: ios             !! `iostat` flag
    logical(LK) :: ignore          !! if whitespace is to be ignored
    logical(LK) :: ignore_comments !! if comment lines are to be ignored
    logical(LK) :: parsing_comment !! if we are in the process
                                   !! of parsing a comment line
    integer(IK) :: tmp             !! local copy of `iachar(c)`
    if (.not. json%exception_thrown) then
        eof = .false.
        if (.not. present(skip_ws)) then
            ignore = .false.
        else
            ignore = skip_ws
        end if
        parsing_comment = .false.
        if (.not. present(skip_comments)) then
            ignore_comments = .false.
        else
            ignore_comments = skip_comments
        end if
        do
            if (json%pushed_index > 0) then
                ! there is a character pushed back on, most likely
                ! from the number parsing. Note: this can only occur if
                ! reading from a file when use_unformatted_stream=.false.
                c = json%pushed_char(json%pushed_index:json%pushed_index)
                json%pushed_index = json%pushed_index - 1
            else
                if (unit/=0) then    !read from the file
                    !read the next character:
                    if (use_unformatted_stream) then
                        ! in this case, we read the file in chunks.
                        ! if we already have the character we need,
                        ! then get it from the chunk. Otherwise,
                        ! read in another chunk.
                        if (json%ichunk<1) then
                            ! read in a chunk:
                            json%ichunk = 0
                            if (json%filesize<json%ipos+size(json%chunk)-1) then
                                ! for the last chunk, we resize
                                ! it to the correct size:
                                deallocate(json%chunk)
                                allocate(json%chunk(json%filesize-json%ipos+1))
                                json%chunk = space
                            end if
                            read(unit=unit,pos=json%ipos,iostat=ios) json%chunk
                        else
                            ios = 0
                        end if
                        json%ichunk = json%ichunk + 1
                        if (json%ichunk>size(json%chunk)) then
                            ! check this just in case
                            ios = IOSTAT_END
                        else
                            ! get the next character from the chunk:
                            c = json%chunk(json%ichunk)
                            if (json%ichunk==size(json%chunk)) then
                                json%ichunk = 0 ! reset for next chunk
                            end if
                        end if
                    else
                        ! a formatted read:
                        read(unit=unit,fmt='(A1)',advance='NO',iostat=ios) c
                    end if
                    json%ipos = json%ipos + 1
                else    !read from the string
                    if (json%ipos<=len(str)) then
                        c = str(json%ipos:json%ipos)
                        ios = 0
                    else
                        ios = IOSTAT_END  !end of the string
                    end if
                    json%ipos = json%ipos + 1
                end if
                json%char_count = json%char_count + 1    !character count in the current line
                if (IS_IOSTAT_END(ios)) then  !end of file
                    ! no character to return
                    json%char_count = 0
                    eof = .true.
                    c = space ! just to set a value
                    exit
                else if (IS_IOSTAT_EOR(ios) .or. c==newline) then    !end of record
                    json%char_count = 0
                    json%line_count = json%line_count + 1
                    if (ignore_comments) parsing_comment = .false. ! done parsing this comment line
                    cycle
                end if
            end if
            if (ignore) then ! ignoring whitespace
                 if (c == space) cycle
            end if
            if (ignore_comments) then
                if (parsing_comment) cycle ! still in the comment
                if (scan(c,json%comment_char,kind=IK)>0_IK) then
                    ! start of comment, skipping it
                    parsing_comment = .true.
                    cycle
                end if
            end if
            tmp = iachar(c,kind=IK)
            ! skip non printing ascii characters [these are the control_chars]
            if ( (tmp>=1 .and. tmp<=31) .or. (tmp==127)) cycle
            ! return the character c
            exit
        end do
    else
        c = space
    end if
    end subroutine pop_char
Call graph
json_parse_end calls pop_char
parse_array calls pop_char
parse_for_chars calls pop_char
parse_number calls pop_char
parse_object calls pop_char, parse_object, parse_string
parse_string calls pop_char
parse_value_nonrecursive calls pop_char, parse_for_chars, parse_number, parse_string
parse_value_recursive calls pop_char, parse_array, parse_for_chars, parse_number, parse_object, parse_string
json_parse_file calls json_parse_end
json_parse_string calls json_parse_end
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2