push_char – JSON-Fortran
push_char Subroutine
21 statements
Source File
private subroutine push_char(json, c)
Core routine.
See also
pop_char
History
Jacob Williams : 5/3/2015 : replaced original version of this routine.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
character(kind=CK, len=1), intent(in) :: c
to character to push
Calls
Called by
Source Code
    subroutine push_char(json,c)
    implicit none
    class(json_core),intent(inout)      :: json
    character(kind=CK,len=1),intent(in) :: c     !! to character to push
    character(kind=CK,len=max_numeric_str_len) :: istr  !! for error printing
    if (.not. json%exception_thrown) then
        if (use_unformatted_stream) then
            !in this case, c is ignored, and we just
            !decrement the stream position counter:
            json%ipos = json%ipos - 1
            json%ichunk = json%ichunk - 1
        else
            json%pushed_index = json%pushed_index + 1
            if (json%pushed_index>0 .and. json%pushed_index<=len(json%pushed_char)) then
                json%pushed_char(json%pushed_index:json%pushed_index) = c
            else
                call integer_to_string(json%pushed_index,int_fmt,istr)
                call json%throw_exception('Error in push_char: '//&
                                          'invalid valid of pushed_index: '//trim(istr))
            end if
        end if
        !character count in the current line
        json%char_count = json%char_count - 1
    end if
    end subroutine push_char
Call graph
push_char calls throw_exception, integer_to_string
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
parse_number calls push_char
parse_value calls push_char, parse_number, parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
parse_object calls parse_value, parse_object
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2