set_json_core_in_file – JSON-Fortran
set_json_core_in_file Subroutine
6 statements
Source File
private subroutine set_json_core_in_file(me, core)
Set the json_core for this json_file.
Note
This does not destroy the data in the file.
Note
This one is used if you want to initialize the file with an already-existing json_core (presumably, this was already initialized by a call to initialize_json_core or similar).
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
type(json_core), intent(in) :: core
Called by
Source Code
    subroutine set_json_core_in_file(me,core)
    implicit none
    class(json_file),intent(inout) :: me
    type(json_core),intent(in)     :: core
    me%core = core
    end subroutine set_json_core_in_file
Call graph
initialize_json_file calls initialize
initialize_json_file_from_string calls initialize
json_file_move_pointer calls initialize
json_file calls initialize_json_file, initialize_json_file_from_string, wrap_initialize_json_file_from_string
wrap_initialize_json_file_from_string calls initialize_json_file_from_string