string_to_int – JSON-Fortran
string_to_int Function
12 statements
Source File
private function string_to_int(json, str) result(ival)
Convert a string into an integer.
Note
Replacement for the parse_integer function in the original code.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
character(kind=CK, len=*), intent(in) :: str
a string
Return Value integer(kind=IK)
str converted to an integer
Calls
Called by
Source Code
    function string_to_int(json,str) result(ival)
    implicit none
    class(json_core),intent(inout)      :: json
    character(kind=CK,len=*),intent(in) :: str   !! a string
    integer(IK)                         :: ival  !! `str` converted to an integer
    logical(LK) :: status_ok !! error flag for [[string_to_integer]]
    ! call the core routine:
    call string_to_integer(str,ival,status_ok)
    if (.not. status_ok) then
        ival = 0
        call json%throw_exception('Error in string_to_int: '//&
                                    'string cannot be converted to an integer: '//&
                                    trim(str))
    end if
    end function string_to_int
Call graph
string_to_int calls throw_exception, string_to_integer
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec
parse_number calls string_to_int
parse_value calls parse_number, parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
parse_object calls parse_value, parse_object
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2