ucs4_join_default – JSON-Fortran
ucs4_join_default Function
Izaak Beekman
7 statements
Source File
private pure function ucs4_join_default(ucs4_str, def_str) result(res)
CK//CDK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: ucs4_str
character(kind=CDK, len=*), intent(in) :: def_str
Return Value character(kind=CK, len=len=(len(ucs4_str)+len(def_str)))
Calls
Called by
Contents
Source Code
ucs4_join_default
Source Code
    pure function ucs4_join_default(ucs4_str,def_str) result(res)
    implicit none
    character(kind=CK, len=*), intent(in) :: ucs4_str
    character(kind=CDK,len=*), intent(in) :: def_str
    character(kind=CK,len=(len(ucs4_str)+len(def_str))) :: res
    res = ucs4_str//to_unicode(def_str)
    end function ucs4_join_default
Call graph
ucs4_join_default calls to_unicode
to_unicode calls to_uni, to_uni_vec
operator(SLASHSLASH) calls ucs4_join_default