wrap_json_value_create_real32 – JSON-Fortran
wrap_json_value_create_real32 Subroutine
8 statements
Source File
private subroutine wrap_json_value_create_real32(json, p, val, name)
Alternate version of json_value_create_real32 where “name” is kind(CDK).
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
real(kind=real32), intent(in) :: val
character(kind=CDK, len=*), intent(in) :: name
Calls
Called by
Source Code
    subroutine wrap_json_value_create_real32(json,p,val,name)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    real(real32),intent(in)              :: val
    character(kind=CDK,len=*),intent(in) :: name
    call json%create_real(p,val,to_unicode(name))
    end subroutine wrap_json_value_create_real32
Call graph
wrap_json_value_create_real32 calls to_unicode, create_real
to_unicode calls to_uni, to_uni_vec
json_value_create_real32 calls create_real
json_add_real_by_path calls create_real
json_value_add_real calls create_real
wrap_json_value_create_real calls create_real
wrap_json_add_real_by_path calls json_add_real_by_path