wrap_json_value_create_string – JSON-Fortran
wrap_json_value_create_string Subroutine
Izaak Beekman
10 statements
Source File
private subroutine wrap_json_value_create_string(json, p, val, name, trim_str, adjustl_str)
Wrap json_value_create_string so that create_string method may be called with actual character string arguments for name and val that are BOTH of ‘DEFAULT’ or ‘ISO_10646’ character kind.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
character(kind=CDK, len=*), intent(in) :: val
character(kind=CDK, len=*), intent(in) :: name
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for the val
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for the val
Calls
Called by
Source Code
    subroutine wrap_json_value_create_string(json,p,val,name,trim_str,adjustl_str)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    character(kind=CDK,len=*),intent(in) :: val
    character(kind=CDK,len=*),intent(in) :: name
    logical(LK),intent(in),optional      :: trim_str      !! if TRIM() should be called for the `val`
    logical(LK),intent(in),optional      :: adjustl_str   !! if ADJUSTL() should be called for the `val`
    call json%create_string(p,to_unicode(val),to_unicode(name),trim_str,adjustl_str)
    end subroutine wrap_json_value_create_string
Call graph
wrap_json_value_create_string calls to_unicode, create_string
to_unicode calls to_uni, to_uni_vec
json_value_create_string calls json_value_create, to_string
to_string calls destroy_json_data
json_add_string_by_path calls create_string
json_value_add_string calls create_string
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_update_integer calls add_by_path
json_update_logical calls add_by_path
json_update_real calls add_by_path
json_update_string calls add_by_path
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec