wrap_json_value_create_logical – JSON-Fortran
wrap_json_value_create_logical Subroutine
Izaak Beekman
8 statements
Source File
private subroutine wrap_json_value_create_logical(json, p, val, name)
Wrapper for json_value_create_logical so create_logical method can be called with name of character kind ‘DEFAULT’ or ‘ISO_10646’
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
logical(kind=LK), intent(in) :: val
character(kind=CDK, len=*), intent(in) :: name
Calls
Called by
Source Code
    subroutine wrap_json_value_create_logical(json,p,val,name)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    logical(LK),intent(in)               :: val
    character(kind=CDK,len=*),intent(in) :: name
    call json%create_logical(p,val,to_unicode(name))
    end subroutine wrap_json_value_create_logical
Call graph
wrap_json_value_create_logical calls to_unicode, create_logical
to_unicode calls to_uni, to_uni_vec
json_value_create_logical calls json_value_create, to_logical
to_logical calls destroy_json_data
json_add_logical_by_path calls create_logical
json_value_add_logical calls create_logical
wrap_json_add_logical_by_path calls json_add_logical_by_path