wrap_json_value_create_integer – JSON-Fortran
wrap_json_value_create_integer Subroutine
Izaak Beekman
8 statements
Source File
private subroutine wrap_json_value_create_integer(json, p, val, name)
A wrapper procedure for json_value_create_integer so that create_integer method may be called with either a ‘DEFAULT’ or ‘ISO_10646’ character kind name actual argument.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
integer(kind=IK), intent(in) :: val
character(kind=CDK, len=*), intent(in) :: name
Calls
Called by
Source Code
    subroutine wrap_json_value_create_integer(json,p,val,name)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    integer(IK),intent(in)               :: val
    character(kind=CDK,len=*),intent(in) :: name
    call json%create_integer(p,val,to_unicode(name))
    end subroutine wrap_json_value_create_integer
Call graph
wrap_json_value_create_integer calls to_unicode, create_integer
to_unicode calls to_uni, to_uni_vec
json_value_create_integer calls json_value_create, to_integer
to_integer calls destroy_json_data
json_add_integer_by_path calls create_integer
json_value_add_integer calls create_integer
wrap_json_add_integer_by_path calls json_add_integer_by_path