wrap_json_get_path – JSON-Fortran
wrap_json_get_path Subroutine
16 statements
Source File
private subroutine wrap_json_get_path(json, p, path, found, use_alt_array_tokens, path_sep)
Wrapper for json_get_path where “path” and “path_sep” are kind=CDK.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
a JSON linked list object
character(kind=CDK, len=:), intent(out), allocatable :: path
path to the variable
logical(kind=LK), intent(out), optional :: found
true if there were no problems
logical(kind=LK), intent(in), optional :: use_alt_array_tokens
if true, then ‘()’ are used for array elements otherwise, ‘[]’ are used [default]
character(kind=CDK, len=1), intent(in), optional :: path_sep
character to use for path separator (default is ‘.’)
Calls
Called by
Source Code
    subroutine wrap_json_get_path(json, p, path, found, use_alt_array_tokens, path_sep)
    implicit none
    class(json_core),intent(inout)                    :: json
    type(json_value),pointer,intent(in)               :: p     !! a JSON linked list object
    character(kind=CDK,len=:),allocatable,intent(out) :: path  !! path to the variable
    logical(LK),intent(out),optional                  :: found !! true if there were no problems
    logical(LK),intent(in),optional :: use_alt_array_tokens    !! if true, then '()' are used
                                                               !! for array elements otherwise,
                                                               !! '[]' are used [default]
    character(kind=CDK,len=1),intent(in),optional :: path_sep  !! character to use for path
                                                               !! separator (default is '.')
    character(kind=CK,len=:),allocatable :: ck_path  !! path to the variable
    ! call the main routine:
    if (present(path_sep)) then
        call json%get_path(p,ck_path,found,use_alt_array_tokens,to_unicode(path_sep))
    else
        call json%get_path(p,ck_path,found,use_alt_array_tokens)
    end if
    ! from unicode:
    path = ck_path
    end subroutine wrap_json_get_path
Call graph
wrap_json_get_path calls to_unicode, get_path
to_unicode calls to_uni, to_uni_vec
json_get_path calls info, throw_exception, encode_rfc6901, integer_to_string, json_clear_exceptions
encode_rfc6901 calls replace_string
json_info calls throw_exception
json_info_by_path calls info, get
wrap_json_info_by_path calls to_unicode, info
wrap_json_throw_exception calls to_unicode, throw_exception
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls info, throw_exception, json_clear_exceptions, get
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
wrap_json_value_get_child_by_name calls to_unicode, get
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy
json_check_children_for_duplicate_keys calls get_path