wrap_json_file_get_alloc_string_vec – JSON-Fortran
wrap_json_file_get_alloc_string_vec Subroutine
11 statements
Source File
private subroutine wrap_json_file_get_alloc_string_vec(me, path, vec, ilen, found, default, default_ilen)
Alternate version of json_file_get_alloc_string_vec, where “path” is kind=CDK. This is just a wrapper for wrap_json_get_alloc_string_vec_by_path.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CDK, len=*), intent(in) :: path
the path to the variable
character(kind=CK, len=:), intent(out), dimension(:), allocatable :: vec
value vector
integer(kind=IK), intent(out), dimension(:), allocatable :: ilen
the actual length of each character string in the array
logical(kind=LK), intent(out), optional :: found
character(kind=CK, len=*), intent(in), optional, dimension(:) :: default
integer(kind=IK), intent(in), optional, dimension(:) :: default_ilen
the actual length of default
Calls
Called by
Source Code
    subroutine wrap_json_file_get_alloc_string_vec(me, path, vec, ilen, found, default, default_ilen)
    implicit none
    class(json_file),intent(inout)       :: me
    character(kind=CDK,len=*),intent(in) :: path !! the path to the variable
    character(kind=CK,len=:),dimension(:),allocatable,intent(out) :: vec  !! value vector
    integer(IK),dimension(:),allocatable,intent(out) :: ilen !! the actual length
                                                             !! of each character
                                                             !! string in the array
    logical(LK),intent(out),optional :: found
    character(kind=CK,len=*),dimension(:),intent(in),optional :: default
    integer(IK),dimension(:),intent(in),optional :: default_ilen !! the actual
                                                                 !! length of `default`
    call me%get(to_unicode(path), vec, ilen, found, default, default_ilen)
    end subroutine wrap_json_file_get_alloc_string_vec
Call graph
wrap_json_file_get_alloc_string_vec calls to_unicode, get
to_unicode calls to_uni, to_uni_vec
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
wrap_json_file_get_integer calls to_unicode, get
wrap_json_file_get_integer_vec calls to_unicode, get
wrap_json_file_get_logical calls to_unicode, get
wrap_json_file_get_logical_vec calls to_unicode, get
wrap_json_file_get_object calls to_unicode, get
wrap_json_file_get_real calls to_unicode, get
wrap_json_file_get_real32 calls to_unicode, get
wrap_json_file_get_real32_vec calls to_unicode, get
wrap_json_file_get_real_vec calls to_unicode, get
wrap_json_file_get_string calls to_unicode, get
wrap_json_file_get_string_vec calls to_unicode, get
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls get, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
wrap_json_get_alloc_string_vec_by_path calls to_unicode, get
wrap_json_get_array_by_path calls to_unicode, get
wrap_json_get_by_path calls to_unicode, get
wrap_json_get_integer_by_path calls to_unicode, get
wrap_json_get_integer_vec_by_path calls to_unicode, get
wrap_json_get_logical_by_path calls to_unicode, get
wrap_json_get_logical_vec_by_path calls to_unicode, get
wrap_json_get_real32_by_path calls to_unicode, get
wrap_json_get_real32_vec_by_path calls to_unicode, get
wrap_json_get_real_by_path calls to_unicode, get
wrap_json_get_real_vec_by_path calls to_unicode, get
wrap_json_get_string_by_path calls to_unicode, get
wrap_json_get_string_vec_by_path calls to_unicode, get
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, create_array, create_null, create_object, info, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls get, throw_exception, json_clear_exceptions, info
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
wrap_json_throw_exception calls to_unicode, throw_exception
json_value_add_string_name_ascii calls to_unicode, add
json_value_add_string_val_ascii calls to_unicode, add
json_value_add_string_vec_name_ascii calls to_unicode, add
json_value_add_string_vec_val_ascii calls to_unicode, add
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
wrap_json_value_get_child_by_name calls to_unicode, get
json_info calls throw_exception
json_info_by_path calls get, info
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
wrap_json_info_by_path calls to_unicode, info
wrap_json_value_create_array calls to_unicode, create_array
wrap_json_value_create_null calls to_unicode, create_null
wrap_json_value_create_object calls to_unicode, create_object
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy