wrap_json_value_create_real – JSON-Fortran
wrap_json_value_create_real Subroutine
Izaak Beekman
8 statements
Source File
private subroutine wrap_json_value_create_real(json, p, val, name)
A wrapper for json_value_create_real so that create_real method may be called with an actual argument corresponding to the dummy argument, name that may be of ‘DEFAULT’ or ‘ISO_10646’ character kind.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
real(kind=RK), intent(in) :: val
character(kind=CDK, len=*), intent(in) :: name
Calls
Source Code
    subroutine wrap_json_value_create_real(json,p,val,name)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    real(RK),intent(in)                  :: val
    character(kind=CDK,len=*),intent(in) :: name
    call json%create_real(p,val,to_unicode(name))
    end subroutine wrap_json_value_create_real
Call graph
wrap_json_value_create_real calls to_unicode, create_real
to_unicode calls to_uni, to_uni_vec
json_value_create_real32 calls create_real
wrap_json_value_create_real32 calls to_unicode, create_real