json_value_add_string_val_ascii – JSON-Fortran
json_value_add_string_val_ascii Subroutine
10 statements
Source File
private subroutine json_value_add_string_val_ascii(json, p, name, val, trim_str, adjustl_str)
Alternate version of json_value_add_string where val is kind=CDK.
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
character(kind=CK, len=*), intent(in) :: name
name of the variable
character(kind=CDK, len=*), intent(in) :: val
value
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for the val
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for the val
Calls
Source Code
    subroutine json_value_add_string_val_ascii(json, p, name, val, trim_str, adjustl_str)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer             :: p
    character(kind=CK, len=*),intent(in) :: name        !! name of the variable
    character(kind=CDK,len=*),intent(in) :: val         !! value
    logical(LK),intent(in),optional      :: trim_str    !! if TRIM() should be called for the `val`
    logical(LK),intent(in),optional      :: adjustl_str !! if ADJUSTL() should be called for the `val`
    call json%add(p, name, to_unicode(val), trim_str, adjustl_str)
    end subroutine json_value_add_string_val_ascii
Call graph
json_value_add_string_val_ascii calls to_unicode, add
to_unicode calls to_uni, to_uni_vec
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls info, throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_info calls throw_exception
json_info_by_path calls info, get
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_string calls destroy_json_data
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, get, flag_not_found, json_clear_exceptions
escape_string calls valid_json_hex
json_get_by_path_default calls add, throw_exception, json_value_create, to_array, to_null, json_clear_exceptions, string_to_integer, get_child, to_object
json_get_by_path_jsonpath_bracket calls add, throw_exception, json_value_create, to_null, json_clear_exceptions, string_to_integer, get_child, convert
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls create_array, create_null, info, throw_exception, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls info, throw_exception, get, json_clear_exceptions
to_object calls destroy_json_data
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy