json_file_get_root – JSON-Fortran
json_file_get_root Subroutine
Izaak Beekman
7/23/2015
6 statements
Source File
private subroutine json_file_get_root(me, p)
Get a json_value pointer to the JSON file root.
Note
This is equivalent to calling [[json_file]]%get('$',p)
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
type(json_value), intent(out), pointer :: p
pointer to the variable
Called by
Source Code
    subroutine json_file_get_root(me,p)
    implicit none
    class(json_file),intent(inout)       :: me
    type(json_value),pointer,intent(out) :: p      !! pointer to the variable
    p => me%p
    end subroutine json_file_get_root
Call graph
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get