wrap_json_file_rename – JSON-Fortran
wrap_json_file_rename Subroutine
Jacob Williams
8 statements
Source File
private subroutine wrap_json_file_rename(me, path, name, found)
Alternate version of json_file_rename, where “path” and “name” are kind=CDK.
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CDK, len=*), intent(in) :: path
the path to the variable
character(kind=CDK, len=*), intent(in) :: name
the new name
logical(kind=LK), intent(out), optional :: found
if the variable was found
Calls
Source Code
    subroutine wrap_json_file_rename(me,path,name,found)
    implicit none
    class(json_file),intent(inout)       :: me
    character(kind=CDK,len=*),intent(in) :: path   !! the path to the variable
    character(kind=CDK,len=*),intent(in) :: name   !! the new name
    logical(LK),intent(out),optional     :: found  !! if the variable was found
    call me%json_file_rename(to_unicode(path),to_unicode(name),found)
    end subroutine wrap_json_file_rename
Call graph
wrap_json_file_rename calls to_unicode, json_file_rename
to_unicode calls to_uni, to_uni_vec