wrap_json_file_add_double – JSON-Fortran
wrap_json_file_add_double Subroutine
Jacob Williams
9 statements
Source File
private subroutine wrap_json_file_add_double(me, path, val, found, was_created)
Alternate version of json_file_add_double, where "path" is kind=CDK.
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CDK,len=*), intent(in) :: path
the path to the variable
real(kind=RK), intent(in) :: val
value
logical(kind=LK), intent(out), optional :: found
if the variable was found
logical(kind=LK), intent(out), optional :: was_created
if the variable had to be created
Calls
Contents
Source Code
wrap_json_file_add_double
Source Code
    subroutine wrap_json_file_add_double(me,path,val,found,was_created)
    implicit none
    class(json_file),intent(inout)       :: me
    character(kind=CDK,len=*),intent(in) :: path         !! the path to the variable
    real(RK),intent(in)                  :: val          !! value
    logical(LK),intent(out),optional     :: found        !! if the variable was found
    logical(LK),intent(out),optional     :: was_created  !! if the variable had to be created
    call me%json_file_add_double(to_unicode(path),val,found,was_created)
    end subroutine wrap_json_file_add_double
Call graph
wrap_json_file_add_double calls to_unicode
to_unicode calls to_uni_vec, to_uni