json_core – JSON-Fortran
json_core Interface
3 statements
Source File
public interface json_core
Structure constructor to initialize a json_core object
Example
 type(json_file)  :: json_core
 json_core = json_core()
Calls
Module Procedures
private function initialize_json_core(verbose, compact_reals, print_signs, real_format, spaces_per_tab, strict_type_checking, trailing_spaces_significant, case_sensitive_keys, no_whitespace, unescape_strings, comment_char, path_mode, path_separator, compress_vectors, allow_duplicate_keys, escape_solidus, stop_on_error, null_to_real_mode, non_normal_mode, use_quiet_nan, strict_integer_type_checking, allow_trailing_comma, parser_mode, parser_initial_stack_size, parser_max_stack_size, string_to_real_mode, null_to_integer_mode, null_to_integer_value) result(json_core_object)
Author
Jacob Williams
Date
4/26/2016
Function constructor for a json_core. This is just a wrapper for json_initialize.
Read more…
Arguments
Type Intent Optional Attributes Name
logical(kind=LK), intent(in), optional :: verbose
mainly useful for debugging (default is false)
logical(kind=LK), intent(in), optional :: compact_reals
to compact the real number strings for output (default is true)
logical(kind=LK), intent(in), optional :: print_signs
always print numeric sign (default is false)
character(kind=CDK, len=*), intent(in), optional :: real_format
Real number format: ‘E’ [default], ‘*’, ‘G’, ‘EN’, or ‘ES’
integer(kind=IK), intent(in), optional :: spaces_per_tab
number of spaces per tab for indenting (default is 2)
logical(kind=LK), intent(in), optional :: strict_type_checking
if true, no integer, double, or logical type conversions are done for the get routines (default is false).
logical(kind=LK), intent(in), optional :: trailing_spaces_significant
for name and path comparisons, is trailing space to be considered significant. (default is false)
logical(kind=LK), intent(in), optional :: case_sensitive_keys
for name and path comparisons, are they case sensitive. (default is true)
logical(kind=LK), intent(in), optional :: no_whitespace
if true, printing the JSON structure is done without adding any non-significant spaces or linebreaks (default is false)
logical(kind=LK), intent(in), optional :: unescape_strings
If false, then the raw escaped string is returned from json_get_string and similar routines. If true [default], then the string is returned unescaped.
character(kind=CK, len=*), intent(in), optional :: comment_char
If present, these characters are used to denote comments in the JSON file, which will be ignored if present. Example: !, #, or /!#. Setting this to a blank string disables the ignoring of comments. (Default is /!#).
integer(kind=IK), intent(in), optional :: path_mode
How the path strings are interpreted in the get_by_path routines:
Read more…
character(kind=CK, len=1), intent(in), optional :: path_separator
The path separator to use in the “default” mode for the paths in the various get_by_path routines. Example: . [default] or %. Note: if path_mode/=1 then this is ignored.
logical(kind=LK), intent(in), optional :: compress_vectors
If true, then arrays of integers, nulls, doubles, and logicals are printed all on one line. [Note: no_whitespace will override this option if necessary]. (Default is False).
logical(kind=LK), intent(in), optional :: allow_duplicate_keys Read more…
logical(kind=LK), intent(in), optional :: escape_solidus
Note that this option does not affect parsing (both escaped and unescaped are still valid in all cases).
Read more…
logical(kind=LK), intent(in), optional :: stop_on_error
If an exception is raised, then immediately quit. (Default is False).
integer(kind=IK), intent(in), optional :: null_to_real_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: non_normal_mode
How to serialize NaN, Infinity, and -Infinity real values:
Read more…
logical(kind=LK), intent(in), optional :: use_quiet_nan Read more…
logical(kind=LK), intent(in), optional :: strict_integer_type_checking
(default is true)
Read more…
logical(kind=LK), intent(in), optional :: allow_trailing_comma
Allow a single trailing comma in arrays and objects. (default is true)
integer(kind=IK), intent(in), optional :: parser_mode
Which version of the JSON parser to use:
Read more…
integer(kind=IK), intent(in), optional :: parser_initial_stack_size
The initial stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 32)
integer(kind=IK), intent(in), optional :: parser_max_stack_size
The maximum stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 10000)
integer(kind=IK), intent(in), optional :: string_to_real_mode
Which implementation to use for converting strings to real values:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_value
The integer value to return when retrieving a null as an integer and null_to_integer_mode=3. (default is 0).
Return Value type(json_core)
Call graph
json_core calls initialize_json_core
initialize_json_core calls json_initialize
json_initialize calls throw_exception, integer_to_string, json_clear_exceptions
wrap_json_throw_exception calls throw_exception, to_unicode
to_unicode calls to_uni, to_uni_vec