json_file – JSON-Fortran
json_file Interface
Izaak Beekman
07/23/2015
3 statements
Source File
public interface json_file
Structure constructor to initialize a json_file object with an existing json_value object or a JSON string, and either the json_core settings or a json_core instance.
Example
 ...
 type(json_file) :: my_file
 type(json_value),pointer :: json_object
 type(json_core) :: json_core_object
 ...
 ! Construct a json_object:
 !could do this:
   my_file = json_file(json_object)
 !or:
   my_file = json_file(json_object,verbose=.true.)
 !or:
   my_file = json_file('{"x": [1]}',verbose=.true.)
 !or:
   my_file = json_file(json_object,json_core_object)
 !or:
   my_file = json_file('{"x": [1]}',json_core_object)
Calls
Module Procedures
private function initialize_json_file(p, verbose, compact_reals, print_signs, real_format, spaces_per_tab, strict_type_checking, trailing_spaces_significant, case_sensitive_keys, no_whitespace, unescape_strings, comment_char, path_mode, path_separator, compress_vectors, allow_duplicate_keys, escape_solidus, stop_on_error, null_to_real_mode, non_normal_mode, use_quiet_nan, strict_integer_type_checking, allow_trailing_comma, parser_mode, parser_initial_stack_size, parser_max_stack_size, string_to_real_mode, null_to_integer_mode, null_to_integer_value, nullify_pointer) result(file_object)
Author
Izaak Beekman
Date
07/23/2015
Cast a json_value object as a json_file object. It also calls the initialize() method.
Read more…
Arguments
Type Intent Optional Attributes Name
type(json_value), optional, pointer :: p
json_value object to cast as a json_file object. This will be nullified.
logical(kind=LK), intent(in), optional :: verbose
mainly useful for debugging (default is false)
logical(kind=LK), intent(in), optional :: compact_reals
to compact the real number strings for output (default is true)
logical(kind=LK), intent(in), optional :: print_signs
always print numeric sign (default is false)
character(kind=CDK, len=*), intent(in), optional :: real_format
Real number format: ‘E’ [default], ‘*’, ‘G’, ‘EN’, or ‘ES’
integer(kind=IK), intent(in), optional :: spaces_per_tab
number of spaces per tab for indenting (default is 2)
logical(kind=LK), intent(in), optional :: strict_type_checking
if true, no integer, double, or logical type conversions are done for the get routines (default is false).
logical(kind=LK), intent(in), optional :: trailing_spaces_significant
for name and path comparisons, is trailing space to be considered significant. (default is false)
logical(kind=LK), intent(in), optional :: case_sensitive_keys
for name and path comparisons, are they case sensitive. (default is true)
logical(kind=LK), intent(in), optional :: no_whitespace
if true, printing the JSON structure is done without adding any non-significant spaces or linebreaks (default is false)
logical(kind=LK), intent(in), optional :: unescape_strings
If false, then the raw escaped string is returned from json_get_string and similar routines. If true [default], then the string is returned unescaped.
character(kind=CK, len=*), intent(in), optional :: comment_char
If present, these characters are used to denote comments in the JSON file, which will be ignored if present. Example: !, #, or /!#. Setting this to a blank string disables the ignoring of comments. (Default is /!#).
integer(kind=IK), intent(in), optional :: path_mode
How the path strings are interpreted in the get_by_path routines:
Read more…
character(kind=CK, len=1), intent(in), optional :: path_separator
The path separator to use in the “default” mode for the paths in the various get_by_path routines. Example: . [default] or %. Note: if path_mode/=1 then this is ignored.
logical(kind=LK), intent(in), optional :: compress_vectors
If true, then arrays of integers, nulls, doubles, and logicals are printed all on one line. [Note: no_whitespace will override this option if necessary]. (Default is False).
logical(kind=LK), intent(in), optional :: allow_duplicate_keys Read more…
logical(kind=LK), intent(in), optional :: escape_solidus
Note that this option does not affect parsing (both escaped and unescaped are still valid in all cases).
Read more…
logical(kind=LK), intent(in), optional :: stop_on_error
If an exception is raised, then immediately quit. (Default is False).
integer(kind=IK), intent(in), optional :: null_to_real_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: non_normal_mode
How to serialize NaN, Infinity, and -Infinity real values:
Read more…
logical(kind=LK), intent(in), optional :: use_quiet_nan Read more…
logical(kind=LK), intent(in), optional :: strict_integer_type_checking
(default is true)
Read more…
logical(kind=LK), intent(in), optional :: allow_trailing_comma
Allow a single trailing comma in arrays and objects. (default is true)
integer(kind=IK), intent(in), optional :: parser_mode
Which version of the JSON parser to use:
Read more…
integer(kind=IK), intent(in), optional :: parser_initial_stack_size
The initial stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 32)
integer(kind=IK), intent(in), optional :: parser_max_stack_size
The maximum stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 10000)
integer(kind=IK), intent(in), optional :: string_to_real_mode
Which implementation to use for converting strings to real values:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_value
The integer value to return when retrieving a null as an integer and null_to_integer_mode=3. (default is 0).
logical(kind=LK), intent(in), optional :: nullify_pointer
if True, then p will be nullified if present. (default is True). Normally, this should be done, because the json_file will destroy the pointer when the class goes out of scope (causing p to be a dangling pointer). However, if the intent is to use p in a json_file and then call nullify and continue to use p, then this should be set to False.
Return Value type(json_file)
private function initialize_json_file_v2(json_value_object, json_core_object) result(file_object)
Author
Jacob Williams
Date
4/26/2016
Cast a json_value pointer and a json_core object as a json_file object.
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: json_value_object
type(json_core), intent(in) :: json_core_object
Return Value type(json_file)
private function initialize_json_file_from_string(str, verbose, compact_reals, print_signs, real_format, spaces_per_tab, strict_type_checking, trailing_spaces_significant, case_sensitive_keys, no_whitespace, unescape_strings, comment_char, path_mode, path_separator, compress_vectors, allow_duplicate_keys, escape_solidus, stop_on_error, null_to_real_mode, non_normal_mode, use_quiet_nan, strict_integer_type_checking, allow_trailing_comma, parser_mode, parser_initial_stack_size, parser_max_stack_size, string_to_real_mode, null_to_integer_mode, null_to_integer_value) result(file_object)
Author
Jacob Williams
Date
01/19/2019
Cast a JSON string as a json_file object. It also calls the initialize() method.
Read more…
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: str
string to load JSON data from
logical(kind=LK), intent(in), optional :: verbose
mainly useful for debugging (default is false)
logical(kind=LK), intent(in), optional :: compact_reals
to compact the real number strings for output (default is true)
logical(kind=LK), intent(in), optional :: print_signs
always print numeric sign (default is false)
character(kind=CDK, len=*), intent(in), optional :: real_format
Real number format: ‘E’ [default], ‘*’, ‘G’, ‘EN’, or ‘ES’
integer(kind=IK), intent(in), optional :: spaces_per_tab
number of spaces per tab for indenting (default is 2)
logical(kind=LK), intent(in), optional :: strict_type_checking
if true, no integer, double, or logical type conversions are done for the get routines (default is false).
logical(kind=LK), intent(in), optional :: trailing_spaces_significant
for name and path comparisons, is trailing space to be considered significant. (default is false)
logical(kind=LK), intent(in), optional :: case_sensitive_keys
for name and path comparisons, are they case sensitive. (default is true)
logical(kind=LK), intent(in), optional :: no_whitespace
if true, printing the JSON structure is done without adding any non-significant spaces or linebreaks (default is false)
logical(kind=LK), intent(in), optional :: unescape_strings
If false, then the raw escaped string is returned from json_get_string and similar routines. If true [default], then the string is returned unescaped.
character(kind=CK, len=*), intent(in), optional :: comment_char
If present, these characters are used to denote comments in the JSON file, which will be ignored if present. Example: !, #, or /!#. Setting this to a blank string disables the ignoring of comments. (Default is /!#).
integer(kind=IK), intent(in), optional :: path_mode
How the path strings are interpreted in the get_by_path routines:
Read more…
character(kind=CK, len=1), intent(in), optional :: path_separator
The path separator to use in the “default” mode for the paths in the various get_by_path routines. Example: . [default] or %. Note: if path_mode/=1 then this is ignored.
logical(kind=LK), intent(in), optional :: compress_vectors
If true, then arrays of integers, nulls, doubles, and logicals are printed all on one line. [Note: no_whitespace will override this option if necessary]. (Default is False).
logical(kind=LK), intent(in), optional :: allow_duplicate_keys Read more…
logical(kind=LK), intent(in), optional :: escape_solidus
Note that this option does not affect parsing (both escaped and unescaped are still valid in all cases).
Read more…
logical(kind=LK), intent(in), optional :: stop_on_error
If an exception is raised, then immediately quit. (Default is False).
integer(kind=IK), intent(in), optional :: null_to_real_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: non_normal_mode
How to serialize NaN, Infinity, and -Infinity real values:
Read more…
logical(kind=LK), intent(in), optional :: use_quiet_nan Read more…
logical(kind=LK), intent(in), optional :: strict_integer_type_checking
(default is true)
Read more…
logical(kind=LK), intent(in), optional :: allow_trailing_comma
Allow a single trailing comma in arrays and objects. (default is true)
integer(kind=IK), intent(in), optional :: parser_mode
Which version of the JSON parser to use:
Read more…
integer(kind=IK), intent(in), optional :: parser_initial_stack_size
The initial stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 32)
integer(kind=IK), intent(in), optional :: parser_max_stack_size
The maximum stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 10000)
integer(kind=IK), intent(in), optional :: string_to_real_mode
Which implementation to use for converting strings to real values:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_value
The integer value to return when retrieving a null as an integer and null_to_integer_mode=3. (default is 0).
Return Value type(json_file)
private function wrap_initialize_json_file_from_string(str, verbose, compact_reals, print_signs, real_format, spaces_per_tab, strict_type_checking, trailing_spaces_significant, case_sensitive_keys, no_whitespace, unescape_strings, comment_char, path_mode, path_separator, compress_vectors, allow_duplicate_keys, escape_solidus, stop_on_error, null_to_real_mode, non_normal_mode, use_quiet_nan, strict_integer_type_checking, allow_trailing_comma, parser_mode, parser_initial_stack_size, parser_max_stack_size, string_to_real_mode, null_to_integer_mode, null_to_integer_value) result(file_object)
Alternate version of initialize_json_file_from_string, where “str” is kind=CDK.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: str
string to load JSON data from
logical(kind=LK), intent(in), optional :: verbose
mainly useful for debugging (default is false)
logical(kind=LK), intent(in), optional :: compact_reals
to compact the real number strings for output (default is true)
logical(kind=LK), intent(in), optional :: print_signs
always print numeric sign (default is false)
character(kind=CDK, len=*), intent(in), optional :: real_format
Real number format: ‘E’ [default], ‘*’, ‘G’, ‘EN’, or ‘ES’
integer(kind=IK), intent(in), optional :: spaces_per_tab
number of spaces per tab for indenting (default is 2)
logical(kind=LK), intent(in), optional :: strict_type_checking
if true, no integer, double, or logical type conversions are done for the get routines (default is false).
logical(kind=LK), intent(in), optional :: trailing_spaces_significant
for name and path comparisons, is trailing space to be considered significant. (default is false)
logical(kind=LK), intent(in), optional :: case_sensitive_keys
for name and path comparisons, are they case sensitive. (default is true)
logical(kind=LK), intent(in), optional :: no_whitespace
if true, printing the JSON structure is done without adding any non-significant spaces or linebreaks (default is false)
logical(kind=LK), intent(in), optional :: unescape_strings
If false, then the raw escaped string is returned from json_get_string and similar routines. If true [default], then the string is returned unescaped.
character(kind=CK, len=*), intent(in), optional :: comment_char
If present, these characters are used to denote comments in the JSON file, which will be ignored if present. Example: !, #, or /!#. Setting this to a blank string disables the ignoring of comments. (Default is /!#).
integer(kind=IK), intent(in), optional :: path_mode
How the path strings are interpreted in the get_by_path routines:
Read more…
character(kind=CK, len=1), intent(in), optional :: path_separator
The path separator to use in the “default” mode for the paths in the various get_by_path routines. Example: . [default] or %. Note: if path_mode/=1 then this is ignored.
logical(kind=LK), intent(in), optional :: compress_vectors
If true, then arrays of integers, nulls, doubles, and logicals are printed all on one line. [Note: no_whitespace will override this option if necessary]. (Default is False).
logical(kind=LK), intent(in), optional :: allow_duplicate_keys Read more…
logical(kind=LK), intent(in), optional :: escape_solidus
Note that this option does not affect parsing (both escaped and unescaped are still valid in all cases).
Read more…
logical(kind=LK), intent(in), optional :: stop_on_error
If an exception is raised, then immediately quit. (Default is False).
integer(kind=IK), intent(in), optional :: null_to_real_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: non_normal_mode
How to serialize NaN, Infinity, and -Infinity real values:
Read more…
logical(kind=LK), intent(in), optional :: use_quiet_nan Read more…
logical(kind=LK), intent(in), optional :: strict_integer_type_checking
(default is true)
Read more…
logical(kind=LK), intent(in), optional :: allow_trailing_comma
Allow a single trailing comma in arrays and objects. (default is true)
integer(kind=IK), intent(in), optional :: parser_mode
Which version of the JSON parser to use:
Read more…
integer(kind=IK), intent(in), optional :: parser_initial_stack_size
The initial stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 32)
integer(kind=IK), intent(in), optional :: parser_max_stack_size
The maximum stack size (in number of elements) to use when parser_mode=2 (non-recursive parser). (default is 10000)
integer(kind=IK), intent(in), optional :: string_to_real_mode
Which implementation to use for converting strings to real values:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_mode
if strict_type_checking=false:
Read more…
integer(kind=IK), intent(in), optional :: null_to_integer_value
The integer value to return when retrieving a null as an integer and null_to_integer_mode=3. (default is 0).
Return Value type(json_file)
private function initialize_json_file_from_string_v2(str, json_core_object) result(file_object)
Author
Jacob Williams
Date
1/19/2019
Cast a JSON string and a json_core object as a json_file object.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: str
string to load JSON data from
type(json_core), intent(in) :: json_core_object
Return Value type(json_file)
private function wrap_initialize_json_file_from_string_v2(str, json_core_object) result(file_object)
Alternate version of initialize_json_file_from_string_v2, where “str” is kind=CDK.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: str
string to load JSON data from
type(json_core), intent(in) :: json_core_object
Return Value type(json_file)
Call graph
json_file calls initialize_json_file, initialize_json_file_from_string, initialize_json_file_from_string_v2, initialize_json_file_v2, wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
initialize_json_file calls initialize
initialize_json_file_from_string calls deserialize, initialize
initialize_json_file_from_string_v2 calls deserialize
wrap_initialize_json_file_from_string calls initialize_json_file_from_string, to_unicode
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2, to_unicode
to_unicode calls to_uni, to_uni_vec
initialize_json_core_in_file calls json_initialize
json_file_load_from_string calls deserialize, json_file_destroy
wrap_json_file_load_from_string calls to_unicode, deserialize
json_file_destroy calls destroy
json_initialize calls throw_exception, integer_to_string, json_clear_exceptions
json_parse_string calls json_initialize, throw_exception, annotate_invalid_json, json_check_all_for_duplicate_keys, json_parse_end, json_prepare_parser, json_value_create
wrap_json_parse_string calls to_unicode, deserialize
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
json_check_all_for_duplicate_keys calls json_traverse
json_parse_end calls throw_exception, pop_char
json_value_destroy calls destroy, destroy_json_data
wrap_json_throw_exception calls to_unicode, throw_exception
json_traverse calls throw_exception