operator(==) – JSON-Fortran
operator(==) Interface
3 statements
Source File
public interface operator(==)
Provide a string == operator that works with mixed kinds
Calls
Module Procedures
private pure elemental function ucs4_comp_default(ucs4_str, def_str) result(res)
Author
Izaak Beekman
CK==CDK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: ucs4_str
character(kind=CDK, len=*), intent(in) :: def_str
Return Value logical(kind=LK)
private pure elemental function default_comp_ucs4(def_str, ucs4_str) result(res)
Author
Izaak Beekman
CDK==CK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: def_str
character(kind=CK, len=*), intent(in) :: ucs4_str
Return Value logical(kind=LK)
Call graph
operator(==) calls default_comp_ucs4, ucs4_comp_default
default_comp_ucs4 calls to_unicode
ucs4_comp_default calls to_unicode
to_unicode calls to_uni, to_uni_vec