operator(//) – JSON-Fortran
operator(//) Interface
3 statements
Source File
public interface operator(//)
Provide a means to convert to UCS4 while concatenating UCS4 and default strings
Calls
Contents
Module Procedures
ucs4_join_default default_join_ucs4
Module Procedures
private pure function ucs4_join_default(ucs4_str, def_str) result(res)
Author
Izaak Beekman
CK//CDK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: ucs4_str
character(kind=CDK, len=*), intent(in) :: def_str
Return Value character(kind=CK, len=len=(len(ucs4_str)+len(def_str)))
private pure function default_join_ucs4(def_str, ucs4_str) result(res)
Author
Izaak Beekman
CDK//CK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: def_str
character(kind=CK, len=*), intent(in) :: ucs4_str
Return Value character(kind=CK, len=len=(len(def_str)+len(ucs4_str)))
Call graph
operator(SLASHSLASH) calls default_join_ucs4, ucs4_join_default
default_join_ucs4 calls to_unicode
ucs4_join_default calls to_unicode
to_unicode calls to_uni, to_uni_vec