operator(/=) – JSON-Fortran
operator(/=) Interface
3 statements
Source File
public interface operator(/=)
Provide a string /= operator that works with mixed kinds
Calls
Contents
Module Procedures
ucs4_neq_default default_neq_ucs4
Module Procedures
private pure elemental function ucs4_neq_default(ucs4_str, def_str) result(res)
Author
Jacob Williams
CK/=CDK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: ucs4_str
character(kind=CDK, len=*), intent(in) :: def_str
Return Value logical(kind=LK)
private pure elemental function default_neq_ucs4(def_str, ucs4_str) result(res)
Author
Jacob Williams
CDK/=CK operator.
Arguments
Type Intent Optional Attributes Name
character(kind=CDK, len=*), intent(in) :: def_str
character(kind=CK, len=*), intent(in) :: ucs4_str
Return Value logical(kind=LK)
Call graph
operator(SLASH=) calls default_neq_ucs4, ucs4_neq_default
default_neq_ucs4 calls to_unicode
ucs4_neq_default calls to_unicode
to_unicode calls to_uni, to_uni_vec