to_real – JSON-Fortran
to_real Subroutine
Jacob Williams
16 statements
Source File
private subroutine to_real(json, p, val, name)
Change the json_value variable to a real.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), pointer :: p
real(kind=RK), intent(in), optional :: val
if the value is also to be set (if not present, then 0.0_rk is used).
character(kind=CK, len=*), intent(in), optional :: name
if the name is also to be changed.
Calls
Called by
Source Code
    subroutine to_real(json,p,val,name)
    implicit none
    class(json_core),intent(inout)               :: json
    type(json_value),pointer                     :: p
    real(RK),intent(in),optional                 :: val   !! if the value is also to be set
                                                          !! (if not present, then 0.0_rk is used).
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    !set type and value:
    call destroy_json_data(p)
    p%var_type = json_real
    allocate(p%dbl_value)
    if (present(val)) then
        p%dbl_value = val
    else
        p%dbl_value = 0.0_RK    !default value
    end if
    !name:
    if (present(name)) call json%rename(p,name)
    end subroutine to_real
Call graph
to_real calls destroy_json_data
json_update_real calls to_real
json_value_create_real calls to_real
parse_number calls to_real
parse_value calls parse_number, parse_array, parse_object
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_parse_file calls parse_value
json_parse_string calls parse_value
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
parse_array calls parse_value
parse_object calls parse_value, parse_object
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
json_file_load calls load
json_file_load_from_string calls deserialize
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2