json_file_move_pointer – JSON-Fortran
json_file_move_pointer Subroutine
Jacob Williams
12/5/2014
16 statements
Source File
private subroutine json_file_move_pointer(to, from)
Move the json_value pointer from one json_file to another. The “from” pointer is then nullified, but not destroyed.
Note
If “from%p” is not associated, then an error is thrown.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: to
class(json_file), intent(inout) :: from
Calls
Source Code
    subroutine json_file_move_pointer(to,from)
    implicit none
    class(json_file),intent(inout) :: to
    class(json_file),intent(inout) :: from
    if (associated(from%p)) then
        if (from%failed()) then
            !Don't get the data if the FROM file has an
            !active exception, since it may not be valid.
            call to%core%throw_exception('Error in json_file_move_pointer: '//&
                                         'error exception in FROM file.')
        else
            call to%initialize()  !initialize and clear any exceptions that may be present
            to%p => from%p
            nullify(from%p)
        end if
    else
        call to%core%throw_exception('Error in json_file_move_pointer: '//&
                                     'pointer is not associated.')
    end if
    end subroutine json_file_move_pointer
Call graph
json_file_move_pointer calls initialize, throw_exception, json_file_failed
json_file_failed calls json_failed
initialize_json_core_in_file calls json_initialize
json_initialize calls throw_exception, integer_to_string, json_clear_exceptions