json_rename_by_path_path_ascii – JSON-Fortran
json_rename_by_path_path_ascii Subroutine
9 statements
Source File
private subroutine json_rename_by_path_path_ascii(json, me, path, name, found)
Alternate version of json_rename_by_path, where “path” is kind=CDK
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: me
character(kind=CDK, len=*), intent(in) :: path
character(kind=CK, len=*), intent(in) :: name
logical(kind=LK), intent(out), optional :: found
Calls
Source Code
    subroutine json_rename_by_path_path_ascii(json, me, path, name, found)
    implicit none
    class(json_core),intent(inout)        :: json
    type(json_value),pointer,intent(in)   :: me
    character(kind=CDK,len=*),intent(in)  :: path
    character(kind=CK,len=*),intent(in)   :: name
    logical(LK),intent(out),optional      :: found
    call json%rename(me,to_unicode(path),name,found)
    end subroutine json_rename_by_path_path_ascii
Call graph
json_rename_by_path_path_ascii calls to_unicode
to_unicode calls to_uni, to_uni_vec