json_parse_file – JSON-Fortran
json_parse_file Subroutine
53 statements
Source File
private subroutine json_parse_file(json, file, p, unit)
Parse the JSON file and populate the json_value tree.
Inputs
The inputs can be:
file & unit : the specified unit is used to read JSON from file. [note if unit is already open, then the filename is ignored]
file : JSON is read from file using internal unit number
Example
    type(json_core) :: json
    type(json_value),pointer :: p
    call json%load(file='myfile.json', p=p)
History
Jacob Williams : 01/13/2015 : added read from string option.
Izaak Beekman : 03/08/2015 : moved read from string to separate subroutine, and error annotation to separate subroutine.
Note
When calling this routine, any exceptions thrown from previous calls will automatically be cleared.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
character(kind=CDK, len=*), intent(in) :: file
JSON file name
type(json_value), pointer :: p
output structure
integer(kind=IK), intent(in), optional :: unit
file unit number (/= 0)
Calls
Called by
Source Code
    subroutine json_parse_file(json, file, p, unit)
    implicit none
    class(json_core),intent(inout)       :: json
    character(kind=CDK,len=*),intent(in) :: file  !! JSON file name
    type(json_value),pointer             :: p     !! output structure
    integer(IK),intent(in),optional      :: unit  !! file unit number (/= 0)
    integer(IK) :: iunit   !! file unit actually used
    integer(IK) :: istat   !! iostat flag
    logical(LK) :: is_open !! if the file is already open
    logical(LK) :: has_duplicate  !! if checking for duplicate keys
    character(kind=CK,len=:),allocatable :: path !! path to any duplicate key
    ! clear any exceptions and initialize:
    call json%initialize()
    call json%prepare_parser()
    if ( present(unit) ) then
        if (unit==0) then
            call json%throw_exception('Error in json_parse_file: unit number must not be 0.')
            return
        end if
        iunit = unit
        ! check to see if the file is already open
        ! if it is, then use it, otherwise open the file with the name given.
        inquire(unit=iunit, opened=is_open, iostat=istat)
        if (istat==0 .and. .not. is_open) then
           ! open the file
            open (  unit        = iunit, &
                    file        = file, &
                    status      = 'OLD', &
                    action      = 'READ', &
                    form        = form_spec, &
                    access      = access_spec, &
                    iostat      = istat &
                    FILE_ENCODING )
        else
            ! if the file is already open, then we need to make sure
            ! that it is open with the correct form/access/etc...
        end if
    else
        ! open the file with a new unit number:
        open (  newunit     = iunit, &
                file        = file, &
                status      = 'OLD', &
                action      = 'READ', &
                form        = form_spec, &
                access      = access_spec, &
                iostat      = istat &
                FILE_ENCODING )
    end if
    if (istat==0) then
        if (use_unformatted_stream) then
            ! save the file size to be read:
            inquire(unit=iunit, size=json%filesize, iostat=istat)
        end if
        ! create the value and associate the pointer
        call json_value_create(p)
        ! Note: the name of the root json_value doesn't really matter,
        !  but we'll allocate something here just in case.
        p%name = trim(file)  !use the file name
        ! parse as a value
        call json%parse_value(unit=iunit, str=CK_'', value=p)
        call json%parse_end(unit=iunit, str=CK_'')
        ! check for errors:
        if (json%exception_thrown) then
            call json%annotate_invalid_json(iunit,CK_'')
        else
            if (.not. json%allow_duplicate_keys) then
                call json%check_for_duplicate_keys(p,has_duplicate,path=path)
                if (.not. json%exception_thrown) then
                    if (has_duplicate) then
                        call json%throw_exception('Error in json_parse_file: '//&
                                                  'Duplicate key found: '//path)
                    end if
                end if
            end if
        end if
        ! close the file:
        close(unit=iunit, iostat=istat)
    else
        call json%throw_exception('Error in json_parse_file: Error opening file: '//trim(file))
        nullify(p)
    end if
    end subroutine json_parse_file
Call graph
json_parse_file calls throw_exception, annotate_invalid_json, json_check_all_for_duplicate_keys, json_initialize, json_parse_end, json_prepare_parser, json_value_create, parse_value
annotate_invalid_json calls get_current_line_from_file_sequential, get_current_line_from_file_stream, integer_to_string
json_check_all_for_duplicate_keys calls json_traverse
json_initialize calls throw_exception, integer_to_string, json_clear_exceptions
json_parse_end calls throw_exception, pop_char
parse_value calls throw_exception, parse_array, parse_for_chars, parse_number, parse_object, parse_string, pop_char, push_char, to_array, to_logical, to_null, to_object, to_string
json_traverse calls throw_exception
parse_array calls throw_exception, json_value_create, parse_value, pop_char, add, destroy
parse_for_chars calls throw_exception, pop_char
parse_number calls json_clear_exceptions, pop_char, push_char, string_to_dble, string_to_int, to_integer, to_real
parse_object calls throw_exception, json_value_create, parse_value, parse_object, parse_string, pop_char, add, destroy
parse_string calls throw_exception, pop_char, unescape_string
push_char calls throw_exception, integer_to_string
to_array calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_string calls destroy_json_data
string_to_dble calls throw_exception, string_to_real
string_to_int calls throw_exception, string_to_integer
to_integer calls destroy_json_data
to_real calls destroy_json_data
unescape_string calls valid_json_hex
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception, info
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_destroy calls destroy, destroy_json_data
json_info calls throw_exception
json_info_by_path calls info, get
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_value_create, json_clear_exceptions, to_array, to_null, to_object, add, string_to_integer, get_child
json_get_by_path_jsonpath_bracket calls throw_exception, json_value_create, json_clear_exceptions, to_null, add, string_to_integer, get_child, convert
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, create_array, create_null, info, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, json_clear_exceptions, info, get
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_file_load calls load