json_get_alloc_string_vec – JSON-Fortran
json_get_alloc_string_vec Subroutine
Jacob Williams
12/16/2016
49 statements
Source File
private subroutine json_get_alloc_string_vec(json, me, vec, ilen)
Get a string vector from a json_value. This is an alternate version of json_get_string_vec. This one returns an allocatable length character (where the string length is the maximum length of any element in the array). It also returns an integer array of the actual sizes of the strings in the JSON structure.
Note
This is somewhat inefficient since it does cycle through the array twice.
Warning
The allocation of vec doesn’t work with gfortran 4.9 or 5 due to compiler bugs
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: me
character(kind=CK, len=:), intent(out), dimension(:), allocatable :: vec
integer(kind=IK), intent(out), dimension(:), allocatable :: ilen
the actual length of each character string in the array
Calls
Called by
Source Code
    subroutine json_get_alloc_string_vec(json, me, vec, ilen)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer,intent(in)  :: me
    character(kind=CK,len=:),dimension(:),allocatable,intent(out) :: vec
    integer(IK),dimension(:),allocatable,intent(out) :: ilen !! the actual length
                                                             !! of each character
                                                             !! string in the array
    logical(LK) :: initialized !! if the output array has been sized
    integer(IK) :: max_len     !! the length of the longest string in the array
    if ( json%exception_thrown ) return
    ! check for 0-length arrays first:
    select case (me%var_type)
    case (json_array)
        if (json%count(me)==0) then
            allocate(character(kind=CK,len=0) :: vec(0))
            allocate(ilen(0))
            return
        end if
    end select
    initialized = .false.
    call json%string_info(me,ilen=ilen,max_str_len=max_len)
    if (.not. json%exception_thrown) then
        ! now get each string using the callback function:
        call json%get(me, array_callback=get_chars_from_array)
    end if
    if (json%exception_thrown) then
        if (allocated(vec))  deallocate(vec)
        if (allocated(ilen)) deallocate(ilen)
    end if
    contains
        subroutine get_chars_from_array(json, element, i, count)
        !! callback function for chars
        implicit none
        class(json_core),intent(inout)      :: json
        type(json_value),pointer,intent(in) :: element
        integer(IK),intent(in)              :: i        !! index
        integer(IK),intent(in)              :: count    !! size of array
        character(kind=CK,len=:),allocatable :: cval  !! for getting string
        !size the output array:
        if (.not. initialized) then
            ! string length long enough to hold the longest one
            ! Note that this doesn't work with gfortran 4.9 or 5.
            allocate( character(kind=CK,len=max_len) :: vec(count) )
            initialized = .true.
        end if
        !populate the elements:
        call json%get(element, value=cval)
        if (allocated(cval)) then
            vec(i)  = cval
            ilen(i) = len(cval)  ! return the actual length
            deallocate(cval)
        else
            vec(i)  = CK_''
            ilen(i) = 0
        end if
        end subroutine get_chars_from_array
    end subroutine json_get_alloc_string_vec
Call graph
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_array calls throw_exception
json_get_array_by_path calls get, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical calls throw_exception
json_get_logical_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_real_vec calls get
json_get_real_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string calls throw_exception, escape_string, integer_to_string, real_to_string
json_get_string_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_get_string_vec calls get
json_get_string_vec_by_path calls get, throw_exception, flag_not_found, json_clear_exceptions
json_string_info calls get, info, throw_exception, json_clear_exceptions
escape_string calls valid_json_hex
json_get_by_path_default calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, json_value_create, to_array, to_null, to_object
json_get_by_path_jsonpath_bracket calls throw_exception, json_clear_exceptions, string_to_integer, add, get_child, convert, json_value_create, to_null
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls info, throw_exception, create_array, create_null, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_info calls throw_exception
json_info_by_path calls get, info
to_array calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls info, throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_array calls json_value_create, to_array
json_value_create_null calls json_value_create, to_null
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_value_destroy calls destroy_json_data, destroy
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_update_integer calls get, info, add_by_path
json_update_logical calls get, info, add_by_path
json_update_real calls get, info, add_by_path
json_update_string calls get, info, add_by_path
json_valid_path calls get
json_value_remove_if_present calls get
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
json_add_integer_by_path calls info, create
json_add_integer_vec_by_path calls info, add, create
json_add_logical_by_path calls info, create
json_add_logical_vec_by_path calls info, add, create
json_add_member_by_path calls info, create
json_add_real_by_path calls info, create
json_add_real_vec_by_path calls info, add, create
json_add_string_by_path calls info, create
json_add_string_vec_by_path calls info, add, create
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_reverse calls info
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_value_print calls json_is_vector, json_value_print
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_check_children_for_duplicate_keys calls get_path
json_create_by_path calls json_get_by_path_jsonpath_bracket, json_get_by_path_default
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_print_to_unit calls json_value_print
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
json_value_to_string calls json_value_print
parse_array calls add, parse_value
parse_object calls add, parse_object, parse_value
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
assign_json_file_to_string calls json_value_to_string
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_file_print_to_string calls json_value_to_string
parse_value calls parse_array, parse_object
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_parse_file calls parse_value
json_parse_string calls parse_value
wrap_json_create_by_path calls create
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2