parse_array – JSON-Fortran
parse_array Subroutine
42 statements
Source File
private recursive subroutine parse_array(json, unit, str, array)
Core parsing routine.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK, len=*), intent(in) :: str
JSON string (if parsing from a string)
type(json_value), pointer :: array
Calls
Called by
Source Code
    recursive subroutine parse_array(json, unit, str, array)
    implicit none
    class(json_core),intent(inout)      :: json
    integer(IK),intent(in)              :: unit   !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str    !! JSON string (if parsing from a string)
    type(json_value),pointer            :: array
    type(json_value),pointer :: element !! temp variable for array element
    logical(LK)              :: eof     !! end of file flag
    character(kind=CK,len=1) :: c       !! character returned by [[pop_char]]
    logical(LK) :: expecting_next_element !! to check for trailing delimiters
    expecting_next_element = .false.
    do
        if (json%exception_thrown) exit
        ! try to parse an element value
        nullify(element)
        call json_value_create(element)
        call json%parse_value(unit, str, element)
        if (json%exception_thrown) then
            if (associated(element)) call json%destroy(element)
            exit
        end if
        ! parse value will deallocate an empty array value
        if (associated(element)) then
            expecting_next_element = .false.
            call json%add(array, element)
        end if
        ! popped the next character
        call json%pop_char(unit, str=str, eof=eof, skip_ws=.true., &
                           skip_comments=json%allow_comments, popped=c)
        if (eof) then
            ! The file ended before array was finished:
            call json%throw_exception('Error in parse_array: '//&
                                      'End of file encountered when parsing an array.')
            exit
        else if (delimiter == c) then
            ! parse the next element
            expecting_next_element = .true.
            cycle
        else if (end_array == c) then
            ! end of array
            if (expecting_next_element .and. .not. json%allow_trailing_comma) then
                ! this is a dangling comma.
                call json%throw_exception('Error in parse_array: '//&
                                          'Dangling comma when parsing an array.')
            end if
            exit
        else
            call json%throw_exception('Error in parse_array: '//&
                                      'Unexpected character encountered when parsing array.')
            exit
        end if
    end do
    end subroutine parse_array
Call graph
parse_array calls add, destroy, throw_exception, json_value_create, parse_value, pop_char
parse_value calls parse_array, throw_exception, pop_char, parse_for_chars, parse_number, parse_object, parse_string, push_char, to_array, to_logical, to_null, to_object, to_string
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception, info
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_destroy calls destroy, destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls pop_char, push_char, json_clear_exceptions, string_to_dble, string_to_int, to_integer, to_real
parse_object calls add, destroy, throw_exception, json_value_create, parse_value, pop_char, parse_object, parse_string
parse_string calls throw_exception, pop_char, unescape_string
push_char calls throw_exception, integer_to_string
to_array calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_string calls destroy_json_data
string_to_dble calls throw_exception, string_to_real
string_to_int calls throw_exception, string_to_integer
to_integer calls destroy_json_data
to_real calls destroy_json_data
unescape_string calls valid_json_hex
json_info calls throw_exception
json_info_by_path calls info, get
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
escape_string calls valid_json_hex
json_get_by_path_default calls add, throw_exception, json_value_create, to_array, to_null, to_object, json_clear_exceptions, string_to_integer, get_child
json_get_by_path_jsonpath_bracket calls add, throw_exception, json_value_create, to_null, json_clear_exceptions, string_to_integer, get_child, convert
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, create_array, create_null, info, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, info, json_clear_exceptions, get
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_parse_file calls parse_value
json_parse_string calls parse_value
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2