parse_object – JSON-Fortran
parse_object Subroutine
70 statements
Source File
private recursive subroutine parse_object(json, unit, str, parent, expecting_next_element)
Core parsing routine.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK, len=*), intent(in) :: str
JSON string (if parsing from a string)
type(json_value), pointer :: parent
the parsed object will be added as a child of this
logical(kind=LK), intent(in) :: expecting_next_element
if true, this object is preceeded by a comma, so we expect a valid object to exist. used to check for trailing delimiters.
Calls
Called by
Source Code
    recursive subroutine parse_object(json, unit, str, parent, expecting_next_element)
    implicit none
    class(json_core),intent(inout)      :: json
    integer(IK),intent(in)              :: unit    !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str     !! JSON string (if parsing from a string)
    type(json_value),pointer            :: parent  !! the parsed object will be added as a child of this
    logical(LK),intent(in) :: expecting_next_element !! if true, this object is preceeded by a comma, so
                                                     !! we expect a valid object to exist. used to check
                                                     !! for trailing delimiters.
    type(json_value),pointer :: pair  !! temp variable
    logical(LK)              :: eof   !! end of file flag
    character(kind=CK,len=1) :: c     !! character returned by [[pop_char]]
#if defined __GFORTRAN__
    character(kind=CK,len=:),allocatable :: tmp  !! this is a work-around for a bug
                                                 !! in the gfortran 4.9 compiler.
#endif
    if (.not. json%exception_thrown) then
        !the routine is being called incorrectly.
        if (.not. associated(parent)) then
            call json%throw_exception('Error in parse_object: parent pointer not associated.')
        end if
        nullify(pair)    !probably not necessary
        ! pair name
        call json%pop_char(unit, str=str, eof=eof, skip_ws=.true., &
                           skip_comments=json%allow_comments, popped=c)
        if (eof) then
            call json%throw_exception('Error in parse_object:'//&
                                      ' Unexpected end of file while parsing start of object.')
            return
        else if (end_object == c) then
            ! end of an empty object
            if (expecting_next_element .and. .not. json%allow_trailing_comma) then
                ! this is a dangling comma.
                call json%throw_exception('Error in parse_object: '//&
                                          'Dangling comma when parsing an object.')
            end if
            return
        else if (quotation_mark == c) then
            call json_value_create(pair)
#if defined __GFORTRAN__
            call json%parse_string(unit,str,tmp)   ! write to a tmp variable because of
            pair%name = tmp                        ! a bug in 4.9 gfortran compiler.
            deallocate(tmp)
#else
            call json%parse_string(unit,str,pair%name)
#endif
            if (json%exception_thrown) then
                call json%destroy(pair)
                return
            end if
        else
            call json%throw_exception('Error in parse_object: Expecting string: "'//c//'"')
            return
        end if
        ! pair value
        call json%pop_char(unit, str=str, eof=eof, skip_ws=.true., &
                           skip_comments=json%allow_comments, popped=c)
        if (eof) then
            call json%destroy(pair)
            call json%throw_exception('Error in parse_object:'//&
                                      ' Unexpected end of file while parsing object member.')
            return
        else if (colon_char == c) then
            ! parse the value
            call json%parse_value(unit, str, pair)
            if (json%exception_thrown) then
                call json%destroy(pair)
                return
            else
                call json%add(parent, pair)
            end if
        else
            call json%destroy(pair)
            call json%throw_exception('Error in parse_object:'//&
                                      ' Expecting : and then a value: '//c)
            return
        end if
        ! another possible pair
        call json%pop_char(unit, str=str, eof=eof, skip_ws=.true., &
                           skip_comments=json%allow_comments, popped=c)
        if (eof) then
            call json%throw_exception('Error in parse_object: '//&
                                      'End of file encountered when parsing an object')
            return
        else if (delimiter == c) then
            ! read the next member
            call json%parse_object(unit = unit, str=str, parent = parent, &
                                   expecting_next_element=.true.)
        else if (end_object == c) then
            ! end of object
            return
        else
            call json%throw_exception('Error in parse_object: Expecting end of object: '//c)
            return
        end if
    end if
    end subroutine parse_object
Call graph
parse_object calls parse_object, add, destroy, throw_exception, json_value_create, parse_string, parse_value, pop_char
parse_string calls throw_exception, pop_char, unescape_string
parse_value calls parse_object, throw_exception, parse_string, pop_char, parse_array, parse_for_chars, parse_number, push_char, to_array, to_logical, to_null, to_object, to_string
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception, info
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_destroy calls destroy, destroy_json_data
parse_array calls add, destroy, throw_exception, json_value_create, parse_value, pop_char
parse_for_chars calls throw_exception, pop_char
parse_number calls pop_char, push_char, json_clear_exceptions, string_to_dble, string_to_int, to_integer, to_real
push_char calls throw_exception, integer_to_string
to_array calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_string calls destroy_json_data
unescape_string calls valid_json_hex
string_to_dble calls throw_exception, string_to_real
string_to_int calls throw_exception, string_to_integer
to_integer calls destroy_json_data
to_real calls destroy_json_data
json_info calls throw_exception
json_info_by_path calls info, get
json_value_create_array calls json_value_create, to_array
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls json_value_create, to_logical
json_value_create_null calls json_value_create, to_null
json_value_create_real32 calls create_real
json_value_create_string calls json_value_create, to_string
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, json_clear_exceptions, get
json_get_by_path calls throw_exception, integer_to_string, json_clear_exceptions, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_integer calls throw_exception, string_to_integer
json_get_integer_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_integer_vec calls get
json_get_integer_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_logical_vec calls get
json_get_logical_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real calls throw_exception, string_to_real
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_real_vec calls get
json_get_real_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string calls throw_exception, integer_to_string, escape_string, real_to_string
json_get_string_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
json_get_string_vec calls get
json_get_string_vec_by_path calls throw_exception, json_clear_exceptions, get, flag_not_found
escape_string calls valid_json_hex
json_get_by_path_default calls add, throw_exception, json_value_create, to_array, to_null, to_object, json_clear_exceptions, string_to_integer, get_child
json_get_by_path_jsonpath_bracket calls add, throw_exception, json_value_create, to_null, json_clear_exceptions, string_to_integer, get_child, convert
json_get_by_path_rfc6901 calls throw_exception, json_clear_exceptions, string_to_integer, get_child, decode_rfc6901
real_to_string calls compact_real_string
convert calls throw_exception, create_array, create_null, info, create_object, json_value_replace
decode_rfc6901 calls replace_string
json_string_info calls throw_exception, info, json_clear_exceptions, get
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_value_get_child_by_name calls throw_exception, json_clear_exceptions, name_equal
json_value_replace calls insert_after, json_value_remove
json_value_create_object calls json_value_create, to_object
json_value_remove calls destroy
name_equal calls name_strings_equal
json_value_insert_after_child_by_index calls get_child, insert_after
name_strings_equal calls lowercase_string
json_parse_file calls parse_value
json_parse_string calls parse_value
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2