wrap_json_value_rename – JSON-Fortran
wrap_json_value_rename Subroutine
Jacob Williams
4/29/2016
7 statements
Source File
private subroutine wrap_json_value_rename(json, p, name)
Alternate version of json_value_rename, where name is kind=CDK.
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
character(kind=CDK, len=*), intent(in) :: name
new variable name
Calls
Source Code
    subroutine wrap_json_value_rename(json,p,name)
    implicit none
    class(json_core),intent(inout)       :: json
    type(json_value),pointer,intent(in)  :: p
    character(kind=CDK,len=*),intent(in) :: name !! new variable name
    call json%rename(p,to_unicode(name))
    end subroutine wrap_json_value_rename
Call graph
wrap_json_value_rename calls to_unicode
to_unicode calls to_uni, to_uni_vec