json_file_print_1 – JSON-Fortran
json_file_print_1 Subroutine
Jacob Williams
12/9/2013
Source File
private subroutine json_file_print_1(me, iunit)
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
integer(kind=IK), intent(in) :: iunit
file unit number (must not be -1)
Description
Prints the JSON file to the specified file unit number.
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
character(kind=CK,len=:), public, allocatable :: dummy
Source Code
    subroutine json_file_print_1(me, iunit)
    implicit none
    class(json_file),intent(inout)  :: me
    integer(IK),intent(in)          :: iunit  !! file unit number (must not be -1)
    integer(IK) :: i
    character(kind=CK,len=:),allocatable :: dummy
    if (iunit/=unit2str) then
        i = iunit
        call json_value_print(me%p,iunit=i,str=dummy,indent=1,colon=.true.)
    else
        call throw_exception('Error in json_file_print_1: iunit must not be -1.')
    end if
    end subroutine json_file_print_1
Call graph
json_file_print_1 calls json_value_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string