json_print_1 – JSON-Fortran
json_print_1 Subroutine
Jacob Williams
6/20/2014
Source File
private subroutine json_print_1(me, iunit)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
integer(kind=IK), intent(in) :: iunit
the file unit (the file must already have been opened, can't be -1).
Description
Print the json_value structure to a file.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=:), public, allocatable :: dummy
Source Code
    subroutine json_print_1(me,iunit)
    implicit none
    type(json_value),pointer,intent(in)  :: me
    integer(IK),intent(in)               :: iunit   !! the file unit (the file must already have been opened, can't be -1).
    character(kind=CK,len=:),allocatable :: dummy
    if (iunit/=unit2str) then
        call json_value_print(me,iunit,str=dummy, indent=1, colon=.true.)
    else
        call throw_exception('Error in json_print: iunit must not be -1.')
    end if
    end subroutine json_print_1
Call graph
json_print_1 calls json_value_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
json_print calls json_print_1, json_print_2
test_7 calls json_print
test_2 calls json_print
test_12 calls json_print
test_8 calls json_print
test_4 calls json_print
test_14 calls json_print
json_print_2 calls json_print
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_8 calls test_8
jf_test_4 calls test_4
jf_test_14 calls test_14