json_print_error_message – JSON-Fortran
json_print_error_message Subroutine
Jacob Williams
Source File
public subroutine json_print_error_message(io_unit)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: io_unit
Description
Print any error message, and then clear the exceptions.
Note
This routine is used by the unit tests. It was originally in json_example.f90, and was moved here 2/26/2015 by Izaak Beekman.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=:), public, allocatable :: error_msg
logical, public :: status_ok
Source Code
    subroutine json_print_error_message(io_unit)
    implicit none
    integer, intent(in), optional :: io_unit
    character(kind=CK,len=:),allocatable :: error_msg
    logical :: status_ok
    !get error message:
    call json_check_for_errors(status_ok, error_msg)
    !print it if there is one:
    if (.not. status_ok) then
        if (present(io_unit)) then
            write(io_unit,'(A)') error_msg
        else
            write(*,'(A)') error_msg
        end if
        deallocate(error_msg)
        call json_clear_exceptions()
    end if
    end subroutine json_print_error_message
Call graph
json_print_error_message calls json_check_for_errors, json_clear_exceptions
test_7 calls json_print_error_message
test_9 calls json_print_error_message
test_2 calls json_print_error_message, add_variables_to_input
test_3 calls json_print_error_message
test_8 calls json_print_error_message
test_13 calls json_print_error_message
add_variables_to_input calls json_print_error_message
test_1 calls json_print_error_message
test_10 calls json_print_error_message
test_5 calls json_print_error_message
test_14 calls json_print_error_message
test_6 calls json_print_error_message
test_11 calls json_print_error_message
test_4 calls json_print_error_message
jf_test_7 calls test_7
jf_test_9 calls test_9
jf_test_2 calls test_2
test_12 calls check_errors
jf_test_12 calls test_12
jf_test_3 calls test_3
jf_test_8 calls test_8
jf_test_13 calls test_13
jf_test_1 calls test_1
jf_test_10 calls test_10
jf_test_5 calls test_5
jf_test_14 calls test_14
jf_test_6 calls test_6
jf_test_11 calls test_11
jf_test_4 calls test_4