json_value_get_by_name_chars – JSON-Fortran
json_value_get_by_name_chars Subroutine
Source File
private subroutine json_value_get_by_name_chars(me, name, p)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: name
the name of a child of "me"
type(json_value), , pointer :: p
pointer to the child
Description
Returns a child in the object or array given the name string.
It is a case-sensitive search, and the name string is not trimmed. So, for example,
     'a ' /= 'A ' /= 'a  '
Note
The "name" input is not a path, and is not parsed like it is in json_get_by_path.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
integer(kind=IK), public :: n_children
Source Code
    subroutine json_value_get_by_name_chars(me, name, p)
    implicit none
    type(json_value),pointer,intent(in) :: me
    character(kind=CK,len=*),intent(in) :: name  !! the name of a child of "me"
    type(json_value),pointer            :: p     !! pointer to the child
    integer(IK) :: i,n_children
    nullify(p)
    if (.not. exception_thrown) then
        if (associated(me)) then
            if (me%var_type==json_object) then
                n_children = json_count(me)
                p => me%children    !start with first one
                do i=1, n_children
                    if (allocated(p%name)) then
                        if (p%name == name) return
                    end if
                    p => p%next
                end do
            end if
            !did not find anything:
            call throw_exception('Error in json_value_get_by_name_chars: '//&
                                 'child variable '//trim(name)//' was not found.')
            nullify(p)
        else
            call throw_exception('Error in json_value_get_by_name_chars: '//&
                                 'pointer is not associated.')
        end if
    end if
    end subroutine json_value_get_by_name_chars
Call graph
json_value_get_by_name_chars calls json_count, throw_exception
throw_exception calls json_throw_exception
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars
json_get_child calls json_value_get_by_name_chars
test_7 calls json_get_child, json_get
json_get_by_path calls json_get_child
jf_test_7 calls test_7
json_file_get_object calls json_get_by_path
json_get_string_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
wrap_json_get_by_path calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_string_with_path calls json_get_string_with_path
json_get calls json_get_by_path, json_get_string_with_path, json_get_logical_with_path, json_get_double_with_path, json_get_integer_with_path, json_get_array_with_path, json_get_logical_vec_with_path, json_get_string_vec_with_path, json_get_logical_vec, json_get_integer_vec, json_get_integer_vec_with_path, json_get_double_vec_with_path, json_get_string_vec, json_get_double_vec
json_file_get_string calls json_get
json_file_get_string_vec calls json_get
json_get_logical_vec_with_path calls json_get
test_12 calls json_get, json_update
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_file_get_integer calls json_get
rename calls json_get, json_update
json_get_logical_vec calls json_get
test_2 calls json_get, json_update
json_file_get_integer_vec calls json_get
json_file_get_double calls json_get
json_update_logical calls json_get
json_get_integer_vec calls json_get
json_file_get_double_vec calls json_get
json_update_double calls json_get
json_get_integer_vec_with_path calls json_get
json_update_integer calls json_get
json_file_get_logical calls json_get
json_get_double_vec_with_path calls json_get
json_update_string calls json_get
json_get_string_vec calls json_get
json_get_double_vec calls json_get
json_file_get_logical_vec calls json_get
test_10 calls json_get, json_remove_if_present, json_update
wrap_json_file_get_string calls json_file_get_string
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_12 calls test_12
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_file_get_integer calls json_file_get_integer
jf_test_2 calls test_2
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_file_get_double calls json_file_get_double
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_integer, json_update_string
json_file_update_integer calls json_update
json_file_update_string calls json_update
test_1 calls json_update
json_file_update_real calls json_update
json_file_update_logical calls json_update
wrap_json_file_update_integer calls json_file_update_integer
json_file_update_string_name_ascii calls json_file_update_string
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_update_logical calls json_file_update_logical
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_update_double calls json_update_double
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
jf_test_10 calls test_10
wrap_json_get_logical_with_path calls json_get_logical_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_array_with_path calls json_get_array_with_path