test_9 – JSON-Fortran
test_9 Subroutine
Source File
public subroutine test_9(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
Open a random JSON file generated by http://www.json-generator.com
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_file), public :: f
real, public :: tstart
real, public :: tend
character(len=:), public, allocatable :: str
Source Code
    subroutine test_9(error_cnt)
    !! Open a random JSON file generated by http://www.json-generator.com
    implicit none
    integer,intent(out) :: error_cnt
    type(json_file) :: f
    real :: tstart, tend
    character(len=:),allocatable :: str
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 9a '
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '  Load a file using json_file%load_file'
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'Loading file: '//trim(filename)
    call cpu_time(tstart)
    call f%load_file(dir//filename)
    call cpu_time(tend)
    write(error_unit,'(A,1X,F10.3,1X,A)') 'Elapsed time: ',tend-tstart,' sec'
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    else
        write(error_unit,'(A)') 'File successfully read'
    end if
    write(error_unit,'(A)') ''
    !cleanup:
    call f%destroy()
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 9b '
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '  Load a file using json_file%load_from_string'
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') 'Loading file: '//trim(filename)
    call cpu_time(tstart)
    call read_file(dir//filename, str)
    if (allocated(str)) then
        call f%load_from_string(str)
        call cpu_time(tend)
        write(error_unit,'(A,1X,F10.3,1X,A)') 'Elapsed time to parse: ',tend-tstart,' sec'
        if (json_failed()) then
            call json_print_error_message(error_unit)
            error_cnt = error_cnt + 1
        else
            write(error_unit,'(A)') 'File successfully read'
        end if
        write(error_unit,'(A)') ''
        !write(error_unit,'(A)') str   !!!! test !!!!
        !write(error_unit,'(A)') ''    !!!! test !!!!
    else
        write(error_unit,'(A)') 'Error loading file'
    end if
    !cleanup:
    call f%destroy()
    end subroutine test_9
Call graph
test_9 calls json_initialize, read_file, json_failed, json_print_error_message
json_initialize calls json_clear_exceptions, throw_exception
json_print_error_message calls json_clear_exceptions, json_check_for_errors
throw_exception calls json_throw_exception
jf_test_9 calls test_9