test_8 – JSON-Fortran
test_8 Subroutine
Source File
public subroutine test_8(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
read a JSON structure from a string
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p
character(len=*), public, parameter :: newline = achar(10)
character(len=*), public, parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
character(len=*), public, parameter :: str2 = '{ "label": "foo",'//newline//' "value": "bar",'//newline//' "empty_array": [],'//newline//' "empty_object": {}'//newline//'}'
character(len=*), public, parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
Source Code
    subroutine test_8(error_cnt)
    !! read a JSON structure from a string
    implicit none
    integer,intent(out) :: error_cnt
    type(json_value),pointer :: p
    character(len=*),parameter :: newline = achar(10)
    character(len=*),parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
    character(len=*),parameter :: str2 = '{ "label": "foo",'//newline//&
                                         '  "value": "bar",'//newline//&
                                         '  "empty_array": [],'//newline//&
                                         '  "empty_object": {}' //newline//&
                                         '}'
    character(len=*),parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 8 : read JSON from string'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 1:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '{ "part a" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 2:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str2, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part b" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Invalid test:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str_invalid, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
    else
        write(error_unit,'(A)') 'This should have failed!'
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part c" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') '}'
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    end subroutine test_8
Call graph
test_8 calls json_print, json_failed, json_destroy, json_print_error_message, json_initialize, json_parse
json_print calls json_print_1, json_print_2
json_destroy calls json_value_destroy
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_initialize calls throw_exception, json_clear_exceptions
json_parse calls json_parse_file, json_parse_string
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
json_value_destroy calls json_value_destroy, destroy_json_data
json_parse_file calls json_initialize, throw_exception, annotate_invalid_json, parse_value, json_value_create
json_parse_string calls json_initialize, annotate_invalid_json, parse_value, json_value_create
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
parse_value calls throw_exception, to_string, parse_array, pop_char, parse_number, parse_string, to_logical, push_char, to_object, to_array, parse_for_chars, to_null, parse_object
to_string calls destroy_json_data
parse_array calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, json_add
parse_number calls throw_exception, pop_char, push_char, to_double, to_integer, string_to_integer, string_to_double
parse_string calls throw_exception, pop_char, valid_json_hex
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_object calls destroy_json_data
to_array calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
to_null calls destroy_json_data
parse_object calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, parse_string, parse_object, json_add
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_double calls json_value_create, json_add, to_double
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_double calls destroy_json_data
to_integer calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
jf_test_8 calls test_8