test_14 – JSON-Fortran
test_14 Subroutine
Source File
public subroutine test_14(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
report number of errors to caller
Description
Tests the traversal of a JSON structure
It traverses the structure, looks for all "name" variables, and changes the name.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: json
Source Code
    subroutine test_14(error_cnt)
    !! Tests the traversal of a JSON structure
    !!
    !! It traverses the structure, looks for all "name" variables, and changes the name.
    implicit none
    integer,intent(out) :: error_cnt !! report number of errors to caller
    type(json_value),pointer  :: json
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   TEST 14'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    error_cnt = 0
    icount = 0 !number of name changes (should be 2)
    call json_initialize() !initialize the module
    call json_parse(dir//filename1,json)  !read the file
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_traverse(json,rename) !traverse all nodes in the structure
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    if (icount/=2) then
        write(error_unit,'(A)') 'Error: should be 2 "name" variables in this file: '//filename1
        error_cnt = error_cnt + 1
    end if
    if (error_cnt==0) then
        write(error_unit,'(A)') ''
        write(error_unit,'(A)') ' All names changed to Fred:'
        write(error_unit,'(A)') ''
        call json_print(json,output_unit)
        write(error_unit,'(A)') ''
    end if
    call json_destroy(json)  !clean up
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    end subroutine test_14
Call graph
test_14 calls json_print, json_failed, json_traverse, json_print_error_message, json_destroy, json_initialize, json_parse
json_print calls json_print_1, json_print_2
json_traverse calls json_traverse, json_count
json_print_error_message calls json_check_for_errors, json_clear_exceptions
json_destroy calls json_value_destroy
json_initialize calls throw_exception, json_clear_exceptions
json_parse calls json_parse_file, json_parse_string
json_print_1 calls json_value_print, throw_exception
json_print_2 calls json_print, throw_exception
json_value_print calls json_value_print, throw_exception, real_to_string, json_count, integer_to_string, write_it
throw_exception calls json_throw_exception
real_to_string calls compact_real_string
json_value_destroy calls json_value_destroy, destroy_json_data
json_parse_file calls json_initialize, throw_exception, annotate_invalid_json, parse_value, json_value_create
json_parse_string calls json_initialize, annotate_invalid_json, parse_value, json_value_create
annotate_invalid_json calls integer_to_string, get_current_line_from_file_sequential, get_current_line_from_file_stream
parse_value calls throw_exception, to_string, parse_array, pop_char, parse_number, parse_string, to_logical, push_char, to_object, to_array, parse_for_chars, to_null, parse_object
to_string calls destroy_json_data
parse_array calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, json_add
parse_number calls throw_exception, pop_char, push_char, to_double, to_integer, string_to_integer, string_to_double
parse_string calls throw_exception, pop_char, valid_json_hex
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_object calls destroy_json_data
to_array calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
to_null calls destroy_json_data
parse_object calls json_destroy, throw_exception, parse_value, json_value_create, pop_char, parse_string, parse_object, json_add
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
json_value_add_logical calls json_value_create, to_logical, json_add
json_value_add_double calls json_value_create, json_add, to_double
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_double calls destroy_json_data
to_integer calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
jf_test_14 calls test_14