wrap_json_get_double_with_path – JSON-Fortran
wrap_json_get_double_with_path Subroutine
Source File
private subroutine wrap_json_get_double_with_path(me, path, value, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: path
real(kind=RK), intent(out) :: value
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_double_with_path, where "path" is kind=CDK
Calls
Source Code
    subroutine wrap_json_get_double_with_path(me, path, value, found)
    implicit none
    type(json_value),pointer             :: me
    character(kind=CDK,len=*),intent(in) :: path
    real(RK),intent(out)                 :: value
    logical(LK),intent(out),optional     :: found
    call json_get_double_with_path(me,to_unicode(path),value,found)
    end subroutine wrap_json_get_double_with_path
Call graph
wrap_json_get_double_with_path calls json_get_double_with_path, to_unicode
json_get_double_with_path calls json_get_double, json_clear_exceptions, json_get_by_path, throw_exception
to_unicode calls to_uni, to_uni_vec
json_get_double calls throw_exception
json_get_by_path calls json_clear_exceptions, throw_exception, json_get_child, string_to_integer
throw_exception calls json_throw_exception
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count