wrap_json_update_double – JSON-Fortran
wrap_json_update_double Subroutine
Source File
private subroutine wrap_json_update_double(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
real(kind=RK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_double, where "name" is kind=CDK.
Calls
Source Code
    subroutine wrap_json_update_double(p,name,val,found)
    implicit none
    type(json_value),pointer             :: p
    character(kind=CDK,len=*),intent(in) :: name
    real(RK),intent(in)                  :: val
    logical(LK),intent(out)              :: found
    call json_update_double(p,to_unicode(name),val,found)
    end subroutine wrap_json_update_double
Call graph
wrap_json_update_double calls json_update_double, to_unicode
json_update_double calls json_add, json_get, to_double, throw_exception, json_info
to_unicode calls to_uni, to_uni_vec
json_add calls json_value_add_logical, json_value_add_double, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
json_get calls json_get_string, json_get_double_vec_with_path, json_get_logical, json_get_integer_vec_with_path, json_get_logical_vec_with_path, json_get_array, json_get_double, json_get_string_vec_with_path, json_get_by_path, json_get_integer, json_get_double_with_path, json_get_logical_with_path, json_get_integer_with_path, json_get_logical_vec, json_get_string_with_path, json_get_string_vec, json_get_integer_vec, json_get_array_with_path, json_get_double_vec
to_double calls destroy_json_data
throw_exception calls json_throw_exception
json_info calls json_count
json_value_add_logical calls json_add, json_value_create, to_logical
json_value_add_double calls json_add, to_double, json_value_create
json_value_add_integer calls json_add, json_value_create, to_integer
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_logical calls destroy_json_data
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
json_get_string calls throw_exception, unescape_string
json_get_double_vec_with_path calls json_get
json_get_logical calls throw_exception
json_get_integer_vec_with_path calls json_get
json_get_logical_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
json_get_double calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_by_path calls throw_exception, json_get_child, json_clear_exceptions, string_to_integer
json_get_integer calls throw_exception
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
json_get_logical_with_path calls throw_exception, json_get_logical, json_get_by_path, json_clear_exceptions
json_get_integer_with_path calls throw_exception, json_get_by_path, json_get_integer, json_clear_exceptions
json_get_logical_vec calls json_get
json_get_string_with_path calls throw_exception, json_get_string, json_get_by_path, json_clear_exceptions
json_get_string_vec calls json_get
json_get_integer_vec calls json_get
json_get_array_with_path calls throw_exception, json_get_array, json_get_by_path, json_clear_exceptions
json_get_double_vec calls json_get
unescape_string calls to_unicode, throw_exception
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count