wrap_json_value_add_double – JSON-Fortran
wrap_json_value_add_double Subroutine
Source File
private subroutine wrap_json_value_add_double(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
variable name
real(kind=RK), intent(in) :: val
real value
Description
Alternate version of json_value_add_double where "name" is kind=CDK.
Calls
Source Code
    subroutine wrap_json_value_add_double(me, name, val)
    implicit none
    type(json_value),pointer             :: me
    character(kind=CDK,len=*),intent(in) :: name  !! variable name
    real(RK),intent(in)                  :: val   !! real value
    call json_value_add_double(me, to_unicode(name), val)
    end subroutine wrap_json_value_add_double
Call graph
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_double calls json_value_create, json_add, to_double
to_unicode calls to_uni, to_uni_vec
json_add calls json_value_add_double, json_value_add_logical, json_value_add_member, json_value_add_integer, json_value_add_double_vec, json_value_add_logical_vec, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_string
to_double calls destroy_json_data
json_value_add_logical calls json_value_create, json_add, to_logical
json_value_add_integer calls json_value_create, json_add, to_integer
json_value_add_double_vec calls json_value_create, json_add, to_array
json_value_add_logical_vec calls json_value_create, json_add, to_array
json_value_add_integer_vec calls json_value_create, json_add, to_array
json_value_add_string_vec calls json_value_create, json_add, to_array
json_value_add_string calls json_value_create, json_add, escape_string, to_string
to_logical calls destroy_json_data
to_integer calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data