wrap_json_get_double_vec_with_path – JSON-Fortran
wrap_json_get_double_vec_with_path Subroutine
Source File
private subroutine wrap_json_get_double_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: path
real(kind=RK), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_get_double_vec_with_path, where "path" is kind=CDK
Calls
Source Code
    subroutine wrap_json_get_double_vec_with_path(me, path, vec, found)
    implicit none
    type(json_value),pointer                      :: me
    character(kind=CDK,len=*),intent(in)          :: path
    real(RK),dimension(:),allocatable,intent(out) :: vec
    logical(LK),intent(out),optional              :: found
    call json_get_double_vec_with_path(me, to_unicode(path), vec, found)
    end subroutine wrap_json_get_double_vec_with_path
Call graph
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path, to_unicode
json_get_double_vec_with_path calls json_get
to_unicode calls to_uni, to_uni_vec
json_get calls json_get_double_vec_with_path, json_get_string, json_get_logical, json_get_integer_vec_with_path, json_get_logical_vec_with_path, json_get_array, json_get_double, json_get_string_vec_with_path, json_get_by_path, json_get_integer, json_get_double_with_path, json_get_logical_with_path, json_get_integer_with_path, json_get_logical_vec, json_get_string_with_path, json_get_string_vec, json_get_integer_vec, json_get_array_with_path, json_get_double_vec
json_get_string calls unescape_string, throw_exception
json_get_logical calls throw_exception
json_get_integer_vec_with_path calls json_get
json_get_logical_vec_with_path calls json_get
json_get_array calls throw_exception, json_count
json_get_double calls throw_exception
json_get_string_vec_with_path calls json_get
json_get_by_path calls throw_exception, json_get_child, json_clear_exceptions, string_to_integer
json_get_integer calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_logical_with_path calls json_get_logical, json_get_by_path, throw_exception, json_clear_exceptions
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
json_get_logical_vec calls json_get
json_get_string_with_path calls json_get_string, json_get_by_path, throw_exception, json_clear_exceptions
json_get_string_vec calls json_get
json_get_integer_vec calls json_get
json_get_array_with_path calls json_get_array, json_get_by_path, throw_exception, json_clear_exceptions
json_get_double_vec calls json_get
unescape_string calls to_unicode, throw_exception
throw_exception calls json_throw_exception
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars
string_to_integer calls throw_exception
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception, json_count