json_file_rename – JSON-Fortran
json_file_rename Subroutine
Jacob Williams
8 statements
Source File
private subroutine json_file_rename(me, path, name, found)
Rename a variable in a JSON file.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CK, len=*), intent(in) :: path
the path to the variable
character(kind=CK, len=*), intent(in) :: name
the new name
logical(kind=LK), intent(out), optional :: found
if the variable was found
Called by
Source Code
    subroutine json_file_rename(me,path,name,found)
    implicit none
    class(json_file),intent(inout)      :: me
    character(kind=CK,len=*),intent(in) :: path   !! the path to the variable
    character(kind=CK,len=*),intent(in) :: name   !! the new name
    logical(LK),intent(out),optional    :: found  !! if the variable was found
    call me%core%rename(me%p, path, name, found)
    end subroutine json_file_rename
Call graph
json_file_rename_name_ascii calls json_file_rename
json_file_rename_path_ascii calls json_file_rename
wrap_json_file_rename calls json_file_rename