assign_json_file – JSON-Fortran
assign_json_file Subroutine
Jacob Williams
7 statements
Source File
private subroutine assign_json_file(me, f)
Assignment operator for json_core = json_core. This will duplicate the json_core and also perform a deep copy of the json_value data structure.
Type Bound
json_file
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(out) :: me
type(json_file), intent(in) :: f
Calls
Source Code
    subroutine assign_json_file(me,f)
    implicit none
    class(json_file),intent(out) :: me
    type(json_file),intent(in)   :: f
    me%core = f%core ! no pointers here so OK to copy
    call me%core%clone(f%p,me%p)
    end subroutine assign_json_file
Call graph
assign_json_file calls json_clone
json_clone calls json_value_clone_func, json_value_clone_func_nonrecursive
json_value_clone_func calls json_value_clone_func