destroy_json_data – JSON-Fortran
destroy_json_data Subroutine
Jacob Williams
9 statements
Source File
private pure subroutine destroy_json_data(d)
Destroy the data within a json_value, and reset type to json_unknown.
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(inout) :: d
Called by
Source Code
    pure subroutine destroy_json_data(d)
    implicit none
    type(json_value),intent(inout) :: d
    d%var_type = json_unknown
    if (allocated(d%log_value)) deallocate(d%log_value)
    if (allocated(d%int_value)) deallocate(d%int_value)
    if (allocated(d%dbl_value)) deallocate(d%dbl_value)
    if (allocated(d%str_value)) deallocate(d%str_value)
    end subroutine destroy_json_data
Call graph
json_value_destroy calls destroy_json_data, destroy
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_real calls destroy_json_data
to_string calls destroy_json_data
json_get_by_path_default calls to_array, to_null, to_object, add
json_get_by_path_jsonpath_bracket calls to_null, convert, add
json_update_integer calls to_integer, get, add_by_path, info
json_update_logical calls to_logical, get, add_by_path, info
json_update_real calls to_real, get, add_by_path, info
json_update_string calls to_string, get, add_by_path, info
json_value_create_array calls to_array
json_value_create_integer calls to_integer
json_value_create_logical calls to_logical
json_value_create_null calls to_null
json_value_create_object calls to_object
json_value_create_real calls to_real
json_value_create_string calls to_string
parse_number calls to_integer, to_real
parse_value_nonrecursive calls to_array, to_logical, to_null, to_object, to_string, destroy, parse_number, add
parse_value_recursive calls to_array, to_logical, to_null, to_object, to_string, parse_number, parse_array, parse_object
json_create_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_file_destroy calls destroy
json_file_valid_path_op calls destroy, valid_path
json_get_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_value_remove calls destroy
parse_array calls destroy, add
parse_object calls destroy, parse_object, add
assign_string_to_json_file calls json_file_destroy, deserialize
convert calls create_array, create_null, create_object, json_value_replace, info
finalize_json_file calls json_file_destroy
json_add_integer_vec_by_path calls create_array, create, json_value_replace, add, info
json_add_logical_vec_by_path calls create_array, create, json_value_replace, add, info
json_add_null_vec_by_path calls create_array, create, json_value_replace, add, info
json_add_real_vec_by_path calls create_array, create, json_value_replace, add, info
json_add_string_vec_by_path calls create_array, create, json_value_replace, add, info
json_file_add calls json_file_destroy
json_file_add_integer calls create_object, add_by_path
json_file_add_integer_vec calls create_object, add_by_path
json_file_add_logical calls create_object, add_by_path
json_file_add_logical_vec calls create_object, add_by_path
json_file_add_null calls create_object, add_null_by_path
json_file_add_null_vec calls create_object, add_null_by_path
json_file_add_object calls create_object, add_by_path
json_file_add_real calls create_object, add_by_path
json_file_add_real_vec calls create_object, add_by_path
json_file_add_string calls create_object, add_by_path
json_file_add_string_path_ascii calls create_object, json_file_add_string
json_file_add_string_value_ascii calls create_object, json_file_add_string
json_file_add_string_vec calls create_object, add_by_path
json_file_load calls json_file_destroy
json_file_load_from_string calls json_file_destroy
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_add_integer calls create_integer, add
json_value_add_integer_vec calls create_array, add
json_value_add_logical calls create_logical, add
json_value_add_logical_vec calls create_array, add
json_value_add_null calls create_null, add
json_value_add_real_vec calls create_array, add
json_value_add_string calls create_string, add
json_value_add_string_vec calls create_array, add
json_value_remove_if_present calls json_value_remove, get
json_value_replace calls json_value_remove
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_value_create_array calls create_array
wrap_json_value_create_integer calls create_integer
wrap_json_value_create_logical calls create_logical
wrap_json_value_create_null calls create_null
wrap_json_value_create_object calls create_object
wrap_json_value_create_string calls create_string
json_add_integer_by_path calls create, json_value_replace, info
json_add_logical_by_path calls create, json_value_replace, info
json_add_member_by_path calls create, json_value_replace, info
json_add_null_by_path calls create, json_value_replace, info
json_add_real_by_path calls create, json_value_replace, info
json_add_string_by_path calls create, json_value_replace, info
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_string_info calls get, info
json_valid_path calls get
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_null_vec_by_path calls json_add_null_vec_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
wrap_json_create_by_path calls create
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_null calls json_file_add_null
wrap_json_file_add_null_vec calls json_file_add_null_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_remove calls remove_if_present
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_null_by_path calls json_add_null_by_path
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_file_load_from_string calls deserialize
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
wrap_json_value_remove_if_present calls remove_if_present
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
json_file_valid_path calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_value_reverse calls info
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_valid_path calls valid_path
json_value_print calls json_is_vector, json_value_print
wrap_json_file_remove calls remove
json_check_children_for_duplicate_keys calls get_path
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string