json_throw_exception – JSON-Fortran
json_throw_exception Subroutine
Jacob Williams
12/4/2013
18 statements
Source File
private subroutine json_throw_exception(json, msg, found)
Throw an exception in the json_core. This routine sets the error flag, and prevents any subsequent routine from doing anything, until json_clear_exceptions is called.
traceback if the Intel compiler is used.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
character(kind=CK, len=*), intent(in) :: msg
the error message
logical(kind=LK), intent(inout), optional :: found
if the caller is handling the exception with an optimal return argument. If so, json%stop_on_error is ignored.
Called by
Source Code
    subroutine json_throw_exception(json,msg,found)
#ifdef __INTEL_COMPILER
    use ifcore, only: tracebackqq
#endif
    implicit none
    class(json_core),intent(inout)      :: json
    character(kind=CK,len=*),intent(in) :: msg    !! the error message
    logical(LK),intent(inout),optional  :: found  !! if the caller is handling the
                                                  !! exception with an optimal return
                                                  !! argument. If so, `json%stop_on_error`
                                                  !! is ignored.
    logical(LK) :: stop_on_error
    json%exception_thrown = .true.
    json%err_message = trim(msg)
    stop_on_error = json%stop_on_error .and. .not. present(found)
    if (stop_on_error) then
#ifdef __INTEL_COMPILER
        ! for Intel, we raise a traceback and quit
        call tracebackqq(string=trim(msg), user_exit_code=0)
#else
        write(error_unit,'(A)') 'JSON-Fortran Exception: '//trim(msg)
        error stop 1
#endif
    elseif (json%is_verbose) then
        write(output_unit,'(A)') '***********************'
        write(output_unit,'(A)') 'JSON-Fortran Exception: '//trim(msg)
!#if defined __GFORTRAN__
!        call backtrace()  ! (have to compile with -fbacktrace -fall-intrinsics flags)
!#endif
#ifdef __INTEL_COMPILER
        call tracebackqq(user_exit_code=-1)  ! print a traceback and return
#endif
        write(output_unit,'(A)') '***********************'
    end if
    end subroutine json_throw_exception
Call graph
convert calls throw_exception, info, json_value_replace
json_add_integer_by_path calls throw_exception, create, info, json_value_replace
json_add_logical_by_path calls throw_exception, create, info, json_value_replace
json_add_member_by_path calls throw_exception, create, info, json_value_replace
json_add_null_by_path calls throw_exception, create, info, json_value_replace
json_add_real_by_path calls throw_exception, create, info, json_value_replace
json_add_string_by_path calls throw_exception, create, info, json_value_replace
json_add_string_vec_by_path calls throw_exception, add, create, info, json_value_replace
json_check_children_for_duplicate_keys calls throw_exception, get_child, get_path
json_count calls throw_exception
json_create_by_path calls throw_exception, json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_file_move_pointer calls throw_exception, initialize
json_file_print_to_unit calls throw_exception
json_get_alloc_string_vec_by_path calls throw_exception, get
json_get_array calls throw_exception
json_get_array_by_path calls throw_exception, get
json_get_by_path calls throw_exception, json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_get_by_path_default calls throw_exception, add, get_child
json_get_by_path_jsonpath_bracket calls throw_exception, convert, add, get_child
json_get_by_path_rfc6901 calls throw_exception, get_child
json_get_integer calls throw_exception
json_get_integer_by_path calls throw_exception, get
json_get_integer_vec_by_path calls throw_exception, get
json_get_logical calls throw_exception
json_get_logical_by_path calls throw_exception, get
json_get_logical_vec_by_path calls throw_exception, get
json_get_next calls throw_exception
json_get_parent calls throw_exception
json_get_path calls throw_exception, info
json_get_previous calls throw_exception
json_get_real calls throw_exception
json_get_real_by_path calls throw_exception, get
json_get_real_vec_by_path calls throw_exception, get
json_get_string calls throw_exception
json_get_string_by_path calls throw_exception, get
json_get_string_vec_by_path calls throw_exception, get
json_get_tail calls throw_exception
json_info calls throw_exception
json_initialize calls throw_exception
json_is_vector calls throw_exception, info
json_matrix_info calls throw_exception, get_child, info
json_parse_end calls throw_exception
json_parse_file calls throw_exception, json_initialize, json_parse_end, json_check_all_for_duplicate_keys
json_parse_string calls throw_exception, json_initialize, json_parse_end, json_check_all_for_duplicate_keys
json_print_to_filename calls throw_exception
json_print_to_unit calls throw_exception, json_value_print
json_rename_by_path calls throw_exception, get
json_string_info calls throw_exception, get, info
json_traverse calls throw_exception
json_update_integer calls throw_exception, add_by_path, get, info
json_update_logical calls throw_exception, add_by_path, get, info
json_update_real calls throw_exception, add_by_path, get, info
json_update_string calls throw_exception, add_by_path, get, info
json_value_add_member calls throw_exception
json_value_get_child calls throw_exception
json_value_get_child_by_index calls throw_exception
json_value_get_child_by_name calls throw_exception
json_value_print calls throw_exception, json_is_vector, json_value_print
json_value_swap calls throw_exception, json_value_is_child_of
json_value_validate calls throw_exception, json_check_all_for_duplicate_keys
parse_array calls throw_exception, add
parse_for_chars calls throw_exception
parse_object calls throw_exception, parse_object, parse_string, add
parse_string calls throw_exception
parse_value_nonrecursive calls throw_exception, parse_for_chars, parse_string, push_char, add, parse_number
parse_value_recursive calls throw_exception, parse_array, parse_for_chars, parse_object, parse_string, push_char, parse_number
push_char calls throw_exception
string_to_dble calls throw_exception
string_to_int calls throw_exception
wrap_json_throw_exception calls throw_exception
initialize_json_core calls json_initialize
initialize_json_core_in_file calls json_initialize
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_check_all_for_duplicate_keys calls json_traverse
json_file_traverse calls json_traverse
json_value_is_child_of calls json_traverse
json_value_to_string calls json_value_print
parse_number calls push_char, string_to_dble, string_to_int
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_null_by_path calls json_add_null_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
json_core calls initialize_json_core
assign_json_file_to_string calls json_value_to_string
json_add_integer_vec_by_path calls add, create, info, json_value_replace
json_add_logical_vec_by_path calls add, create, info, json_value_replace
json_add_null_vec_by_path calls add, create, info, json_value_replace
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_real_vec_by_path calls add, create, info, json_value_replace
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_null calls add_null_by_path
json_file_add_null_vec calls add_null_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_file_load calls load
json_file_load_from_string calls deserialize
json_file_print_to_string calls json_value_to_string
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_alloc_string_vec calls get, string_info
json_get_integer_vec calls get
json_get_logical_vec calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_vec calls get
json_get_string_vec calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_valid_path calls get
json_value_add_integer calls add
json_value_add_integer_vec calls add
json_value_add_logical calls add
json_value_add_logical_vec calls add
json_value_add_null calls add
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add
json_value_add_string calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
json_value_equals calls get_child, json_value_equals
json_value_insert_after_child_by_index calls get_child, insert_after
json_value_remove_if_present calls get
json_value_reverse calls info
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_create_by_path calls create
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_path calls get_path
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_parse_string calls deserialize
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
wrap_json_value_get_child_by_name calls get
initialize_json_file calls initialize
initialize_json_file_from_string calls initialize, deserialize
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_null_vec_by_path calls json_add_null_vec_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_null calls json_file_add_null
wrap_json_file_add_null_vec calls json_file_add_null_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_file calls initialize_json_file, initialize_json_file_from_string, initialize_json_file_from_string_v2
assign_string_to_json_file calls deserialize
initialize_json_file_from_string_v2 calls deserialize
json_file_remove calls remove_if_present
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_value_replace calls insert_after
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_file_load_from_string calls deserialize
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2
wrap_json_file_remove calls remove
wrap_json_file_valid_path calls valid_path