json_prepare_parser – JSON-Fortran
json_prepare_parser Subroutine
7 statements
Source File
private subroutine json_prepare_parser(json)
Internal routine to be called before parsing JSON. Currently, all this does it allocate the comment_char if none was specified.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
Called by
Source Code
    subroutine json_prepare_parser(json)
    implicit none
    class(json_core),intent(inout) :: json
    if (json%allow_comments .and. .not. allocated(json%comment_char)) then
        ! comments are enabled, but user hasn't set the comment char,
        ! so in this case use the default:
        json%comment_char = CK_'/!#'
    end if
    end subroutine json_prepare_parser
Call graph
json_parse_file calls json_prepare_parser
json_parse_string calls json_prepare_parser
json_file_load calls load
json_file_load_from_string calls deserialize
wrap_json_parse_string calls deserialize
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
wrap_json_file_load_from_string calls deserialize
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2