json_value_create – JSON-Fortran
json_value_create Subroutine
6 statements
Source File
private subroutine json_value_create(p)
Allocate a json_value pointer variable. This should be called before adding data to it.
Example
    type(json_value),pointer :: var
    call json_value_create(var)
    call json%to_real(var,1.0_RK)
Notes
This routine does not check for exceptions.
The pointer should not already be allocated, or a memory leak will occur.
Arguments
Type Intent Optional Attributes Name
type(json_value), pointer :: p
Called by
Source Code
    subroutine json_value_create(p)
    implicit none
    type(json_value),pointer :: p
    nullify(p)
    allocate(p)
    end subroutine json_value_create
Call graph
json_get_by_path_default calls json_value_create, add
json_get_by_path_jsonpath_bracket calls json_value_create, convert, add
json_parse_file calls json_value_create
json_parse_string calls json_value_create
json_value_create_array calls json_value_create
json_value_create_integer calls json_value_create
json_value_create_logical calls json_value_create
json_value_create_null calls json_value_create
json_value_create_object calls json_value_create
json_value_create_real calls json_value_create
json_value_create_string calls json_value_create
parse_array calls json_value_create, add
parse_object calls json_value_create, parse_object, add
parse_value_nonrecursive calls json_value_create, add
json_create_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_get_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket
parse_value_recursive calls parse_array, parse_object
convert calls create_array, create_null, create_object, info
json_add_integer_vec_by_path calls create_array, create, add, info
json_add_logical_vec_by_path calls create_array, create, add, info
json_add_null_vec_by_path calls create_array, create, add, info
json_add_real_vec_by_path calls create_array, create, add, info
json_add_string_vec_by_path calls create_array, create, add, info
json_file_add_integer calls create_object, add_by_path
json_file_add_integer_vec calls create_object, add_by_path
json_file_add_logical calls create_object, add_by_path
json_file_add_logical_vec calls create_object, add_by_path
json_file_add_null calls create_object, add_null_by_path
json_file_add_null_vec calls create_object, add_null_by_path
json_file_add_object calls create_object, add_by_path
json_file_add_real calls create_object, add_by_path
json_file_add_real_vec calls create_object, add_by_path
json_file_add_string calls create_object, add_by_path
json_file_add_string_path_ascii calls create_object, json_file_add_string
json_file_add_string_value_ascii calls create_object, json_file_add_string
json_file_add_string_vec calls create_object, add_by_path
json_file_load calls load
json_file_load_from_string calls deserialize
json_value_add_integer calls create_integer, add
json_value_add_integer_vec calls create_array, add
json_value_add_logical calls create_logical, add
json_value_add_logical_vec calls create_array, add
json_value_add_null calls create_null, add
json_value_add_real_vec calls create_array, add
json_value_add_string calls create_string, add
json_value_add_string_vec calls create_array, add
wrap_json_parse_string calls deserialize
wrap_json_value_create_array calls create_array
wrap_json_value_create_integer calls create_integer
wrap_json_value_create_logical calls create_logical
wrap_json_value_create_null calls create_null
wrap_json_value_create_object calls create_object
wrap_json_value_create_string calls create_string
json_add_integer_by_path calls create, info
json_add_logical_by_path calls create, info
json_add_member_by_path calls create, info
json_add_null_by_path calls create, info
json_add_real_by_path calls create, info
json_add_string_by_path calls create, info
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_matrix_info_by_path calls get, matrix_info
json_rename_by_path calls get
json_string_info calls get, info
json_update_integer calls get, add_by_path, info
json_update_logical calls get, add_by_path, info
json_update_real calls get, add_by_path, info
json_update_string calls get, add_by_path, info
json_valid_path calls get
json_value_remove_if_present calls get
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_null_vec_by_path calls json_add_null_vec_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
wrap_json_create_by_path calls create
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_null calls json_file_add_null
wrap_json_file_add_null_vec calls json_file_add_null_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
assign_string_to_json_file calls deserialize
initialize_json_file_from_string calls deserialize
initialize_json_file_from_string_v2 calls deserialize
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_value_add_real calls add
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_string_name_ascii calls add
json_value_add_string_val_ascii calls add
json_value_add_string_vec_name_ascii calls add
json_value_add_string_vec_val_ascii calls add
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_null_by_path calls json_add_null_by_path
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_file_load_from_string calls deserialize
wrap_json_value_add_integer calls add
wrap_json_value_add_integer_vec calls add
wrap_json_value_add_logical calls add
wrap_json_value_add_logical_vec calls add
wrap_json_value_add_null calls add
wrap_json_value_add_real calls add
wrap_json_value_add_real32 calls add
wrap_json_value_add_real32_vec calls add
wrap_json_value_add_real_vec calls add
wrap_json_value_add_string calls add
wrap_json_value_add_string_vec calls add
json_file calls initialize_json_file_from_string, initialize_json_file_from_string_v2
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_file_variable_matrix_info calls matrix_info
json_get_path calls info
json_is_vector calls info
json_matrix_info calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_reverse calls info
wrap_assign_string_to_json_file calls assign_string_to_json_file
wrap_initialize_json_file_from_string calls initialize_json_file_from_string
wrap_initialize_json_file_from_string_v2 calls initialize_json_file_from_string_v2
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_matrix_info_by_path calls matrix_info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
json_value_print calls json_is_vector, json_value_print
json_check_children_for_duplicate_keys calls get_path
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_file_variable_matrix_info calls matrix_info
wrap_json_get_path calls get_path
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string