json_value_get_child_by_index – JSON-Fortran
json_value_get_child_by_index Subroutine
61 statements
Source File
private subroutine json_value_get_child_by_index(json, p, idx, child, found)
Returns a child in the object or array given the index.
Type Bound
json_core
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
object or array JSON data
integer(kind=IK), intent(in) :: idx
index of the child (this is a 1-based Fortran style array index).
type(json_value), pointer :: child
pointer to the child
logical(kind=LK), intent(out), optional :: found
true if the value was found (if not present, an exception will be thrown if it was not found. If present and not found, no exception will be thrown).
Calls
Called by
Source Code
    subroutine json_value_get_child_by_index(json, p, idx, child, found)
    implicit none
    class(json_core),intent(inout)      :: json
    type(json_value),pointer,intent(in) :: p      !! object or array JSON data
    integer(IK),intent(in)              :: idx    !! index of the child
                                                  !! (this is a 1-based Fortran
                                                  !! style array index).
    type(json_value),pointer            :: child  !! pointer to the child
    logical(LK),intent(out),optional    :: found  !! true if the value was found
                                                  !! (if not present, an exception
                                                  !! will be thrown if it was not
                                                  !! found.  If present and not
                                                  !! found, no exception will be
                                                  !! thrown).
    integer(IK) :: i  !! counter
    nullify(child)
    if (.not. json%exception_thrown) then
        if (associated(p%children)) then
            ! If getting first or last child, we can do this quickly.
            ! Otherwise, traverse the list.
            if (idx==1) then
                child => p%children  ! first one
            elseif (idx==p%n_children) then
                if (associated(p%tail)) then
                    child => p%tail  ! last one
                else
                    call json%throw_exception('Error in json_value_get_child_by_index:'//&
                                              ' child%tail is not associated.',found)
                end if
            elseif (idx<1 .or. idx>p%n_children) then
                call json%throw_exception('Error in json_value_get_child_by_index:'//&
                                          ' idx is out of range.',found)
            else
                ! if idx is closer to the end, we traverse the list backward from tail,
                ! otherwise we traverse it forward from children:
                if (p%n_children-idx < idx) then  ! traverse backward
                    child => p%tail
                    do i = 1, p%n_children - idx
                        if (associated(child%previous)) then
                            child => child%previous
                        else
                            call json%throw_exception('Error in json_value_get_child_by_index:'//&
                                                      ' child%previous is not associated.',found)
                            nullify(child)
                            exit
                        end if
                    end do
                else  ! traverse forward
                    child => p%children
                    do i = 1, idx - 1
                        if (associated(child%next)) then
                            child => child%next
                        else
                            call json%throw_exception('Error in json_value_get_child_by_index:'//&
                                                      ' child%next is not associated.',found)
                            nullify(child)
                            exit
                        end if
                    end do
                end if
            end if
        else
            call json%throw_exception('Error in json_value_get_child_by_index:'//&
                                      ' p%children is not associated.',found)
        end if
        ! found output:
        if (json%exception_thrown) then
            if (present(found)) then
                call json%clear_exceptions()
                found = .false.
            end if
        else
            if (present(found)) found = .true.
        end if
    else
        if (present(found)) found = .false.
    end if
    end subroutine json_value_get_child_by_index
Call graph
json_value_get_child_by_index calls throw_exception, json_clear_exceptions
json_check_children_for_duplicate_keys calls get_child, get_path
json_get_by_path_default calls get_child
json_get_by_path_jsonpath_bracket calls get_child, convert
json_get_by_path_rfc6901 calls get_child
json_matrix_info calls get_child, info
json_value_equals calls get_child, json_value_equals
json_value_insert_after_child_by_index calls get_child, insert_after
json_create_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket
json_get_by_path calls json_get_by_path_default, json_get_by_path_jsonpath_bracket, json_get_by_path_rfc6901
json_file_variable_matrix_info calls matrix_info
json_matrix_info_by_path calls matrix_info, get
json_value_replace calls insert_after
wrap_json_matrix_info_by_path calls matrix_info
convert calls json_value_replace, info
json_add_integer_by_path calls create, json_value_replace, info
json_add_integer_vec_by_path calls create, json_value_replace, info
json_add_logical_by_path calls create, json_value_replace, info
json_add_logical_vec_by_path calls create, json_value_replace, info
json_add_member_by_path calls create, json_value_replace, info
json_add_real_by_path calls create, json_value_replace, info
json_add_real_vec_by_path calls create, json_value_replace, info
json_add_string_by_path calls create, json_value_replace, info
json_add_string_vec_by_path calls create, json_value_replace, info
json_file_get_alloc_string_vec calls get
json_file_get_integer calls get
json_file_get_integer_vec calls get
json_file_get_logical calls get
json_file_get_logical_vec calls get
json_file_get_object calls get
json_file_get_real calls get
json_file_get_real32 calls get
json_file_get_real32_vec calls get
json_file_get_real_vec calls get
json_file_get_string calls get
json_file_get_string_vec calls get
json_get_alloc_string_vec calls get, string_info
json_get_alloc_string_vec_by_path calls get
json_get_array_by_path calls get
json_get_integer_by_path calls get
json_get_integer_vec calls get
json_get_integer_vec_by_path calls get
json_get_logical_by_path calls get
json_get_logical_vec calls get
json_get_logical_vec_by_path calls get
json_get_real32 calls get
json_get_real32_by_path calls get
json_get_real32_vec calls get
json_get_real32_vec_by_path calls get
json_get_real_by_path calls get
json_get_real_vec calls get
json_get_real_vec_by_path calls get
json_get_string_by_path calls get
json_get_string_vec calls get
json_get_string_vec_by_path calls get
json_info_by_path calls get, info
json_rename_by_path calls get
json_string_info calls get, info
json_update_integer calls get, add_by_path, info
json_update_logical calls get, add_by_path, info
json_update_real calls get, add_by_path, info
json_update_string calls get, add_by_path, info
json_valid_path calls get
json_value_remove_if_present calls get
wrap_json_create_by_path calls create
wrap_json_get_alloc_string_vec_by_path calls get
wrap_json_get_array_by_path calls get
wrap_json_get_by_path calls get
wrap_json_get_integer_by_path calls get
wrap_json_get_integer_vec_by_path calls get
wrap_json_get_logical_by_path calls get
wrap_json_get_logical_vec_by_path calls get
wrap_json_get_real32_by_path calls get
wrap_json_get_real32_vec_by_path calls get
wrap_json_get_real_by_path calls get
wrap_json_get_real_vec_by_path calls get
wrap_json_get_string_by_path calls get
wrap_json_get_string_vec_by_path calls get
wrap_json_value_get_child_by_name calls get
json_add_string_by_path_path_ascii calls json_add_string_by_path
json_add_string_by_path_value_ascii calls json_add_string_by_path
json_add_string_vec_by_path_path_ascii calls json_add_string_vec_by_path
json_add_string_vec_by_path_value_ascii calls json_add_string_vec_by_path
wrap_json_add_integer_by_path calls json_add_integer_by_path
wrap_json_add_integer_vec_by_path calls json_add_integer_vec_by_path
wrap_json_add_logical_by_path calls json_add_logical_by_path
wrap_json_add_logical_vec_by_path calls json_add_logical_vec_by_path
wrap_json_add_member_by_path calls json_add_member_by_path
wrap_json_add_real_by_path calls json_add_real_by_path
wrap_json_add_real_vec_by_path calls json_add_real_vec_by_path
wrap_json_add_string_by_path calls json_add_string_by_path
wrap_json_add_string_vec_by_path calls json_add_string_vec_by_path
wrap_json_file_variable_matrix_info calls matrix_info
json_add_real32_by_path calls add_by_path
json_add_real32_vec_by_path calls add_by_path
json_file_add_integer calls add_by_path
json_file_add_integer_vec calls add_by_path
json_file_add_logical calls add_by_path
json_file_add_logical_vec calls add_by_path
json_file_add_object calls add_by_path
json_file_add_real calls add_by_path
json_file_add_real32 calls add_by_path
json_file_add_real32_vec calls add_by_path
json_file_add_real_vec calls add_by_path
json_file_add_string calls add_by_path
json_file_add_string_vec calls add_by_path
json_file_remove calls remove_if_present
json_file_update_integer calls update
json_file_update_logical calls update
json_file_update_real calls update
json_file_update_string calls update
json_file_valid_path calls valid_path
json_file_valid_path_op calls valid_path
json_file_variable_info calls info
json_get_path calls info
json_is_vector calls info
json_update_real32 calls update
json_update_string_name_ascii calls update
json_update_string_val_ascii calls update
json_value_reverse calls info
wrap_json_add_real32_by_path calls add_by_path
wrap_json_add_real32_vec_by_path calls add_by_path
wrap_json_file_get_alloc_string_vec calls get
wrap_json_file_get_integer calls get
wrap_json_file_get_integer_vec calls get
wrap_json_file_get_logical calls get
wrap_json_file_get_logical_vec calls get
wrap_json_file_get_object calls get
wrap_json_file_get_real calls get
wrap_json_file_get_real32 calls get
wrap_json_file_get_real32_vec calls get
wrap_json_file_get_real_vec calls get
wrap_json_file_get_string calls get
wrap_json_file_get_string_vec calls get
wrap_json_info_by_path calls info
wrap_json_update_integer calls update
wrap_json_update_logical calls update
wrap_json_update_real calls update
wrap_json_update_real32 calls update
wrap_json_update_string calls update
wrap_json_valid_path calls valid_path
wrap_json_value_remove_if_present calls remove_if_present
json_file_add_string_path_ascii calls json_file_add_string
json_file_add_string_value_ascii calls json_file_add_string
json_file_add_string_vec_path_ascii calls json_file_add_string_vec
json_file_add_string_vec_vec_ascii calls json_file_add_string_vec
json_value_print calls json_is_vector, json_value_print
wrap_json_file_add_integer calls json_file_add_integer
wrap_json_file_add_integer_vec calls json_file_add_integer_vec
wrap_json_file_add_logical calls json_file_add_logical
wrap_json_file_add_logical_vec calls json_file_add_logical_vec
wrap_json_file_add_object calls json_file_add_object
wrap_json_file_add_real calls json_file_add_real
wrap_json_file_add_real32 calls json_file_add_real32
wrap_json_file_add_real32_vec calls json_file_add_real32_vec
wrap_json_file_add_real_vec calls json_file_add_real_vec
wrap_json_file_add_string calls json_file_add_string
wrap_json_file_add_string_vec calls json_file_add_string_vec
json_file_update_real32 calls update
json_file_update_string_name_ascii calls update
json_file_update_string_val_ascii calls update
json_print_to_unit calls json_value_print
json_value_to_string calls json_value_print
wrap_json_file_remove calls remove
wrap_json_file_update_integer calls update
wrap_json_file_update_logical calls update
wrap_json_file_update_real calls update
wrap_json_file_update_real32 calls update
wrap_json_file_update_string calls update
wrap_json_file_valid_path calls valid_path
wrap_json_file_variable_info calls info
wrap_json_get_path calls get_path
assign_json_file_to_string calls json_value_to_string
json_file_print_to_string calls json_value_to_string