parse_value_recursive – JSON-Fortran
parse_value_recursive Subroutine
57 statements
Source File
private recursive subroutine parse_value_recursive(json, unit, str, value)
Core parsing routine. This is the original recursive routine.
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
integer(kind=IK), intent(in) :: unit
file unit number
character(kind=CK, len=*), intent(in) :: str
string containing JSON data (only used if unit=0)
type(json_value), pointer :: value
JSON data that is extracted
Calls
Source Code
    recursive subroutine parse_value_recursive(json, unit, str, value)
    implicit none
    class(json_core),intent(inout)      :: json
    integer(IK),intent(in)              :: unit   !! file unit number
    character(kind=CK,len=*),intent(in) :: str    !! string containing JSON
                                                  !! data (only used if `unit=0`)
    type(json_value),pointer            :: value  !! JSON data that is extracted
    logical(LK)              :: eof !! end-of-file flag
    character(kind=CK,len=1) :: c   !! character read from file
                                    !! (or string) by [[pop_char]]
#if defined __GFORTRAN__
    character(kind=CK,len=:),allocatable :: tmp  !! this is a work-around for a bug
                                                 !! in the gfortran 4.9 compiler.
#endif
    if (.not. json%exception_thrown) then
        !the routine is being called incorrectly.
        if (.not. associated(value)) then
            call json%throw_exception('Error in parse_value: value pointer not associated.')
            return
        end if
        ! pop the next non whitespace character off the file
        call json%pop_char(unit, str=str, eof=eof, skip_ws=.true., &
                           skip_comments=json%allow_comments, c=c)
        if (eof) then
            return
        else
            select case (c)
            case (start_object)
                ! start object
                call json%to_object(value)    !allocate class
                call json%parse_object(unit, str, value, expecting_next_element=.false.)
            case (start_array)
                ! start array
                call json%to_array(value)    !allocate class
                call json%parse_array(unit, str, value)
            case (end_array)
                ! end an empty array
                call json%push_char(c)
                if (associated(value)) then
                    deallocate(value)
                    nullify(value)
                end if
            case (quotation_mark)
                ! string
                call json%to_string(value)    !allocate class
                select case (value%var_type)
                case (json_string)
#if defined __GFORTRAN__
                    ! write to a tmp variable because of
                    ! a bug in 4.9 gfortran compiler.
                    call json%parse_string(unit,str,tmp)
                    value%str_value = tmp
                    if (allocated(tmp))  deallocate(tmp)
#else
                    call json%parse_string(unit,str,value%str_value)
#endif
                end select
            case (CK_'t') !true_str(1:1) gfortran bug work around
                !true
                call json%parse_for_chars(unit, str, true_str(2:))
                !allocate class and set value:
                if (.not. json%exception_thrown) call json%to_logical(value,.true.)
            case (CK_'f') !false_str(1:1) gfortran bug work around
                !false
                call json%parse_for_chars(unit, str, false_str(2:))
                !allocate class and set value:
                if (.not. json%exception_thrown) call json%to_logical(value,.false.)
            case (CK_'n') !null_str(1:1) gfortran bug work around
                !null
                call json%parse_for_chars(unit, str, null_str(2:))
                if (.not. json%exception_thrown) call json%to_null(value) ! allocate class
            case(CK_'-', CK_'0': CK_'9', CK_'.', CK_'+')
                call json%push_char(c)
                call json%parse_number(unit, str, value)
            case default
                call json%throw_exception('Error in parse_value:'//&
                                          ' Unexpected character while parsing value. "'//&
                                          c//'"')
            end select
        end if
    end if
    end subroutine parse_value_recursive
Call graph
parse_value_recursive calls throw_exception, parse_array, parse_for_chars, parse_number, parse_object, parse_string, pop_char, push_char, to_array, to_logical, to_null, to_object, to_string
parse_array calls throw_exception, pop_char, add, destroy, json_value_create
parse_for_chars calls throw_exception, pop_char
parse_number calls pop_char, push_char, json_clear_exceptions, string_to_dble, string_to_int, to_integer, to_real
parse_object calls throw_exception, parse_object, parse_string, pop_char, add, destroy, json_value_create
parse_string calls throw_exception, pop_char, unescape_string
push_char calls throw_exception, integer_to_string
to_array calls destroy_json_data
to_logical calls destroy_json_data
to_null calls destroy_json_data
to_object calls destroy_json_data
to_string calls destroy_json_data
string_to_dble calls throw_exception
string_to_int calls throw_exception, string_to_integer
to_integer calls destroy_json_data
to_real calls destroy_json_data
unescape_string calls valid_json_hex
json_value_add_integer calls add, create_integer
json_value_add_integer_vec calls add, create_array
json_value_add_logical calls add, create_logical
json_value_add_logical_vec calls add, create_array
json_value_add_member calls throw_exception
json_value_add_null calls add, create_null
json_value_add_real calls add, create_real
json_value_add_real32 calls add
json_value_add_real32_vec calls add
json_value_add_real_vec calls add, create_array
json_value_add_string calls add, create_string
json_value_add_string_vec calls add, create_array
json_value_destroy calls destroy, destroy_json_data
json_value_create_array calls to_array, json_value_create
json_value_create_integer calls json_value_create, to_integer
json_value_create_logical calls to_logical, json_value_create
json_value_create_null calls to_null, json_value_create
json_value_create_real32 calls create_real
json_value_create_string calls to_string, json_value_create